"""Tests for AI signal detection."""

from __future__ import annotations

import unittest

# Import the module under test
import aiir.cli as cli


class TestDetectAISignals(unittest.TestCase):
    """Tests for detect_ai_signals()."""

    def test_copilot_coauthor(self):
        msg = "feat: add auth\n\nCo-authored-by: Copilot <copilot@github.com>"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(len(signals) > 0)
        self.assertTrue(any("copilot" in s for s in signals))

    def test_chatgpt_generated(self):
        msg = "refactor: update parser\n\nGenerated by ChatGPT"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(any("chatgpt" in s for s in signals))

    def test_claude_code(self):
        msg = "fix: resolve null check\n\nClaude Code assisted this change"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(any("claude code" in s for s in signals))

    def test_aider_prefix(self):
        msg = "aider: refactored the auth module"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(any("aider" in s for s in signals))

    def test_no_signals_human(self):
        msg = "fix: typo in README\n\nSimple fix."
        ai_signals, bot_signals = cli.detect_ai_signals(msg)
        self.assertEqual(len(ai_signals), 0)
        self.assertEqual(len(bot_signals), 0)

    def test_bot_author_name(self):
        _, bot_signals = cli.detect_ai_signals(
            "chore: update deps",
            author_name="dependabot[bot]",
            author_email="dependabot@github.com",
        )
        self.assertTrue(any("dependabot" in s for s in bot_signals))

    def test_bot_committer(self):
        _, bot_signals = cli.detect_ai_signals(
            "update lock",
            committer_name="renovate[bot]",
            committer_email="renovate@example.com",
        )
        self.assertTrue(any("renovate" in s for s in bot_signals))

    def test_trailer_detected(self):
        msg = "feat: add feature\n\nGenerated-by: copilot-v2"
        signals, _ = cli.detect_ai_signals(msg)
        # VULN-07: Should only record trailer key, not the value
        trailer_signals = [s for s in signals if s.startswith("trailer:")]
        for s in trailer_signals:
            self.assertNotIn("copilot-v2", s, "Trailer value should not be leaked")
            self.assertIn("generated-by", s)

    def test_trailer_value_not_leaked(self):
        """VULN-07: Internal tool names in trailers must not appear in signals."""
        msg = "fix: update\n\nTool: proprietary-internal-system-v3.2"
        signals, _ = cli.detect_ai_signals(msg)
        trailer_signals = [s for s in signals if s.startswith("trailer:")]
        self.assertTrue(len(trailer_signals) > 0)
        for s in trailer_signals:
            self.assertNotIn("proprietary", s)

    def test_case_insensitive(self):
        msg = "chore: update\n\nCO-AUTHORED-BY: COPILOT"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(len(signals) > 0)

    def test_multiple_signals(self):
        msg = "AI-generated code\n\nCo-authored-by: Copilot\nGenerated-by: copilot"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(len(signals) >= 2)

    def test_windsurf_signal(self):
        msg = "feat: new component\n\nCreated with Windsurf editor"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(any("windsurf" in s for s in signals))


# ---------------------------------------------------------------------------
# Ref validation tests (VULN-03)
# ---------------------------------------------------------------------------


class TestRedTeamSignalEvasion(unittest.TestCase):
    """Tests for R5-01/02/03 signal evasion fixes."""

    def test_r5_01_combining_mark_evasion_blocked(self):
        """Combining diacritical marks must not evade signal detection."""
        # U+0336 COMBINING LONG STROKE OVERLAY between 'o' and 'p'
        msg = "Co-authored-by: co\u0336pilot"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(
            len(signals) > 0, f"Combining mark evasion not blocked: {msg!r}"
        )

    def test_r5_02_variation_selector_evasion_blocked(self):
        """Variation selectors must not evade signal detection."""
        # U+FE0E VARIATION SELECTOR-15 between 'p' and 'i'
        msg = "Co-authored-by: cop\ufe0eilot"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(
            len(signals) > 0, f"Variation selector evasion not blocked: {msg!r}"
        )

    def test_r5_03_tab_whitespace_evasion_blocked(self):
        """Tab characters in trailers must not evade signal detection."""
        msg = "Co-authored-by:\tcopilot"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(
            len(signals) > 0, f"Tab whitespace evasion not blocked: {msg!r}"
        )

    def test_r5_03_double_space_evasion_blocked(self):
        """Double spaces in trailers must not evade signal detection."""
        msg = "Co-authored-by:  copilot"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(len(signals) > 0, f"Double-space evasion not blocked: {msg!r}")

    def test_r5_01_normal_signals_still_detected(self):
        """Normal signals must still be detected after Mn/Me stripping."""
        msg = "Co-authored-by: copilot"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(len(signals) > 0)


class TestMissingAISignals(unittest.TestCase):
    """R21-PUB-01: AI detection must cover major AI coding tools."""

    def test_amazon_q_detected(self):
        signals, _ = cli.detect_ai_signals("feat: update\n\nGenerated by Amazon Q")
        self.assertTrue(any("amazon q" in s for s in signals))

    def test_codewhisperer_detected(self):
        signals, _ = cli.detect_ai_signals("fix: types\n\nCodeWhisperer assisted")
        self.assertTrue(any("codewhisperer" in s for s in signals))

    def test_amazon_codewhisperer_detected(self):
        signals, _ = cli.detect_ai_signals(
            "fix: auth\n\nAmazon CodeWhisperer generated this"
        )
        self.assertTrue(any("amazon codewhisperer" in s for s in signals))

    def test_devin_detected(self):
        signals, _ = cli.detect_ai_signals(
            "refactor: improve perf\n\nGenerated by Devin"
        )
        self.assertTrue(any("devin" in s for s in signals))

    def test_gemini_code_assist_detected(self):
        signals, _ = cli.detect_ai_signals(
            "feat: add endpoint\n\nGemini Code Assist wrote this"
        )
        self.assertTrue(any("gemini code assist" in s for s in signals))

    def test_google_gemini_detected(self):
        signals, _ = cli.detect_ai_signals(
            "fix: null check\n\nGoogle Gemini authored this"
        )
        self.assertTrue(any("google gemini" in s for s in signals))

    def test_tabnine_detected(self):
        signals, _ = cli.detect_ai_signals("refactor: cleanup\n\nTabnine AI completion")
        self.assertTrue(any("tabnine" in s for s in signals))

    def test_codegen_by_gemini_detected(self):
        signals, _ = cli.detect_ai_signals("feat: new module\n\nCodegen by Gemini")
        self.assertTrue(any("codegen by gemini" in s for s in signals))


class TestMissingBotPatterns(unittest.TestCase):
    """R21-PUB-02: Bot author detection must include new AI tool bots."""

    def test_devin_bot_author(self):
        signals, _ = cli.detect_ai_signals("chore: update", author_name="devin[bot]")
        self.assertTrue(any("devin" in s for s in signals))

    def test_amazon_q_bot_author(self):
        signals, _ = cli.detect_ai_signals("chore: update", author_name="amazon-q[bot]")
        self.assertTrue(any("amazon-q" in s for s in signals))

    def test_tabnine_bot_committer(self):
        signals, _ = cli.detect_ai_signals(
            "chore: update", committer_name="tabnine-bot"
        )
        self.assertTrue(any("tabnine" in s for s in signals))

    def test_gemini_bot_author(self):
        signals, _ = cli.detect_ai_signals("chore: update", author_name="gemini[bot]")
        self.assertTrue(any("gemini" in s for s in signals))


class TestAISignalCoverage(unittest.TestCase):
    """R21-PUB-01: AI_SIGNALS list must include all major tools."""

    def test_ai_signals_count(self):
        """AI_SIGNALS must have at least 30 patterns (was 20 before R21)."""
        self.assertGreaterEqual(len(cli.AI_SIGNALS), 30)

    def test_major_tools_in_signals(self):
        """All major AI coding tools must be in AI_SIGNALS."""
        required = [
            "amazon q",
            "codewhisperer",
            "co-authored-by: devin",
            "gemini code assist",
            "google gemini",
            "tabnine",
            "github copilot",
            "claude code",
            "windsurf",
            "aider:",
            "codeium",
            "sourcegraph cody",
        ]
        for tool in required:
            self.assertIn(tool, cli.AI_SIGNALS, f"Missing AI signal: {tool}")


class TestDetectMutationKillers(unittest.TestCase):
    """Mutation-killing tests for detect_ai_signals().

    Each test targets a specific class of surviving mutant that line-
    coverage-based tests miss (weak assertions, missing boundary checks).
    """

    # ------------------------------------------------------------------
    # Default parameter mutations (mutants 1-4)
    # Mutant changes default "" to "XXXX", which would inject phantom
    # bot signals when the caller omits an author/committer field.
    # ------------------------------------------------------------------

    def test_no_false_positive_when_author_name_omitted(self):
        """Omitting author_name must not produce any signal."""
        ai, bot = cli.detect_ai_signals("chore: update deps")
        self.assertEqual(ai, [])
        self.assertEqual(bot, [])

    def test_no_false_positive_when_all_fields_omitted(self):
        """Calling with only message and no author fields => no signals."""
        ai, bot = cli.detect_ai_signals("docs: fix typo in README")
        self.assertEqual(ai, [])
        self.assertEqual(bot, [])

    def test_empty_author_email_no_signal(self):
        """Explicit empty author_email must not match any pattern."""
        ai, bot = cli.detect_ai_signals("chore: bump", author_email="")
        self.assertEqual(ai, [])
        self.assertEqual(bot, [])

    def test_empty_committer_fields_no_signal(self):
        """Explicit empty committer_name/email => no signals."""
        ai, bot = cli.detect_ai_signals(
            "chore: bump", committer_name="", committer_email=""
        )
        self.assertEqual(ai, [])
        self.assertEqual(bot, [])

    # ------------------------------------------------------------------
    # Message split mutation (mutant 21)
    # Mutant changes message.split("\n") to message.split(None), which
    # splits on any whitespace and breaks trailer parsing (trailers
    # are line-oriented).
    # ------------------------------------------------------------------

    def test_trailer_on_separate_line(self):
        """Trailers must be detected line-by-line, not word-by-word."""
        msg = "feat: add endpoint\n\nGenerated-by: copilot-v2"
        ai, _ = cli.detect_ai_signals(msg)
        trailer_signals = [s for s in ai if s.startswith("trailer:")]
        self.assertTrue(
            len(trailer_signals) > 0,
            "Trailer on its own line must be detected",
        )

    def test_trailer_key_not_in_middle_of_line(self):
        """A word that starts with a trailer key but is mid-line must not
        generate a trailer signal (split(None) would wrongly match it)."""
        msg = "feat: impl\n\nThis does not start with generated-by: copilot"
        ai, _ = cli.detect_ai_signals(msg)
        trailer_signals = [s for s in ai if s.startswith("trailer:")]
        # The line doesn't START with "generated-by:", so no trailer signal.
        # (Message-body match is fine, we're testing trailer specifically.)
        self.assertEqual(
            trailer_signals,
            [],
            "Mid-line trailer key must not generate trailer: signal",
        )

    # ------------------------------------------------------------------
    # AI author pattern exact-string mutations (mutants 29-48)
    # Mutants corrupt bot names (e.g. "copilot" → "COPILOT" or
    # "XXcopilotXX").  Tests verify each pattern matches in author fields.
    # ------------------------------------------------------------------

    def test_ai_author_copilot(self):
        ai, _ = cli.detect_ai_signals("chore: x", author_name="copilot[bot]")
        matched = [s for s in ai if "copilot" in s]
        self.assertTrue(matched, "copilot in author_name must be detected")

    def test_ai_author_coderabbit(self):
        ai, _ = cli.detect_ai_signals("chore: x", author_name="coderabbit[bot]")
        matched = [s for s in ai if "coderabbit" in s]
        self.assertTrue(matched, "coderabbit in author_name must be detected")

    def test_ai_author_devin_bot(self):
        ai, _ = cli.detect_ai_signals("chore: x", committer_name="devin-bot")
        matched = [s for s in ai if "devin-bot" in s]
        self.assertTrue(matched, "devin-bot in committer_name must be detected")

    def test_ai_author_gemini_bot_hyphen(self):
        ai, _ = cli.detect_ai_signals("chore: x", author_name="gemini-bot")
        matched = [s for s in ai if "gemini-bot" in s]
        self.assertTrue(matched, "gemini-bot in author_name must be detected")

    def test_ai_author_gitlab_duo(self):
        ai, _ = cli.detect_ai_signals("chore: x", author_email="gitlab-duo@example.com")
        matched = [s for s in ai if "gitlab-duo" in s]
        self.assertTrue(matched, "gitlab-duo in author_email must be detected")

    def test_ai_author_duo_bot(self):
        ai, _ = cli.detect_ai_signals("chore: x", committer_name="duo[bot]")
        matched = [s for s in ai if "duo[bot]" in s]
        self.assertTrue(matched, "duo[bot] in committer_name must be detected")

    # ------------------------------------------------------------------
    # Bot pattern exact-string mutations (mutants 56-61)
    # ------------------------------------------------------------------

    def test_bot_snyk(self):
        _, bot = cli.detect_ai_signals("chore: x", author_name="snyk-bot")
        matched = [s for s in bot if "snyk-bot" in s]
        self.assertTrue(matched, "snyk-bot in author_name must be detected")

    def test_bot_deepsource(self):
        _, bot = cli.detect_ai_signals("chore: x", committer_name="deepsource[bot]")
        matched = [s for s in bot if "deepsource" in s]
        self.assertTrue(matched, "deepsource in committer_name must be detected")

    def test_bot_gitlab_bot(self):
        _, bot = cli.detect_ai_signals("chore: x", author_name="gitlab-bot")
        matched = [s for s in bot if "gitlab-bot" in s]
        self.assertTrue(matched, "gitlab-bot in author_name must be detected")

    # ------------------------------------------------------------------
    # Signal label mutations (mutants 62-69)
    # Mutants change field labels like "author_name" to "AUTHOR_NAME".
    # Tests verify the exact label prefix in the signal string.
    # ------------------------------------------------------------------

    def test_signal_label_author_name(self):
        ai, _ = cli.detect_ai_signals("chore: x", author_name="copilot[bot]")
        self.assertTrue(
            any(s.startswith("author_name_bot:") for s in ai),
            f"Expected 'author_name_bot:' prefix, got {ai}",
        )

    def test_signal_label_author_email(self):
        ai, _ = cli.detect_ai_signals("chore: x", author_email="copilot@users.noreply")
        self.assertTrue(
            any(s.startswith("author_email_bot:") for s in ai),
            f"Expected 'author_email_bot:' prefix, got {ai}",
        )

    def test_signal_label_committer_name(self):
        ai, _ = cli.detect_ai_signals("chore: x", committer_name="copilot[bot]")
        self.assertTrue(
            any(s.startswith("committer_name_bot:") for s in ai),
            f"Expected 'committer_name_bot:' prefix, got {ai}",
        )

    def test_signal_label_committer_email(self):
        _, bot = cli.detect_ai_signals(
            "chore: x", committer_email="dependabot@github.com"
        )
        self.assertTrue(
            any(s.startswith("committer_email_bot:") for s in bot),
            f"Expected 'committer_email_bot:' prefix, got {bot}",
        )

    # ------------------------------------------------------------------
    # Empty-string fallback mutation (mutant 74)
    # Mutant changes `name_field or ""` to `name_field or "XXXX"`.
    # When None is passed, the fallback must be empty, not "XXXX".
    # ------------------------------------------------------------------

    def test_none_author_name_no_false_positive(self):
        """Passing None as author_name must not produce any signal."""
        ai, bot = cli.detect_ai_signals(
            "chore: bump", author_name=None, author_email=None
        )
        self.assertEqual(ai, [])
        self.assertEqual(bot, [])

    def test_none_committer_no_false_positive(self):
        """Passing None as committer fields must not produce any signal."""
        ai, bot = cli.detect_ai_signals(
            "chore: bump", committer_name=None, committer_email=None
        )
        self.assertEqual(ai, [])
        self.assertEqual(bot, [])


# ---------------------------------------------------------------------------
# Ledger tests
# ---------------------------------------------------------------------------
