"""
Virtual Deployment Layer — coverage-completeness tests.

These tests target the ~160 uncovered statements across cli.py, mcp_server.py,
_schema.py, _policy.py, _explain.py, _receipt.py, and _sign.py that require
either (a) a real git repo, (b) CLI subprocess invocation, (c) MCP stdin/stdout
mocking, or (d) crafted defensive inputs.

Design principles:
  - One shared git repo fixture (setUp once) to avoid 100× git-init overhead.
  - StringIO-based MCP server testing (no subprocesses).
  - Pure-function calls for schema/policy/explain branches.
  - Targeted: each test covers a specific uncovered block.

Copyright 2025-2026 Invariant Systems, Inc.
SPDX-License-Identifier: Apache-2.0
"""
from __future__ import annotations

import io
import json
import os
import shutil
import subprocess
import sys
import tempfile
import types
import unittest
from pathlib import Path
from unittest.mock import MagicMock, patch

# ---------------------------------------------------------------------------
# Test-scoped git repo — created once for the whole module
# ---------------------------------------------------------------------------

_REPO_DIR: str = ""
_ORIG_CWD: str = ""


def setUpModule():
    global _REPO_DIR, _ORIG_CWD
    _ORIG_CWD = os.getcwd()
    _REPO_DIR = tempfile.mkdtemp(prefix="aiir_vdeploy_")
    _git(["init"])
    _git(["config", "user.name", "VDeploy Test"])
    _git(["config", "user.email", "vdeploy@test.local"])
    _git(["config", "commit.gpgSign", "false"])
    # Initial commit
    Path(_REPO_DIR, "README.md").write_text("# VDeploy\n")
    _git(["add", "."])
    _git(["commit", "-m", "initial commit"])
    # AI-authored commit
    Path(_REPO_DIR, "ai_file.py").write_text("# Generated by GitHub Copilot\n")
    _git(["add", "."])
    _git(["commit", "-m", "feat: add module\n\nGenerated by GitHub Copilot"])
    # Remote for provenance
    _git(["remote", "add", "origin", "https://github.com/test/repo.git"])


def tearDownModule():
    os.chdir(_ORIG_CWD)
    if _REPO_DIR:
        shutil.rmtree(_REPO_DIR, ignore_errors=True)


def _git(args):
    subprocess.run(
        ["git"] + args, cwd=_REPO_DIR,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE, check=True,
    )


def _chdir_repo():
    """Helper: chdir into _REPO_DIR and return the previous directory."""
    prev = os.getcwd()
    os.chdir(_REPO_DIR)
    return prev


def _base_receipt():
    """Module-level minimal valid receipt for Wave 2 tests."""
    from aiir import __version__
    return {
        "type": "aiir.commit_receipt",
        "schema": "aiir/commit_receipt.v1",
        "version": __version__,
        "receipt_id": "g1-" + "a" * 32,
        "content_hash": "sha256:" + "b" * 64,
        "timestamp": "2026-03-09T00:00:00Z",
        "commit": {
            "sha": "a" * 40,
            "subject": "test",
            "message_hash": "sha256:" + "c" * 64,
            "diff_hash": "sha256:" + "d" * 64,
            "files_changed": 1,
            "author": {"name": "T", "email": "t@t", "date": "2026-03-09T00:00:00Z"},
            "committer": {"name": "T", "email": "t@t", "date": "2026-03-09T00:00:00Z"},
            "files": ["README.md"],
        },
        "ai_attestation": {
            "is_ai_authored": False,
            "signals_detected": [],
            "signal_count": 0,
            "detection_method": "heuristic/v3",
        },
        "provenance": {
            "repository": "https://github.com/test/repo",
            "tool": f"https://github.com/invariant-systems-ai/aiir@{__version__}",
            "generator": f"aiir-cli/{__version__}",
        },
        "extensions": {},
    }


# ═══════════════════════════════════════════════════════════════════════════
# A. CLI main() integration — covers cli.py uncovered blocks
# ═══════════════════════════════════════════════════════════════════════════


class _CLIBase(unittest.TestCase):
    """Base class that chdir's into the test repo for every CLI test."""

    def setUp(self):
        self._prev_cwd = _chdir_repo()
        # Each test gets its own ledger dir inside the repo
        self._ledger_dir = os.path.join(_REPO_DIR, ".aiir_test_" + self.id().rsplit(".", 1)[-1])
        os.makedirs(self._ledger_dir, exist_ok=True)

    def tearDown(self):
        os.chdir(self._prev_cwd)
        if os.path.isdir(self._ledger_dir):
            shutil.rmtree(self._ledger_dir, ignore_errors=True)


class TestCLIPolicyInit(_CLIBase):
    """Cover cli.py lines 466-485: --policy-init mode."""

    def test_policy_init_strict(self):
        from aiir.cli import main as cli_main
        rc = cli_main(["--policy-init", "strict", "--ledger", self._ledger_dir])
        self.assertEqual(rc, 0)
        policy_path = Path(self._ledger_dir, "policy.json")
        self.assertTrue(policy_path.exists())
        policy = json.loads(policy_path.read_text())
        self.assertEqual(policy["enforcement"], "hard-fail")

    def test_policy_init_invalid_preset(self):
        from aiir.cli import main as cli_main
        rc = cli_main(["--policy-init", "nonexistent_preset"])
        self.assertEqual(rc, 1)


class TestCLIVerifyExplain(_CLIBase):
    """Cover cli.py lines 531-538, 537-538, 581, 593-594: --verify with --explain."""

    def test_verify_valid_with_explain(self):
        from aiir import generate_receipt
        from aiir.cli import main as cli_main

        receipt = generate_receipt("HEAD", cwd=_REPO_DIR)
        self.assertIsNotNone(receipt)

        rpath = os.path.join(_REPO_DIR, "test_receipt.json")
        Path(rpath).write_text(json.dumps(receipt))
        try:
            rc = cli_main(["--verify", rpath, "--explain"])
            self.assertEqual(rc, 0)
        finally:
            os.remove(rpath)

    def test_verify_invalid_receipt_with_explain(self):
        from aiir.cli import main as cli_main

        receipt = {"type": "wrong", "schema_version": "wrong"}
        rpath = os.path.join(_REPO_DIR, "bad_receipt.json")
        Path(rpath).write_text(json.dumps(receipt))
        try:
            rc = cli_main(["--verify", rpath, "--explain"])
            self.assertEqual(rc, 1)
        finally:
            os.remove(rpath)


class TestCLIPolicyCheck(_CLIBase):
    """Cover cli.py lines 683-708: --policy evaluation path."""

    def test_policy_check_with_ledger(self):
        from aiir import generate_receipt, append_to_ledger
        from aiir.cli import main as cli_main

        receipt = generate_receipt("HEAD", cwd=_REPO_DIR)
        self.assertIsNotNone(receipt)
        append_to_ledger([receipt], ledger_dir=self._ledger_dir)

        rc = cli_main(["--policy", "permissive", "--ledger", self._ledger_dir])
        self.assertEqual(rc, 0)

    def test_policy_strict_check_with_ai_commits(self):
        from aiir import generate_receipt, append_to_ledger
        from aiir.cli import main as cli_main

        receipt = generate_receipt("HEAD", cwd=_REPO_DIR)
        self.assertIsNotNone(receipt)
        receipt["ai_attestation"]["is_ai_authored"] = True
        append_to_ledger([receipt], ledger_dir=self._ledger_dir)

        rc = cli_main([
            "--policy", "strict",
            "--max-ai-percent", "0",
            "--ledger", self._ledger_dir,
        ])
        # strict + 0% AI threshold should fail
        self.assertEqual(rc, 1)


class TestCLIAgentAttestation(_CLIBase):
    """Cover cli.py lines 783-790: --agent-tool/model/context flags."""

    def test_agent_attestation_flags(self):
        from aiir.cli import main as cli_main

        rc = cli_main([
            "-c", "HEAD",
            "--agent-tool", "copilot",
            "--agent-model", "gpt-4",
            "--agent-context", "test-session",
            "--ledger", self._ledger_dir,
            "-q",
        ])
        self.assertEqual(rc, 0)
        # Verify the ledger has agent attestation
        ledger_file = Path(self._ledger_dir, "receipts.jsonl")
        self.assertTrue(ledger_file.exists())
        receipt = json.loads(ledger_file.read_text().strip().split("\n")[0])
        agent = receipt.get("extensions", {}).get("agent_attestation", {})
        self.assertEqual(agent.get("tool_id"), "copilot")
        self.assertEqual(agent.get("model_class"), "gpt-4")


class TestCLIGitErrorPaths(_CLIBase):
    """Cover cli.py lines 828-829, 859, 870-871, 876: git error handling."""

    def test_empty_repo_no_commits(self):
        from aiir.cli import main as cli_main

        with tempfile.TemporaryDirectory(dir=_REPO_DIR) as tmp:
            subprocess.run(["git", "init", tmp], check=True,
                           stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            subprocess.run(["git", "config", "user.name", "T"], cwd=tmp,
                           check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            subprocess.run(["git", "config", "user.email", "t@t"], cwd=tmp,
                           check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            os.chdir(tmp)
            try:
                rc = cli_main(["-q"])
                self.assertEqual(rc, 1)
            finally:
                os.chdir(_REPO_DIR)

    def test_empty_range_ai_only(self):
        from aiir.cli import main as cli_main

        rc = cli_main([
            "--range", "HEAD~1..HEAD~1",
            "--ai-only",
            "--ledger", self._ledger_dir,
        ])
        self.assertEqual(rc, 0)


class TestCLIOutputModes(_CLIBase):
    """Cover cli.py lines 916-917, 935-950, 958-960: JSONL/JSON stdout modes."""

    def test_jsonl_stdout(self):
        from aiir.cli import main as cli_main
        rc = cli_main([
            "-c", "HEAD",
            "--jsonl", "-q",
            "--ledger", self._ledger_dir,
        ])
        self.assertEqual(rc, 0)

    def test_json_stdout_single(self):
        from aiir.cli import main as cli_main
        rc = cli_main([
            "-c", "HEAD",
            "--json", "-q",
            "--ledger", self._ledger_dir,
        ])
        self.assertEqual(rc, 0)


class TestCLILedgerError(_CLIBase):
    """Cover cli.py lines 975-977: ledger append error."""

    @unittest.skipIf(os.name == "nt", "os.chmod read-only is advisory on Windows")
    def test_ledger_write_to_readonly_dir(self):
        from aiir.cli import main as cli_main

        # Make the ledger dir read-only to force write error.
        # The CLI should handle the PermissionError gracefully.
        os.chmod(self._ledger_dir, 0o555)
        try:
            rc = cli_main([
                "-c", "HEAD",
                "--ledger", self._ledger_dir, "-q",
            ])
            # Should return 1 on permission error
            self.assertEqual(rc, 1)
        except PermissionError:
            pass  # Also acceptable — the error propagated
        finally:
            os.chmod(self._ledger_dir, 0o755)


class TestCLIGitHubActionOverflow(_CLIBase):
    """Cover cli.py lines 1041-1043: receipts_json overflow guard."""

    def test_overflow_guard(self):
        from aiir.cli import main as cli_main

        gh_output = os.path.join(self._ledger_dir, "gh_output")
        Path(gh_output).write_text("")
        gh_summary = os.path.join(self._ledger_dir, "gh_summary")
        Path(gh_summary).write_text("")
        env = {
            "GITHUB_OUTPUT": gh_output,
            "GITHUB_STEP_SUMMARY": gh_summary,
        }
        with patch.dict(os.environ, env):
            rc = cli_main([
                "-c", "HEAD",
                "--github-action",
                "--ledger", self._ledger_dir,
                "-q",
            ])
            self.assertEqual(rc, 0)
            content = Path(gh_output).read_text()
            self.assertIn("receipt_count", content)


class TestCLIMainEntry(_CLIBase):
    """Cover cli.py line 1058: __name__ == '__main__' guard."""

    def test_main_module_invocation(self):
        """Run `python -m aiir --version` as a subprocess."""
        # Must run from the aiir package dir so the module resolves
        aiir_root = Path(__file__).resolve().parent.parent
        result = subprocess.run(
            [sys.executable, "-m", "aiir", "--version"],
            cwd=str(aiir_root),
            stdout=subprocess.PIPE, stderr=subprocess.PIPE,
            text=True, timeout=10,
        )
        self.assertEqual(result.returncode, 0)
        self.assertIn("aiir", result.stdout)


class TestCLIBadgeAndStats(_CLIBase):
    """Cover cli.py badge / stats modes."""

    def test_badge_mode(self):
        from aiir import generate_receipt, append_to_ledger
        from aiir.cli import main as cli_main

        receipt = generate_receipt("HEAD", cwd=_REPO_DIR)
        self.assertIsNotNone(receipt)
        append_to_ledger([receipt], ledger_dir=self._ledger_dir)

        rc = cli_main(["--badge", "--ledger", self._ledger_dir])
        self.assertEqual(rc, 0)

    def test_stats_mode(self):
        from aiir import generate_receipt, append_to_ledger
        from aiir.cli import main as cli_main

        receipt = generate_receipt("HEAD", cwd=_REPO_DIR)
        self.assertIsNotNone(receipt)
        append_to_ledger([receipt], ledger_dir=self._ledger_dir)

        rc = cli_main(["--stats", "--ledger", self._ledger_dir])
        self.assertEqual(rc, 0)


class TestCLIExportMode(_CLIBase):
    """Cover cli.py --export path."""

    def test_export_ledger(self):
        from aiir import generate_receipt, append_to_ledger
        from aiir.cli import main as cli_main

        receipt = generate_receipt("HEAD", cwd=_REPO_DIR)
        self.assertIsNotNone(receipt)
        append_to_ledger([receipt], ledger_dir=self._ledger_dir)

        export_file = "aiir-export-test.json"
        full_path = os.path.join(_REPO_DIR, export_file)
        try:
            rc = cli_main([
                "--export", export_file,
                "--ledger", self._ledger_dir,
            ])
            self.assertEqual(rc, 0)
            self.assertTrue(os.path.isfile(full_path))
        finally:
            if os.path.isfile(full_path):
                os.remove(full_path)


class TestCLICheckMode(_CLIBase):
    """Cover cli.py --check path."""

    def test_check_with_threshold(self):
        from aiir import generate_receipt, append_to_ledger
        from aiir.cli import main as cli_main

        receipt = generate_receipt("HEAD", cwd=_REPO_DIR)
        self.assertIsNotNone(receipt)
        append_to_ledger([receipt], ledger_dir=self._ledger_dir)

        rc = cli_main([
            "--check",
            "--max-ai-percent", "100",
            "--ledger", self._ledger_dir,
        ])
        self.assertEqual(rc, 0)


class TestCLIDetailMode(_CLIBase):
    """Cover cli.py --detail path."""

    def test_detail_output(self):
        from aiir.cli import main as cli_main
        rc = cli_main([
            "-c", "HEAD",
            "--detail",
            "--ledger", self._ledger_dir,
        ])
        self.assertEqual(rc, 0)


class TestCLINamespace(_CLIBase):
    """Cover cli.py --namespace path."""

    def test_namespace_flag(self):
        from aiir.cli import main as cli_main
        rc = cli_main([
            "-c", "HEAD",
            "--namespace", "acme-corp",
            "--ledger", self._ledger_dir,
            "-q",
        ])
        self.assertEqual(rc, 0)
        ledger_file = Path(self._ledger_dir, "receipts.jsonl")
        receipt = json.loads(ledger_file.read_text().strip().split("\n")[0])
        ns = receipt.get("extensions", {}).get("namespace")
        self.assertEqual(ns, "acme-corp")


class TestCLIRedactFiles(_CLIBase):
    """Cover cli.py --redact-files path."""

    def test_redact_files_flag(self):
        from aiir.cli import main as cli_main
        rc = cli_main([
            "-c", "HEAD",
            "--redact-files",
            "--ledger", self._ledger_dir,
            "-q",
        ])
        self.assertEqual(rc, 0)
        ledger_file = Path(self._ledger_dir, "receipts.jsonl")
        receipt = json.loads(ledger_file.read_text().strip().split("\n")[0])
        self.assertTrue(receipt["commit"].get("files_redacted", False))


class TestCLIInToto(_CLIBase):
    """Cover cli.py --in-toto path."""

    def test_in_toto_flag(self):
        from aiir.cli import main as cli_main
        rc = cli_main([
            "-c", "HEAD",
            "--in-toto",
            "--json",
            "-q",
        ])
        self.assertEqual(rc, 0)


class TestCLIOutputDir(_CLIBase):
    """Cover cli.py --output path."""

    def test_output_dir(self):
        from aiir.cli import main as cli_main
        out_dir = os.path.join(_REPO_DIR, ".aiir_output_test")
        try:
            rc = cli_main(["-c", "HEAD", "--output", out_dir, "-q"])
            self.assertEqual(rc, 0)
            self.assertTrue(os.path.isdir(out_dir))
            files = os.listdir(out_dir)
            self.assertTrue(any(f.endswith(".json") for f in files))
        finally:
            shutil.rmtree(out_dir, ignore_errors=True)


# ═══════════════════════════════════════════════════════════════════════════
# B. MCP server — handler testing via direct function calls
# ═══════════════════════════════════════════════════════════════════════════


class _MCPBase(unittest.TestCase):
    """Base class that chdir's into the test repo for MCP handler tests."""

    def setUp(self):
        self._prev_cwd = _chdir_repo()
        self._ledger_dir = os.path.join(_REPO_DIR, ".aiir")
        os.makedirs(self._ledger_dir, exist_ok=True)

    def tearDown(self):
        os.chdir(self._prev_cwd)
        if os.path.isdir(self._ledger_dir):
            shutil.rmtree(self._ledger_dir, ignore_errors=True)


class TestMCPStatsHandler(_MCPBase):
    """Cover mcp_server.py lines 363-375: aiir_stats handler."""

    def test_stats_no_ledger(self):
        """No .aiir/index.json → 'No AIIR ledger'."""
        from aiir.mcp_server import _handle_aiir_stats
        # Remove the index so it looks empty
        index_path = Path(self._ledger_dir, "index.json")
        if index_path.exists():
            index_path.unlink()
        result = _handle_aiir_stats({})
        text = result["content"][0]["text"]
        self.assertIn("No AIIR ledger", text)

    def test_stats_with_ledger(self):
        """With receipts → returns formatted stats."""
        from aiir import generate_receipt, append_to_ledger
        from aiir.mcp_server import _handle_aiir_stats

        receipt = generate_receipt("HEAD", cwd=_REPO_DIR)
        self.assertIsNotNone(receipt)
        append_to_ledger([receipt], ledger_dir=self._ledger_dir)

        result = _handle_aiir_stats({})
        text = result["content"][0]["text"]
        self.assertIn("AIIR", text)


class TestMCPExplainHandler(_MCPBase):
    """Cover mcp_server.py lines 380-392: aiir_explain handler."""

    def test_explain_missing_file_param(self):
        from aiir.mcp_server import _handle_aiir_explain
        result = _handle_aiir_explain({})
        self.assertTrue(result.get("isError", False))

    def test_explain_with_valid_receipt(self):
        from aiir import generate_receipt
        from aiir.mcp_server import _handle_aiir_explain

        receipt = generate_receipt("HEAD", cwd=_REPO_DIR)
        self.assertIsNotNone(receipt)

        rpath = os.path.join(_REPO_DIR, "explain_receipt.json")
        Path(rpath).write_text(json.dumps(receipt))
        try:
            result = _handle_aiir_explain({"file": "explain_receipt.json"})
            self.assertIn("content", result)
            self.assertFalse(result.get("isError", False))
        finally:
            os.remove(rpath)


class TestMCPPolicyCheckHandler(_MCPBase):
    """Cover mcp_server.py lines 397-415: aiir_policy_check handler."""

    def test_policy_check_no_ledger(self):
        from aiir.mcp_server import _handle_aiir_policy_check
        # Remove the index so it looks empty
        index_path = Path(self._ledger_dir, "index.json")
        if index_path.exists():
            index_path.unlink()
        result = _handle_aiir_policy_check({"max_ai_percent": 50})
        text = result["content"][0]["text"]
        self.assertIn("No AIIR ledger", text)

    def test_policy_check_invalid_percent_type(self):
        from aiir.mcp_server import _handle_aiir_policy_check
        # Non-numeric string — should fall back to 50.0
        result = _handle_aiir_policy_check({"max_ai_percent": "not-a-number"})
        self.assertIn("content", result)

    def test_policy_check_with_receipts(self):
        from aiir import generate_receipt, append_to_ledger
        from aiir.mcp_server import _handle_aiir_policy_check

        receipt = generate_receipt("HEAD", cwd=_REPO_DIR)
        self.assertIsNotNone(receipt)
        append_to_ledger([receipt], ledger_dir=self._ledger_dir)

        result = _handle_aiir_policy_check({"max_ai_percent": 100})
        text = result["content"][0]["text"]
        self.assertTrue("✅" in text or "❌" in text)


class TestMCPReceiptHandler(_MCPBase):
    """Cover mcp_server.py lines 306, 318, 321, 327-328: receipt generation."""

    def test_receipt_range_spec(self):
        from aiir.mcp_server import _handle_aiir_receipt
        result = _handle_aiir_receipt({
            "range": "HEAD~1..HEAD",
            "pretty": True,
        })
        self.assertIn("content", result)

    def test_receipt_no_commits_ai_only(self):
        from aiir.mcp_server import _handle_aiir_receipt
        with patch("aiir.mcp_server.generate_receipt", return_value=None):
            result = _handle_aiir_receipt({"ai_only": True})
            text = result["content"][0]["text"]
            self.assertIn("No commits matched", text)

    def test_receipt_exception_handling(self):
        from aiir.mcp_server import _handle_aiir_receipt
        with patch("aiir.mcp_server.generate_receipt", side_effect=RuntimeError("boom")):
            result = _handle_aiir_receipt({})
            self.assertTrue(result.get("isError", False))


class TestMCPVerifyHandler(_MCPBase):
    """Cover mcp_server.py lines 345-358: aiir_verify handler."""

    def test_verify_missing_file(self):
        from aiir.mcp_server import _handle_aiir_verify
        result = _handle_aiir_verify({})
        self.assertTrue(result.get("isError", False))

    def test_verify_path_outside_cwd(self):
        from aiir.mcp_server import _handle_aiir_verify
        result = _handle_aiir_verify({"file": "/etc/passwd"})
        self.assertTrue(result.get("isError", False))

    def test_verify_valid_receipt(self):
        from aiir import generate_receipt
        from aiir.mcp_server import _handle_aiir_verify

        receipt = generate_receipt("HEAD", cwd=_REPO_DIR)
        self.assertIsNotNone(receipt)

        rpath = os.path.join(_REPO_DIR, "verify_receipt.json")
        Path(rpath).write_text(json.dumps(receipt))
        try:
            result = _handle_aiir_verify({"file": "verify_receipt.json"})
            self.assertIn("content", result)
        finally:
            os.remove(rpath)


class TestMCPServeStdio(unittest.TestCase):
    """Cover mcp_server.py lines 519-522, 571, 583-584, 632: serve_stdio paths."""

    def _run_mcp_session(self, requests):
        """Feed JSON-RPC requests through serve_stdio via mocked stdin/stdout."""
        from aiir.mcp_server import serve_stdio

        input_lines = "\n".join(json.dumps(r) for r in requests) + "\n"
        responses = []

        with patch("sys.stdin", io.StringIO(input_lines)):
            capture = io.StringIO()
            with patch("sys.stdout", capture):
                serve_stdio()

            capture.seek(0)
            for line in capture:
                line = line.strip()
                if line:
                    try:
                        responses.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass
        return responses

    def test_notification_no_response(self):
        """Notifications (no id) should not produce responses."""
        msg = {"jsonrpc": "2.0", "method": "notifications/initialized", "params": {}}
        responses = self._run_mcp_session([msg])
        self.assertEqual(len(responses), 0)

    def test_rate_limiter(self):
        """Exceeding rate limit should return error."""
        from aiir.mcp_server import _RATE_LIMIT_MAX
        requests = [
            {"jsonrpc": "2.0", "id": i, "method": "tools/list", "params": {}}
            for i in range(1, _RATE_LIMIT_MAX + 50)
        ]
        responses = self._run_mcp_session(requests)
        errors = [r for r in responses if "error" in r]
        # Either some rate-limited or all went through before reset
        self.assertTrue(
            any("Rate limit" in r.get("error", {}).get("message", "") for r in errors)
            or len(responses) >= _RATE_LIMIT_MAX
        )

    def test_mcp_main_entry(self):
        """Cover mcp_server.py main() entry point (line 632)."""
        from aiir import mcp_server
        with patch.object(mcp_server, "serve_stdio"):
            with patch("sys.argv", ["aiir-mcp-server", "--stdio"]):
                mcp_server.main()

    def test_unknown_method(self):
        """Unknown tool method should return error for unknown tool."""
        msg = {"jsonrpc": "2.0", "id": 1, "method": "tools/call",
               "params": {"name": "nonexistent_tool_xyz"}}
        responses = self._run_mcp_session([msg])
        self.assertTrue(len(responses) >= 1)
        r = responses[0]
        # May be top-level error or result with isError flag
        has_error = (
            "error" in r
            or r.get("result", {}).get("isError", False)
        )
        self.assertTrue(has_error)

    def test_initialize_handshake(self):
        """Cover initialize → initialized flow."""
        requests = [
            {"jsonrpc": "2.0", "id": 1, "method": "initialize",
             "params": {"protocolVersion": "2025-03-26",
                        "capabilities": {}, "clientInfo": {"name": "test"}}},
            {"jsonrpc": "2.0", "method": "notifications/initialized"},
            {"jsonrpc": "2.0", "id": 2, "method": "tools/list", "params": {}},
        ]
        responses = self._run_mcp_session(requests)
        # Should get responses for initialize and tools/list (not for notification)
        ids = [r.get("id") for r in responses]
        self.assertIn(1, ids)
        self.assertIn(2, ids)


# ═══════════════════════════════════════════════════════════════════════════
# C. Schema defensive branches — _schema.py uncovered validators
# ═══════════════════════════════════════════════════════════════════════════


class TestSchemaDefensiveBranches(unittest.TestCase):
    """Cover _schema.py lines 169-276: defensive type checks in validators."""

    def _base_receipt(self):
        """Minimal valid receipt structure matching _schema.py expectations."""
        from aiir import __version__
        return {
            "type": "aiir.commit_receipt",
            "schema": "aiir/commit_receipt.v1",
            "version": __version__,
            "receipt_id": "g1-" + "a" * 32,
            "content_hash": "sha256:" + "b" * 64,
            "timestamp": "2026-03-09T00:00:00Z",
            "commit": {
                "sha": "a" * 40,
                "subject": "test",
                "message_hash": "sha256:" + "c" * 64,
                "diff_hash": "sha256:" + "d" * 64,
                "files_changed": 1,
                "author": {"name": "T", "email": "t@t", "date": "2026-03-09T00:00:00Z"},
                "committer": {"name": "T", "email": "t@t", "date": "2026-03-09T00:00:00Z"},
                "files": ["README.md"],
            },
            "ai_attestation": {
                "is_ai_authored": False,
                "signals_detected": [],
                "signal_count": 0,
                "detection_method": "heuristic/v3",
            },
            "provenance": {
                "repository": "https://github.com/test/repo",
                "tool": f"https://github.com/invariant-systems-ai/aiir@{__version__}",
                "generator": f"aiir-cli/{__version__}",
            },
            "extensions": {},
        }

    def test_commit_missing_files_and_redacted(self):
        from aiir._schema import validate_receipt_schema
        r = self._base_receipt()
        del r["commit"]["files"]
        errors = validate_receipt_schema(r)
        self.assertTrue(any("must have either" in e for e in errors))

    def test_commit_files_not_list(self):
        from aiir._schema import validate_receipt_schema
        r = self._base_receipt()
        r["commit"]["files"] = "not-a-list"
        errors = validate_receipt_schema(r)
        self.assertTrue(any("must be an array" in e for e in errors))

    def test_commit_file_entry_not_string(self):
        from aiir._schema import validate_receipt_schema
        r = self._base_receipt()
        r["commit"]["files"] = [123, "ok"]
        errors = validate_receipt_schema(r)
        self.assertTrue(any("must be a string" in e for e in errors))

    def test_files_redacted_not_true(self):
        from aiir._schema import validate_receipt_schema
        r = self._base_receipt()
        del r["commit"]["files"]
        r["commit"]["files_redacted"] = "yes"
        errors = validate_receipt_schema(r)
        self.assertTrue(any("files_redacted must be true" in e for e in errors))

    def test_signal_count_mismatch(self):
        from aiir._schema import validate_receipt_schema
        r = self._base_receipt()
        r["ai_attestation"]["signals_detected"] = ["copilot"]
        r["ai_attestation"]["signal_count"] = 5
        errors = validate_receipt_schema(r)
        self.assertTrue(any("signal_count" in e for e in errors))

    def test_signal_entry_not_string(self):
        from aiir._schema import validate_receipt_schema
        r = self._base_receipt()
        r["ai_attestation"]["signals_detected"] = [123]
        r["ai_attestation"]["signal_count"] = 1
        errors = validate_receipt_schema(r)
        self.assertTrue(any("must be a string" in e for e in errors))

    def test_is_bot_authored_not_bool(self):
        from aiir._schema import validate_receipt_schema
        r = self._base_receipt()
        r["ai_attestation"]["is_bot_authored"] = "yes"
        errors = validate_receipt_schema(r)
        self.assertTrue(any("must be a boolean" in e for e in errors))

    def test_bot_signals_not_list(self):
        from aiir._schema import validate_receipt_schema
        r = self._base_receipt()
        r["ai_attestation"]["bot_signals_detected"] = "not-a-list"
        errors = validate_receipt_schema(r)
        self.assertTrue(any("must be an array" in e for e in errors))

    def test_bot_signal_count_mismatch(self):
        from aiir._schema import validate_receipt_schema
        r = self._base_receipt()
        r["ai_attestation"]["bot_signals_detected"] = ["renovate"]
        r["ai_attestation"]["bot_signal_count"] = 99
        errors = validate_receipt_schema(r)
        self.assertTrue(any("bot_signal_count" in e for e in errors))

    def test_provenance_repository_not_string(self):
        from aiir._schema import validate_receipt_schema
        r = self._base_receipt()
        r["provenance"]["repository"] = 42
        errors = validate_receipt_schema(r)
        self.assertTrue(any("repository" in e.lower() for e in errors))

    def test_files_capped_not_true(self):
        from aiir._schema import validate_receipt_schema
        r = self._base_receipt()
        r["commit"]["files_capped"] = "not-true"
        errors = validate_receipt_schema(r)
        self.assertTrue(any("files_capped" in e for e in errors))

    def test_identity_wrong_types(self):
        from aiir._schema import validate_receipt_schema
        r = self._base_receipt()
        r["commit"]["author"]["name"] = 42
        errors = validate_receipt_schema(r)
        self.assertTrue(any("name" in e for e in errors))

    def test_bool_int_confusion(self):
        """int where bool expected — Python's bool/int subclass trap."""
        from aiir._schema import validate_receipt_schema
        r = self._base_receipt()
        r["ai_attestation"]["is_ai_authored"] = 1  # int, not bool
        errors = validate_receipt_schema(r)
        self.assertTrue(any("bool" in e for e in errors))


# ═══════════════════════════════════════════════════════════════════════════
# D. Policy defensive branches — _policy.py uncovered lines
# ═══════════════════════════════════════════════════════════════════════════


class TestPolicyDefensiveBranches(unittest.TestCase):
    """Cover _policy.py uncovered defensive paths."""

    def setUp(self):
        self._prev_cwd = _chdir_repo()

    def tearDown(self):
        os.chdir(self._prev_cwd)

    def test_load_policy_with_preset_overlay(self):
        from aiir._policy import load_policy

        policy_dir = os.path.join(_REPO_DIR, ".aiir_policy_test")
        os.makedirs(policy_dir, exist_ok=True)
        try:
            policy = {"preset": "strict", "max_ai_percent": 30}
            Path(policy_dir, "policy.json").write_text(json.dumps(policy))
            loaded = load_policy(ledger_dir=policy_dir)
            self.assertEqual(loaded["enforcement"], "hard-fail")
            self.assertEqual(loaded["max_ai_percent"], 30)
        finally:
            shutil.rmtree(policy_dir, ignore_errors=True)

    def test_evaluate_receipt_soft_fail(self):
        from aiir._policy import evaluate_receipt_policy
        receipt = {
            "ai_attestation": {"is_ai_authored": True},
            "provenance": {"repository": None},
        }
        policy = {
            "enforcement": "soft-fail",
            "require_signing": True,
            "require_provenance_repo": True,
            "require_schema_valid": False,
            "allowed_authorship_classes": [],
        }
        violations = evaluate_receipt_policy(
            receipt, policy, is_signed=False, schema_errors=None,
        )
        self.assertIsInstance(violations, list)

    def test_evaluate_receipt_not_dict(self):
        from aiir._policy import evaluate_receipt_policy
        violations = evaluate_receipt_policy("not-a-dict", {}, is_signed=False)
        self.assertIsInstance(violations, list)

    def test_max_ai_percent_not_float(self):
        from aiir._policy import evaluate_ledger_policy
        policy = {"max_ai_percent": "not-a-number", "enforcement": "warn"}
        passed, msg, violations = evaluate_ledger_policy({}, policy)
        self.assertIsInstance(passed, bool)


# ═══════════════════════════════════════════════════════════════════════════
# E. Explain fallback — _explain.py uncovered generic branch
# ═══════════════════════════════════════════════════════════════════════════


class TestExplainFallback(unittest.TestCase):
    """Cover _explain.py lines 162-163: generic fallback for unknown errors."""

    def test_explain_generic_error(self):
        from aiir._explain import explain_verification
        result = {
            "verified": False,
            "errors": ["some unusual error not matching known patterns"],
            "schema_errors": [],
        }
        text = explain_verification(result)
        self.assertIn("some unusual error", text)


# ═══════════════════════════════════════════════════════════════════════════
# F. Sign boundary mocks — _sign.py uncovered paths
# ═══════════════════════════════════════════════════════════════════════════


class TestSignBoundaryMocks(unittest.TestCase):
    """Cover _sign.py symlink, bundle-not-found, and oversized-file paths."""

    def test_sign_receipt_file_symlink_rejected(self):
        from aiir._sign import sign_receipt_file
        with tempfile.TemporaryDirectory() as tmp:
            real = os.path.join(tmp, "real.json")
            Path(real).write_text("{}")
            link = os.path.join(tmp, "link.json")
            os.symlink(real, link)
            with self.assertRaises(ValueError):
                sign_receipt_file(link)

    def test_verify_signature_no_bundle(self):
        from aiir._sign import verify_receipt_signature
        with tempfile.TemporaryDirectory() as tmp:
            rpath = os.path.join(tmp, "receipt.json")
            Path(rpath).write_text("{}")
            result = verify_receipt_signature(rpath)
            self.assertFalse(result.get("valid", True))

    def test_verify_signature_oversized_bundle(self):
        """Bundle > MAX_RECEIPT_FILE_SIZE should be rejected before sigstore import."""
        from aiir._sign import verify_receipt_signature, MAX_RECEIPT_FILE_SIZE
        with tempfile.TemporaryDirectory() as tmp:
            rpath = os.path.join(tmp, "receipt.json")
            Path(rpath).write_text("{}")
            bundle_path = rpath + ".sigstore"
            # Write a file just over the max size
            with open(bundle_path, "w") as f:
                f.write("x" * (MAX_RECEIPT_FILE_SIZE + 1))
            result = verify_receipt_signature(rpath)
            self.assertFalse(result.get("valid", True))
            self.assertIn("too large", result.get("error", ""))

    def test_verify_signature_symlink_receipt(self):
        from aiir._sign import verify_receipt_signature
        with tempfile.TemporaryDirectory() as tmp:
            real = os.path.join(tmp, "real.json")
            Path(real).write_text("{}")
            link = os.path.join(tmp, "link.json")
            os.symlink(real, link)
            result = verify_receipt_signature(link)
            self.assertFalse(result.get("valid", True))

    def test_verify_signature_symlink_bundle(self):
        from aiir._sign import verify_receipt_signature
        with tempfile.TemporaryDirectory() as tmp:
            rpath = os.path.join(tmp, "receipt.json")
            Path(rpath).write_text("{}")
            real_bundle = os.path.join(tmp, "real.sigstore")
            Path(real_bundle).write_text("{}")
            link_bundle = rpath + ".sigstore"
            os.symlink(real_bundle, link_bundle)
            result = verify_receipt_signature(rpath)
            self.assertFalse(result.get("valid", True))

    def test_sign_receipt_file_not_found(self):
        from aiir._sign import sign_receipt_file
        with self.assertRaises(FileNotFoundError):
            sign_receipt_file("/nonexistent/path/to/receipt.json")

    def test_sign_receipt_file_not_json(self):
        from aiir._sign import sign_receipt_file
        with tempfile.TemporaryDirectory() as tmp:
            rpath = os.path.join(tmp, "receipt.json")
            Path(rpath).write_bytes(b"\x80\x81\x82")  # Invalid UTF-8
            with self.assertRaises(ValueError):
                sign_receipt_file(rpath)


# ═══════════════════════════════════════════════════════════════════════════
# G. Core defensive — _core.py fallback branches
# ═══════════════════════════════════════════════════════════════════════════


class TestCoreDefensiveBranches(unittest.TestCase):
    """Cover _core.py lines 118-121, 126-129: emoji/boxdraw unknown names."""

    def test_emoji_unknown_name(self):
        from aiir._core import _e
        result = _e("nonexistent_emoji_name_xyz")
        self.assertEqual(result, "")

    def test_boxdraw_unknown_name(self):
        from aiir._core import _b
        result = _b("nonexistent_box_name_xyz")
        self.assertEqual(result, "")


class TestCoreDiffHashTimeout(unittest.TestCase):
    """Cover _core.py lines 1108, 1122: diff hash edge cases."""

    def test_diff_hash_works_on_valid_repo(self):
        from aiir._core import _hash_diff_streaming
        head = subprocess.run(
            ["git", "rev-parse", "HEAD"], cwd=_REPO_DIR,
            stdout=subprocess.PIPE, text=True, check=True,
        ).stdout.strip()
        parent = subprocess.run(
            ["git", "rev-parse", "HEAD~1"], cwd=_REPO_DIR,
            stdout=subprocess.PIPE, text=True, check=True,
        ).stdout.strip()
        result = _hash_diff_streaming(parent, head, cwd=_REPO_DIR)
        self.assertTrue(result.startswith("sha256:"))


# ═══════════════════════════════════════════════════════════════════════════
# H. Receipt formatting — _receipt.py uncovered display paths
# ═══════════════════════════════════════════════════════════════════════════


class TestReceiptFormattingPaths(unittest.TestCase):
    """Cover _receipt.py uncovered display paths."""

    def _receipt_with_bot(self):
        from aiir import __version__
        return {
            "type": "aiir/commit_receipt.v1",
            "schema_version": "aiir/commit_receipt.v1",
            "version": __version__,
            "receipt_id": "sha256:" + "a" * 64,
            "content_hash": "sha256:" + "b" * 64,
            "timestamp": "2026-03-09T00:00:00Z",
            "commit": {
                "sha": "a" * 40,
                "subject": "chore: deps update",
                "message_hash": "sha256:" + "c" * 64,
                "diff_hash": "sha256:" + "d" * 64,
                "author": {"name": "dependabot[bot]", "email": "dependabot@github.com",
                           "date": "2026-03-09T00:00:00Z"},
                "committer": {"name": "dependabot[bot]", "email": "dependabot@github.com",
                              "date": "2026-03-09T00:00:00Z"},
                "files": ["package.json"],
            },
            "ai_attestation": {
                "is_ai_authored": False,
                "is_bot_authored": True,
                "signals_detected": [],
                "signal_count": 0,
                "bot_signals_detected": ["author:dependabot[bot]"],
                "bot_signal_count": 1,
                "detection_method": "heuristic/v3",
                "authorship_class": "bot",
            },
            "provenance": {
                "repository": "https://github.com/test/repo",
                "tool": f"https://github.com/invariant-systems-ai/aiir@{__version__}",
                "generator": f"aiir-cli/{__version__}",
            },
        }

    def test_format_detail_with_bot_signals(self):
        from aiir._receipt import format_receipt_detail
        text = format_receipt_detail(self._receipt_with_bot())
        self.assertIn("dependabot", text)

    def test_format_detail_with_extensions(self):
        from aiir._receipt import format_receipt_detail
        receipt = self._receipt_with_bot()
        receipt["extensions"] = {
            "agent_attestation": {"tool_id": "copilot", "model_class": "gpt-4"},
        }
        text = format_receipt_detail(receipt)
        self.assertIn("copilot", text)


# ═══════════════════════════════════════════════════════════════════════════
# WAVE 2 — targeted tests for remaining uncovered lines (~73 stmts)
# ═══════════════════════════════════════════════════════════════════════════


# ---------------------------------------------------------------------------
# W2-A: _receipt.py uncovered lines
# ---------------------------------------------------------------------------

class TestReceiptSanitizeAgentAttestation(unittest.TestCase):
    """Cover _receipt.py line 62: non-dict attestation returns {}."""

    def test_non_dict_returns_empty(self):
        from aiir._receipt import _sanitize_agent_attestation
        self.assertEqual(_sanitize_agent_attestation("not a dict"), {})
        self.assertEqual(_sanitize_agent_attestation(42), {})
        self.assertEqual(_sanitize_agent_attestation(None), {})
        self.assertEqual(_sanitize_agent_attestation([1, 2, 3]), {})

    def test_dict_passes_through(self):
        from aiir._receipt import _sanitize_agent_attestation
        result = _sanitize_agent_attestation({"tool_id": "copilot"})
        self.assertIsInstance(result, dict)


class TestReceiptFormatDetailMalformed(_CLIBase):
    """Cover _receipt.py lines 388-414: format_receipt_detail with malformed sub-objects."""

    def test_detail_non_dict_commit(self):
        from aiir._receipt import format_receipt_detail
        receipt = _base_receipt()
        receipt["commit"] = "not a dict"
        text = format_receipt_detail(receipt)
        self.assertIsInstance(text, str)

    def test_detail_non_dict_ai_attestation(self):
        from aiir._receipt import format_receipt_detail
        receipt = _base_receipt()
        receipt["ai_attestation"] = "not a dict"
        text = format_receipt_detail(receipt)
        self.assertIsInstance(text, str)

    def test_detail_non_dict_provenance(self):
        from aiir._receipt import format_receipt_detail
        receipt = _base_receipt()
        receipt["provenance"] = 42
        text = format_receipt_detail(receipt)
        self.assertIsInstance(text, str)

    def test_detail_non_dict_extensions(self):
        from aiir._receipt import format_receipt_detail
        receipt = _base_receipt()
        receipt["extensions"] = [1, 2, 3]
        text = format_receipt_detail(receipt)
        self.assertIsInstance(text, str)

    def test_detail_non_list_files(self):
        """Cover line 401: commit.files is not a list."""
        from aiir._receipt import format_receipt_detail
        receipt = _base_receipt()
        receipt["commit"]["files"] = "not-a-list"
        text = format_receipt_detail(receipt)
        self.assertIsInstance(text, str)

    def test_detail_non_list_signals(self):
        """Cover line 406: ai.signals_detected not a list."""
        from aiir._receipt import format_receipt_detail
        receipt = _base_receipt()
        receipt["ai_attestation"]["signals_detected"] = "bad"
        text = format_receipt_detail(receipt)
        self.assertIsInstance(text, str)

    def test_detail_non_list_bot_signals(self):
        """Cover line 409/413-414: ai.bot_signals_detected not a list."""
        from aiir._receipt import format_receipt_detail
        receipt = _base_receipt()
        receipt["ai_attestation"]["bot_signals_detected"] = 999
        text = format_receipt_detail(receipt)
        self.assertIsInstance(text, str)


class TestReceiptSignalCountNonInt(unittest.TestCase):
    """Cover _receipt.py lines 470-471: non-integer signal_count."""

    def test_non_int_signal_count(self):
        from aiir._receipt import format_receipt_detail
        receipt = _base_receipt()
        receipt["ai_attestation"]["signal_count"] = "not-an-int"
        text = format_receipt_detail(receipt)
        self.assertIn("Signal count:", text)

    def test_non_numeric_signal_count(self):
        from aiir._receipt import format_receipt_detail
        receipt = _base_receipt()
        receipt["ai_attestation"]["signal_count"] = [1, 2]
        text = format_receipt_detail(receipt)
        self.assertIn("Signal count: 0", text)


class TestReceiptExtensionsOverflow(unittest.TestCase):
    """Cover _receipt.py lines 501-502: extensions with >10 keys."""

    def test_extensions_overflow(self):
        from aiir._receipt import format_receipt_detail
        receipt = _base_receipt()
        receipt["extensions"] = {f"key{i}": f"val{i}" for i in range(15)}
        text = format_receipt_detail(receipt)
        self.assertIn("and 5 more", text)


class TestReceiptWriteJSONL(unittest.TestCase):
    """Cover _receipt.py lines 564-565: write_receipt with jsonl=True."""

    def test_write_receipt_jsonl_stdout(self):
        from aiir._receipt import write_receipt
        receipt = _base_receipt()
        with patch("sys.stdout", new_callable=io.StringIO) as mock_out:
            result = write_receipt(receipt, output_dir=None, jsonl=True)
        self.assertEqual(result, "stdout:jsonl")
        # Output should be valid JSON on a single line
        line = mock_out.getvalue().strip()
        parsed = json.loads(line)
        self.assertEqual(parsed["type"], "aiir.commit_receipt")


# ---------------------------------------------------------------------------
# W2-B: _schema.py uncovered lines
# ---------------------------------------------------------------------------

class TestSchemaValidationBranches(unittest.TestCase):
    """Cover _schema.py lines 238-239, 244, 276."""

    def test_bot_signals_detected_non_string_element(self):
        """Line 238-239: bot_signals_detected entry is not a string."""
        from aiir._schema import validate_receipt_schema
        receipt = _base_receipt()
        receipt["ai_attestation"]["bot_signals_detected"] = [42]
        receipt["ai_attestation"]["bot_signal_count"] = 1
        errors = validate_receipt_schema(receipt)
        found = any("bot_signals_detected[0] must be a string" in e for e in errors)
        self.assertTrue(found, f"Expected bot_signals_detected type error, got: {errors}")

    def test_bot_signal_count_not_int(self):
        """Line 244: bot_signal_count is not an integer."""
        from aiir._schema import validate_receipt_schema
        receipt = _base_receipt()
        receipt["ai_attestation"]["bot_signal_count"] = "three"
        errors = validate_receipt_schema(receipt)
        found = any("bot_signal_count must be an integer" in e for e in errors)
        self.assertTrue(found, f"Expected bot_signal_count type error, got: {errors}")

    def test_provenance_repository_non_null_non_string(self):
        """Line 276: provenance.repository is not string or null."""
        from aiir._schema import validate_receipt_schema
        receipt = _base_receipt()
        receipt["provenance"]["repository"] = 12345
        errors = validate_receipt_schema(receipt)
        found = any("repository must be a string or null" in e for e in errors)
        self.assertTrue(found, f"Expected repository type error, got: {errors}")


# ---------------------------------------------------------------------------
# W2-C: _sign.py uncovered lines
# ---------------------------------------------------------------------------

class TestSignBoundaries(unittest.TestCase):
    """Cover _sign.py lines 124-125, 154-155, 213-214, 237."""

    def test_stat_oserror_on_sign(self):
        """Lines 124-125: OSError when stat-ing receipt file."""
        from aiir._sign import sign_receipt_file
        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as f:
            f.write(b'{"test": true}')
            path = f.name
        try:
            # Patch exists() and is_symlink() to return their real values,
            # then patch stat() to always raise.  This avoids a fragile
            # call-count that varies across Python versions (3.9 pathlib
            # doesn't route exists()/is_symlink() through Path.stat()).
            real_exists = Path(path).exists()
            real_is_symlink = Path(path).is_symlink()

            with patch.object(Path, "exists", return_value=real_exists), \
                 patch.object(Path, "is_symlink", return_value=real_is_symlink), \
                 patch.object(Path, "stat", side_effect=OSError("disk error")):
                with self.assertRaises(ValueError) as ctx:
                    sign_receipt_file(path)
                self.assertIn("Cannot stat", str(ctx.exception))
        finally:
            os.unlink(path)

    def test_file_exists_race_on_sign(self):
        """Lines 154-155: FileExistsError race condition on os.open."""
        from aiir._sign import sign_receipt_file
        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as f:
            f.write(b'{"test": true}')
            path = f.name
        try:
            # Make it pass initial checks but fail on os.open
            with patch("aiir._sign.os.path.exists", return_value=False), \
                 patch("aiir._sign.sign_receipt", return_value='{"sig":"test"}'), \
                 patch("aiir._sign.os.open", side_effect=FileExistsError("race")):
                with self.assertRaises(FileExistsError):
                    sign_receipt_file(path)
        finally:
            os.unlink(path)

    def test_stat_oserror_on_verify(self):
        """Lines 213-214: OSError when stat-ing receipt/bundle during verify."""
        from aiir._sign import verify_receipt_signature
        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as f:
            f.write(b'{"test": true}')
            path = f.name
        bundle_path = path + ".sigstore"
        Path(bundle_path).write_text('{"bundle": true}')
        try:
            # Patch exists() and is_symlink() with their real return values
            # so they don't route through Path.stat() (whose routing varies
            # between Python 3.9 and 3.12+).  Then patch stat() to always
            # raise, exercising the OSError guard in the file-size check.
            rpath = Path(path)
            bpath = Path(bundle_path)
            r_exists = rpath.exists()
            r_sym = rpath.is_symlink()
            b_exists = bpath.exists()
            b_sym = bpath.is_symlink()

            with patch.object(Path, "exists", side_effect=[r_exists, b_exists]), \
                 patch.object(Path, "is_symlink", side_effect=[r_sym, b_sym]), \
                 patch.object(Path, "stat", side_effect=OSError("disk error")):
                result = verify_receipt_signature(path, bundle_path)
            self.assertFalse(result["valid"])
            self.assertIn("Cannot stat", result["error"])
        finally:
            os.unlink(path)
            os.unlink(bundle_path)

    def test_unsafe_noop_policy_path(self):
        """Line 237: UnsafeNoOp policy when no expected_identity."""
        from aiir._sign import verify_receipt_signature
        # This test just confirms the code path runs when Sigstore is available.
        # Without Sigstore installed, it raises RuntimeError on import.
        with tempfile.NamedTemporaryFile(suffix=".json", delete=False) as f:
            f.write(b'{"test": true}')
            path = f.name
        bundle_path = path + ".sigstore"
        Path(bundle_path).write_text('{"bundle": true}')
        try:
            # Mock the Sigstore imports to exercise UnsafeNoOp path
            mock_bundle_cls = MagicMock()
            mock_verifier_cls = MagicMock()
            mock_unsafe = MagicMock()
            mock_identity = MagicMock()

            mock_modules = {
                "sigstore": MagicMock(),
                "sigstore.models": MagicMock(Bundle=mock_bundle_cls),
                "sigstore.verify": MagicMock(Verifier=mock_verifier_cls),
                "sigstore.verify.policy": MagicMock(
                    Identity=mock_identity, UnsafeNoOp=mock_unsafe
                ),
            }
            with patch.dict("sys.modules", mock_modules):
                result = verify_receipt_signature(path, bundle_path)
            # UnsafeNoOp should have been called (no expected_identity)
            mock_unsafe.assert_called_once()
            self.assertTrue(result.get("valid", False))
        finally:
            os.unlink(path)
            os.unlink(bundle_path)


# ---------------------------------------------------------------------------
# W2-D: cli.py uncovered lines
# ---------------------------------------------------------------------------

class TestCLIVerifySignature(_CLIBase):
    """Cover cli.py lines 531-532: --verify with --signature."""

    def test_verify_with_signature_pass(self):
        from aiir.cli import main as cli_main
        from aiir._receipt import write_receipt
        from aiir._receipt import generate_receipt
        receipt = generate_receipt("HEAD")
        path = write_receipt(receipt, output_dir=self._ledger_dir)

        # Create a fake sigstore bundle
        bundle_path = path + ".sigstore"
        Path(bundle_path).write_text('{"bundle": true}')

        with patch("aiir.cli.verify_receipt_signature") as mock_verify:
            mock_verify.return_value = {"valid": True, "signer": "test@test.com"}
            rc = cli_main(["--verify", path, "--verify-signature"])
        self.assertEqual(rc, 0)

    def test_verify_with_signature_fail(self):
        from aiir.cli import main as cli_main
        from aiir._receipt import write_receipt
        from aiir._receipt import generate_receipt
        receipt = generate_receipt("HEAD")
        path = write_receipt(receipt, output_dir=self._ledger_dir)

        bundle_path = path + ".sigstore"
        Path(bundle_path).write_text('{"bundle": true}')

        with patch("aiir.cli.verify_receipt_signature") as mock_verify:
            mock_verify.return_value = {"valid": False, "error": "bad signature"}
            rc = cli_main(["--verify", path, "--verify-signature"])
        self.assertEqual(rc, 1)


class TestCLIVerifyFail(_CLIBase):
    """Cover cli.py line 581: verify returns invalid result."""

    def test_verify_content_hash_mismatch(self):
        from aiir.cli import main as cli_main
        from aiir._receipt import write_receipt
        from aiir._receipt import generate_receipt
        receipt = generate_receipt("HEAD")
        path = write_receipt(receipt, output_dir=self._ledger_dir)
        # Corrupt the receipt to trigger verification failure
        data = json.loads(Path(path).read_text())
        data["content_hash"] = "sha256:" + "0" * 64
        Path(path).write_text(json.dumps(data))
        rc = cli_main(["--verify", path])
        self.assertEqual(rc, 1)


class TestCLIPolicyInitError(_CLIBase):
    """Cover cli.py lines 688-690: policy init ValueError."""

    def test_policy_check_with_load_error(self):
        from aiir.cli import main as cli_main
        # Create a corrupt policy file
        policy_path = Path(self._ledger_dir, "policy.json")
        policy_path.write_text("not json at all")
        rc = cli_main(["--policy", "custom", "--ledger", self._ledger_dir])
        self.assertEqual(rc, 1)


class TestCLIOSError(_CLIBase):
    """Cover cli.py lines 828-829: OSError during receipt generation."""

    def test_oserror_caught(self):
        from aiir.cli import main as cli_main
        with patch("aiir.cli.generate_receipt", side_effect=OSError("disk full")):
            rc = cli_main(["--ledger", self._ledger_dir])
        self.assertEqual(rc, 1)


class TestCLIEmptyResults(_CLIBase):
    """Cover cli.py lines 859, 870-871: empty results with hints."""

    def test_empty_with_ai_only(self):
        from aiir.cli import main as cli_main
        rc = cli_main(["--ai-only", "--range", "HEAD~1..HEAD~1", "--ledger", self._ledger_dir])
        self.assertEqual(rc, 0)

    def test_empty_with_range(self):
        from aiir.cli import main as cli_main
        # Use an empty range
        rc = cli_main(["--range", "HEAD..HEAD", "--ledger", self._ledger_dir])
        self.assertEqual(rc, 0)


class TestCLIJSONLOutput(_CLIBase):
    """Cover cli.py lines 935-950: --jsonl output mode."""

    def test_jsonl_output(self):
        from aiir.cli import main as cli_main
        with patch("sys.stdout", new_callable=io.StringIO) as mock_out:
            rc = cli_main(["--jsonl", "--ledger", self._ledger_dir])
        self.assertEqual(rc, 0)
        lines = [l for l in mock_out.getvalue().strip().split("\n") if l.strip()]
        for line in lines:
            parsed = json.loads(line)
            self.assertIn("type", parsed)

    def test_jsonl_write_error(self):
        """Cover lines 958-960: write_receipt raises ValueError in jsonl mode."""
        from aiir.cli import main as cli_main
        with patch("aiir.cli.write_receipt", side_effect=ValueError("write failed")):
            rc = cli_main(["--jsonl", "--ledger", self._ledger_dir])
        self.assertEqual(rc, 1)


class TestCLILedgerAppendError(_CLIBase):
    """Cover cli.py lines 976-977: ledger append failure."""

    def test_ledger_append_value_error(self):
        from aiir.cli import main as cli_main
        with patch("aiir.cli.append_to_ledger", side_effect=ValueError("ledger corrupt")):
            rc = cli_main(["--ledger", self._ledger_dir])
        self.assertEqual(rc, 1)


class TestCLISummaryWithSigned(_CLIBase):
    """Cover cli.py line 993: summary includes signed count."""

    def test_summary_shows_signed(self):
        from aiir.cli import main as cli_main
        from aiir._sign import sign_receipt_file

        # Mock --sign + --output to exercise signed_count path
        with patch("aiir.cli._sigstore_available", return_value=True), \
             patch("aiir.cli.sign_receipt_file", return_value="/tmp/fake.sigstore"):
            rc = cli_main(["--sign", "--output", self._ledger_dir, "--ledger", self._ledger_dir])
        self.assertEqual(rc, 0)


class TestCLIGitHubActionOverflow(_CLIBase):
    """Cover cli.py lines 1041-1043: GH Action overflow >1MB."""

    def test_overflow(self):
        from aiir.cli import main as cli_main
        # Generate many receipts to exceed 1MB
        huge_receipt = _base_receipt()
        huge_receipt["extensions"] = {f"k{i}": "x" * 10000 for i in range(200)}

        with patch("aiir.cli.generate_receipts_for_range", return_value=[huge_receipt] * 5), \
             patch("aiir.cli.append_to_ledger", return_value=(1, 0, "/tmp/ledger")), \
             patch("aiir.cli.set_github_output") as mock_output, \
             patch("aiir.cli.set_github_summary"):
            rc = cli_main(["--github-action", "--range", "HEAD~1..HEAD",
                           "--ledger", self._ledger_dir])
        self.assertEqual(rc, 0)
        # Check that OVERFLOW was set
        calls = {c[0][0]: c[0][1] for c in mock_output.call_args_list}
        self.assertEqual(calls.get("receipts_json"), '"OVERFLOW"')
        self.assertEqual(calls.get("receipts_overflow"), "true")


class TestCLIStdoutWriteError(_CLIBase):
    """Cover cli.py lines 958-960: stdout write error for --json mode."""

    def test_json_single_receipt_stdout(self):
        """Cover the single-receipt stdout JSON path."""
        from aiir.cli import main as cli_main
        with patch("sys.stdout", new_callable=io.StringIO) as mock_out:
            rc = cli_main(["--json", "--ledger", self._ledger_dir])
        self.assertEqual(rc, 0)
        parsed = json.loads(mock_out.getvalue())
        self.assertIn("type", parsed)


# ---------------------------------------------------------------------------
# W2-E: mcp_server.py uncovered lines
# ---------------------------------------------------------------------------

class TestMCPSymlinkVerifyPath(unittest.TestCase):
    """Cover mcp_server.py line 113: symlink in intermediate path."""

    def test_intermediate_symlink_rejected(self):
        from aiir.mcp_server import _safe_verify_path
        with tempfile.TemporaryDirectory() as tmpdir:
            prev = os.getcwd()
            os.chdir(tmpdir)
            try:
                real_dir = os.path.join(tmpdir, "real")
                os.makedirs(real_dir)
                Path(real_dir, "receipt.json").write_text("{}")
                link_dir = os.path.join(tmpdir, "linked")
                os.symlink(real_dir, link_dir)
                with self.assertRaises(ValueError) as ctx:
                    _safe_verify_path("linked/receipt.json")
                self.assertIn("symlink", str(ctx.exception).lower())
            finally:
                os.chdir(prev)


class TestMCPVerifyHandlerFailure(_MCPBase):
    """Cover mcp_server.py lines 349, 357-358: verify failure/exception."""

    def test_verify_value_error(self):
        from aiir.mcp_server import _handle_aiir_verify
        os.chdir(_REPO_DIR)
        # Path traversal triggers ValueError
        result = _handle_aiir_verify({"file": "../../../etc/passwd"})
        self.assertTrue(result.get("isError", False))

    def test_verify_general_exception(self):
        from aiir.mcp_server import _handle_aiir_verify
        os.chdir(_REPO_DIR)
        with patch("aiir.mcp_server._safe_verify_path", return_value="receipt.json"), \
             patch("aiir.mcp_server.verify_receipt_file", side_effect=RuntimeError("boom")):
            result = _handle_aiir_verify({"file": "receipt.json"})
        self.assertTrue(result.get("isError", False))


class TestMCPStatsException(_MCPBase):
    """Cover mcp_server.py lines 374-375: stats exception."""

    def test_stats_exception(self):
        from aiir.mcp_server import _handle_aiir_stats
        os.chdir(_REPO_DIR)
        with patch("aiir.mcp_server._load_index", side_effect=RuntimeError("corrupt")):
            with patch("aiir.mcp_server.Path") as mock_path:
                mock_path.cwd.return_value.__truediv__ = MagicMock(return_value=Path(_REPO_DIR) / ".aiir")
                # Force the index path to exist so it enters the try block
                mock_index = MagicMock()
                mock_index.is_file.return_value = True
                mock_path.return_value.is_file.return_value = True
                result = _handle_aiir_stats({})
        self.assertTrue(result.get("isError", False))


class TestMCPExplainException(_MCPBase):
    """Cover mcp_server.py lines 389-392: explain ValueError/exception."""

    def test_explain_value_error(self):
        from aiir.mcp_server import _handle_aiir_explain
        os.chdir(_REPO_DIR)
        result = _handle_aiir_explain({"file": "../escape"})
        self.assertTrue(result.get("isError", False))

    def test_explain_general_exception(self):
        from aiir.mcp_server import _handle_aiir_explain
        os.chdir(_REPO_DIR)
        with patch("aiir.mcp_server._safe_verify_path", return_value="r.json"), \
             patch("aiir.mcp_server.verify_receipt_file", side_effect=RuntimeError("fail")):
            result = _handle_aiir_explain({"file": "r.json"})
        self.assertTrue(result.get("isError", False))


class TestMCPPolicyCheckException(_MCPBase):
    """Cover mcp_server.py lines 414-415: policy check exception."""

    def test_policy_check_exception(self):
        from aiir.mcp_server import _handle_aiir_policy_check
        os.chdir(_REPO_DIR)
        with patch("aiir.mcp_server._load_index", side_effect=RuntimeError("corrupt")):
            with patch("aiir.mcp_server._ledger_paths", return_value=("a", "b", "c")), \
                 patch("pathlib.Path.is_file", return_value=True):
                result = _handle_aiir_policy_check({})
        self.assertTrue(result.get("isError", False))


class TestMCPRateLimit(unittest.TestCase):
    """Cover mcp_server.py line 571: rate limit exceeded."""

    def test_rate_limit_fires(self):
        from aiir.mcp_server import serve_stdio, _RATE_LIMIT_MAX
        # Generate enough requests to trigger rate limiting
        messages = []
        for i in range(_RATE_LIMIT_MAX + 5):
            msg = {"jsonrpc": "2.0", "id": i, "method": "tools/list", "params": {}}
            messages.append(json.dumps(msg))

        stdin_data = "\n".join(messages) + "\n"
        responses = []
        with patch("sys.stdin", io.StringIO(stdin_data)), \
             patch("sys.stdout", new_callable=io.StringIO) as mock_out:
            serve_stdio()
        output = mock_out.getvalue()
        for line in output.strip().split("\n"):
            if line.strip():
                responses.append(json.loads(line))
        # At least one response should be a rate limit error
        rate_errors = [r for r in responses if "error" in r and r["error"].get("code") == -32000]
        self.assertGreater(len(rate_errors), 0, "Expected at least one rate limit error")


class TestMCPNotificationException(unittest.TestCase):
    """Cover mcp_server.py lines 583-584: notification handler exception."""

    def test_notification_handler_exception_swallowed(self):
        from aiir.mcp_server import serve_stdio
        # A notification (no id) with a handler that raises should be silently swallowed
        msg = {"jsonrpc": "2.0", "method": "notifications/initialized", "params": {}}
        stdin_data = json.dumps(msg) + "\n"
        with patch("sys.stdin", io.StringIO(stdin_data)), \
             patch("sys.stdout", new_callable=io.StringIO) as mock_out, \
             patch("aiir.mcp_server.HANDLERS", {
                 "notifications/initialized": MagicMock(side_effect=RuntimeError("boom")),
             }):
            serve_stdio()
        # No response should be produced for notifications
        self.assertEqual(mock_out.getvalue().strip(), "")


# ---------------------------------------------------------------------------
# W2-F: _core.py uncovered lines
# ---------------------------------------------------------------------------

class TestCoreDiffHashNonZero(unittest.TestCase):
    """Cover _core.py line 1108: git diff exits with non-zero code."""

    def test_diff_hash_nonzero_exit(self):
        from aiir._core import _hash_diff_streaming
        with tempfile.TemporaryDirectory() as tmpdir:
            prev = os.getcwd()
            os.chdir(tmpdir)
            try:
                subprocess.run(["git", "init"], cwd=tmpdir, capture_output=True, check=True)
                subprocess.run(["git", "config", "user.name", "test"], cwd=tmpdir, capture_output=True, check=True)
                subprocess.run(["git", "config", "user.email", "t@t.com"], cwd=tmpdir, capture_output=True, check=True)
                Path(tmpdir, "f.txt").write_text("x")
                subprocess.run(["git", "add", "."], cwd=tmpdir, capture_output=True, check=True)
                subprocess.run(["git", "commit", "-m", "init"], cwd=tmpdir, capture_output=True, check=True)
                sha = subprocess.run(["git", "rev-parse", "HEAD"], cwd=tmpdir,
                                     capture_output=True, text=True, check=True).stdout.strip()
                # Use an invalid parent to force non-zero exit from git diff
                with self.assertRaises(RuntimeError) as ctx:
                    _hash_diff_streaming("0" * 40, sha, cwd=tmpdir)
                self.assertIn("git diff", str(ctx.exception))
            finally:
                os.chdir(prev)


class TestCoreURLStrip(unittest.TestCase):
    """Cover _core.py line 1122: URL with query/fragment stripped."""

    def test_strip_query_and_fragment(self):
        from aiir._core import _strip_url_credentials
        result = _strip_url_credentials("https://github.com/repo.git?token=abc#ref")
        self.assertNotIn("token=abc", result)
        self.assertNotIn("#ref", result)
        self.assertIn("github.com", result)

    def test_strip_credentials(self):
        from aiir._core import _strip_url_credentials
        result = _strip_url_credentials("https://user:pass@github.com/repo.git")
        self.assertNotIn("user", result)
        self.assertNotIn("pass", result)
        self.assertIn("github.com", result)


# ---------------------------------------------------------------------------
# W2-G: _policy.py remaining uncovered lines
# ---------------------------------------------------------------------------

class TestPolicyEvaluateBranches(unittest.TestCase):
    """Cover _policy.py lines 192, 206, 279."""

    def test_require_provenance_repo_non_dict(self):
        """Line 192: provenance is not a dict."""
        from aiir._policy import evaluate_receipt_policy
        receipt = _base_receipt()
        receipt["provenance"] = "not a dict"
        policy = {"require_provenance_repo": True, "enforcement": "hard-fail"}
        violations = evaluate_receipt_policy(receipt, policy)
        found = any(v.rule == "require_provenance_repo" for v in violations)
        self.assertTrue(found)

    def test_allowed_authorship_class_violation(self):
        """Line 206: authorship class not in allowed list."""
        from aiir._policy import evaluate_receipt_policy
        receipt = _base_receipt()
        receipt["ai_attestation"]["authorship_class"] = "ai_generated"
        policy = {"allowed_authorship_classes": ["human", "ai_assisted"],
                  "enforcement": "hard-fail"}
        violations = evaluate_receipt_policy(receipt, policy)
        found = any(v.rule == "allowed_authorship_classes" for v in violations)
        self.assertTrue(found)

    def test_soft_fail_enforcement(self):
        """Line 279: soft-fail returns False."""
        from aiir._policy import evaluate_ledger_policy
        # Build an index with high AI percentage
        index = {
            "receipt_count": 10,
            "ai_commit_count": 8,
            "ai_percentage": 80.0,
            "unique_authors": ["test"],
        }
        policy = {"max_ai_percent": 50, "enforcement": "soft-fail"}
        passed, message, violations = evaluate_ledger_policy(index, policy)
        self.assertFalse(passed)
        self.assertIn("SOFT-FAIL", message)


if __name__ == "__main__":
    unittest.main()


# ---------------------------------------------------------------------------
# W2-H: _core.py platform-dependent fallback branches
# ---------------------------------------------------------------------------

class TestCoreEmojiFallback(unittest.TestCase):
    """Cover _core.py lines 121 and 129: ASCII fallback when terminal lacks Unicode."""

    def test_emoji_ascii_fallback(self):
        import aiir._core as core
        orig = core._USE_EMOJI
        try:
            core._USE_EMOJI = False
            result = core._e("ok")
            self.assertIsInstance(result, str)
            self.assertTrue(len(result) > 0)
        finally:
            core._USE_EMOJI = orig

    def test_boxdraw_ascii_fallback(self):
        import aiir._core as core
        orig = core._USE_BOXDRAW
        try:
            core._USE_BOXDRAW = False
            result = core._b("tl")
            self.assertIsInstance(result, str)
            self.assertTrue(len(result) > 0)
        finally:
            core._USE_BOXDRAW = orig
