"""Tests for AI signal detection."""

from __future__ import annotations

import unittest

# Import the module under test
import aiir.cli as cli


class TestDetectAISignals(unittest.TestCase):
    """Tests for detect_ai_signals()."""

    def test_copilot_coauthor(self):
        msg = "feat: add auth\n\nCo-authored-by: Copilot <copilot@github.com>"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(len(signals) > 0)
        self.assertTrue(any("copilot" in s for s in signals))

    def test_chatgpt_generated(self):
        msg = "refactor: update parser\n\nGenerated by ChatGPT"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(any("chatgpt" in s for s in signals))

    def test_claude_code(self):
        msg = "fix: resolve null check\n\nClaude Code assisted this change"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(any("claude code" in s for s in signals))

    def test_aider_prefix(self):
        msg = "aider: refactored the auth module"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(any("aider" in s for s in signals))

    def test_no_signals_human(self):
        msg = "fix: typo in README\n\nSimple fix."
        ai_signals, bot_signals = cli.detect_ai_signals(msg)
        self.assertEqual(len(ai_signals), 0)
        self.assertEqual(len(bot_signals), 0)

    def test_bot_author_name(self):
        _, bot_signals = cli.detect_ai_signals(
            "chore: update deps",
            author_name="dependabot[bot]",
            author_email="dependabot@github.com",
        )
        self.assertTrue(any("dependabot" in s for s in bot_signals))

    def test_bot_committer(self):
        _, bot_signals = cli.detect_ai_signals(
            "update lock",
            committer_name="renovate[bot]",
            committer_email="renovate@example.com",
        )
        self.assertTrue(any("renovate" in s for s in bot_signals))

    def test_trailer_detected(self):
        msg = "feat: add feature\n\nGenerated-by: copilot-v2"
        signals, _ = cli.detect_ai_signals(msg)
        # VULN-07: Should only record trailer key, not the value
        trailer_signals = [s for s in signals if s.startswith("trailer:")]
        for s in trailer_signals:
            self.assertNotIn("copilot-v2", s, "Trailer value should not be leaked")
            self.assertIn("generated-by", s)

    def test_trailer_value_not_leaked(self):
        """VULN-07: Internal tool names in trailers must not appear in signals."""
        msg = "fix: update\n\nTool: proprietary-internal-system-v3.2"
        signals, _ = cli.detect_ai_signals(msg)
        trailer_signals = [s for s in signals if s.startswith("trailer:")]
        self.assertTrue(len(trailer_signals) > 0)
        for s in trailer_signals:
            self.assertNotIn("proprietary", s)

    def test_case_insensitive(self):
        msg = "chore: update\n\nCO-AUTHORED-BY: COPILOT"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(len(signals) > 0)

    def test_multiple_signals(self):
        msg = "AI-generated code\n\nCo-authored-by: Copilot\nGenerated-by: copilot"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(len(signals) >= 2)

    def test_windsurf_signal(self):
        msg = "feat: new component\n\nCreated with Windsurf editor"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(any("windsurf" in s for s in signals))


# ---------------------------------------------------------------------------
# Ref validation tests (VULN-03)
# ---------------------------------------------------------------------------


class TestRedTeamSignalEvasion(unittest.TestCase):
    """Tests for R5-01/02/03 signal evasion fixes."""

    def test_r5_01_combining_mark_evasion_blocked(self):
        """Combining diacritical marks must not evade signal detection."""
        # U+0336 COMBINING LONG STROKE OVERLAY between 'o' and 'p'
        msg = "Co-authored-by: co\u0336pilot"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(
            len(signals) > 0, f"Combining mark evasion not blocked: {msg!r}"
        )

    def test_r5_02_variation_selector_evasion_blocked(self):
        """Variation selectors must not evade signal detection."""
        # U+FE0E VARIATION SELECTOR-15 between 'p' and 'i'
        msg = "Co-authored-by: cop\ufe0eilot"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(
            len(signals) > 0, f"Variation selector evasion not blocked: {msg!r}"
        )

    def test_r5_03_tab_whitespace_evasion_blocked(self):
        """Tab characters in trailers must not evade signal detection."""
        msg = "Co-authored-by:\tcopilot"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(
            len(signals) > 0, f"Tab whitespace evasion not blocked: {msg!r}"
        )

    def test_r5_03_double_space_evasion_blocked(self):
        """Double spaces in trailers must not evade signal detection."""
        msg = "Co-authored-by:  copilot"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(len(signals) > 0, f"Double-space evasion not blocked: {msg!r}")

    def test_r5_01_normal_signals_still_detected(self):
        """Normal signals must still be detected after Mn/Me stripping."""
        msg = "Co-authored-by: copilot"
        signals, _ = cli.detect_ai_signals(msg)
        self.assertTrue(len(signals) > 0)


class TestMissingAISignals(unittest.TestCase):
    """R21-PUB-01: AI detection must cover major AI coding tools."""

    def test_amazon_q_detected(self):
        signals, _ = cli.detect_ai_signals("feat: update\n\nGenerated by Amazon Q")
        self.assertTrue(any("amazon q" in s for s in signals))

    def test_codewhisperer_detected(self):
        signals, _ = cli.detect_ai_signals("fix: types\n\nCodeWhisperer assisted")
        self.assertTrue(any("codewhisperer" in s for s in signals))

    def test_amazon_codewhisperer_detected(self):
        signals, _ = cli.detect_ai_signals(
            "fix: auth\n\nAmazon CodeWhisperer generated this"
        )
        self.assertTrue(any("amazon codewhisperer" in s for s in signals))

    def test_devin_detected(self):
        signals, _ = cli.detect_ai_signals(
            "refactor: improve perf\n\nGenerated by Devin"
        )
        self.assertTrue(any("devin" in s for s in signals))

    def test_gemini_code_assist_detected(self):
        signals, _ = cli.detect_ai_signals(
            "feat: add endpoint\n\nGemini Code Assist wrote this"
        )
        self.assertTrue(any("gemini code assist" in s for s in signals))

    def test_google_gemini_detected(self):
        signals, _ = cli.detect_ai_signals(
            "fix: null check\n\nGoogle Gemini authored this"
        )
        self.assertTrue(any("google gemini" in s for s in signals))

    def test_tabnine_detected(self):
        signals, _ = cli.detect_ai_signals("refactor: cleanup\n\nTabnine AI completion")
        self.assertTrue(any("tabnine" in s for s in signals))

    def test_codegen_by_gemini_detected(self):
        signals, _ = cli.detect_ai_signals("feat: new module\n\nCodegen by Gemini")
        self.assertTrue(any("codegen by gemini" in s for s in signals))


class TestMissingBotPatterns(unittest.TestCase):
    """R21-PUB-02: Bot author detection must include new AI tool bots."""

    def test_devin_bot_author(self):
        signals, _ = cli.detect_ai_signals("chore: update", author_name="devin[bot]")
        self.assertTrue(any("devin" in s for s in signals))

    def test_amazon_q_bot_author(self):
        signals, _ = cli.detect_ai_signals("chore: update", author_name="amazon-q[bot]")
        self.assertTrue(any("amazon-q" in s for s in signals))

    def test_tabnine_bot_committer(self):
        signals, _ = cli.detect_ai_signals(
            "chore: update", committer_name="tabnine-bot"
        )
        self.assertTrue(any("tabnine" in s for s in signals))

    def test_gemini_bot_author(self):
        signals, _ = cli.detect_ai_signals("chore: update", author_name="gemini[bot]")
        self.assertTrue(any("gemini" in s for s in signals))


class TestAISignalCoverage(unittest.TestCase):
    """R21-PUB-01: AI_SIGNALS list must include all major tools."""

    def test_ai_signals_count(self):
        """AI_SIGNALS must have at least 30 patterns (was 20 before R21)."""
        self.assertGreaterEqual(len(cli.AI_SIGNALS), 30)

    def test_major_tools_in_signals(self):
        """All major AI coding tools must be in AI_SIGNALS."""
        required = [
            "amazon q",
            "codewhisperer",
            "co-authored-by: devin",
            "gemini code assist",
            "google gemini",
            "tabnine",
            "github copilot",
            "claude code",
            "windsurf",
            "aider:",
            "codeium",
            "sourcegraph cody",
        ]
        for tool in required:
            self.assertIn(tool, cli.AI_SIGNALS, f"Missing AI signal: {tool}")


# ---------------------------------------------------------------------------
# Ledger tests
# ---------------------------------------------------------------------------
