"""
End-to-end dry-run test — guarantees the documented UX never breaks.

This module creates a realistic multi-commit git repo (human, AI, bot)
and exercises every CLI path documented in README.md:

  1.  aiir                              → ledger default (.aiir/)
  2.  aiir --pretty                     → ledger + human-readable stderr
  3.  aiir --range A..B --pretty        → range mode
  4.  aiir --ai-only                    → filter out non-AI
  5.  aiir --ai-only --output .rcpts/   → filtered + directory output
  6.  aiir --json                       → stdout JSON
  7.  aiir --jsonl                      → stdout JSONL
  8.  aiir --ledger .audit/             → custom ledger path
  9.  aiir --verify receipt.json        → round-trip integrity check
  10. Deduplication                     → re-run is no-op
  11. index.json structure              → all documented fields
  12. Receipt format                    → every field present + typed
  13. Content-addressability            → receipt_id = hash(canonical JSON)
  14. AI detection                      → Copilot / ChatGPT / Claude signals
  15. Bot detection                     → dependabot / github-actions
  16. authorship_class values           → human / ai_assisted / bot
  17. --redact-files                    → files omitted, files_redacted present
  18. --github-action                   → outputs set correctly
  19. --version                         → prints current version
  20. --help                            → includes usage examples
  21. --json piped (single commit)      → valid JSON object
  22. Ledger export (--export)          → portable JSON bundle
  23. Stats / badge / check (ledger)    → post-generation analytics

If any of these documented contracts break, this test fails immediately.

Copyright 2025-2026 Invariant Systems, Inc.
# SPDX-License-Identifier: Apache-2.0
"""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
import unittest
from io import StringIO
from pathlib import Path
from unittest.mock import patch

from aiir import __version__
from aiir import cli
from aiir._core import _canonical_json, _sha256


class TestE2EUXContract(unittest.TestCase):
    """Full end-to-end UX contract test against a real git repo.

    Creates 7 diverse commits (human, Copilot, ChatGPT, Claude,
    Dependabot, github-actions, bot+AI) and validates every documented CLI path.
    """

    # ── Fixture ─────────────────────────────────────────────────────────

    @classmethod
    def setUpClass(cls) -> None:
        """Create a temp git repo with 6 diverse commits."""
        cls._tmpdir = tempfile.mkdtemp(prefix="aiir_e2e_")
        cls._old_cwd = os.getcwd()
        os.chdir(cls._tmpdir)

        def _git(*args: str) -> str:
            result = subprocess.run(
                ["git", *args],
                cwd=cls._tmpdir,
                capture_output=True,
                text=True,
                check=True,
            )
            return result.stdout.strip()

        cls._git = staticmethod(_git)

        # Init repo
        _git("init")
        _git("config", "user.name", "Test User")
        _git("config", "user.email", "test@example.com")

        # ── Commit 1: human ────────────────────────────────────────────
        Path(cls._tmpdir, "human.py").write_text("# human code\nprint('hello')\n")
        _git("add", ".")
        _git("commit", "-m", "feat: add human greeting")

        cls.sha_human = _git("rev-parse", "HEAD")

        # ── Commit 2: Copilot (Co-authored-by trailer) ─────────────────
        Path(cls._tmpdir, "copilot.py").write_text("# copilot code\ndef ai(): pass\n")
        _git("add", ".")
        _git(
            "commit",
            "-m",
            "feat: add AI helper\n\nCo-authored-by: Copilot <copilot@github.com>",
        )
        cls.sha_copilot = _git("rev-parse", "HEAD")

        # ── Commit 3: ChatGPT (Generated-by trailer) ──────────────────
        Path(cls._tmpdir, "chatgpt.py").write_text("# chatgpt code\ndef chat(): pass\n")
        _git("add", ".")
        _git(
            "commit",
            "-m",
            "feat: add chat module\n\nGenerated by ChatGPT",
        )
        cls.sha_chatgpt = _git("rev-parse", "HEAD")

        # ── Commit 4: Claude (Generated-by trailer) ───────────────────
        Path(cls._tmpdir, "claude.py").write_text("# claude code\ndef think(): pass\n")
        _git("add", ".")
        _git(
            "commit",
            "-m",
            "feat: add thinking module\n\nGenerated by Claude",
        )
        cls.sha_claude = _git("rev-parse", "HEAD")

        # ── Commit 5: Dependabot (bot author) ─────────────────────────
        _git("config", "user.name", "dependabot[bot]")
        _git("config", "user.email", "dependabot[bot]@users.noreply.github.com")
        Path(cls._tmpdir, "requirements.txt").write_text("requests==2.32.0\n")
        _git("add", ".")
        _git("commit", "-m", "build(deps): bump requests from 2.31.0 to 2.32.0")
        cls.sha_dependabot = _git("rev-parse", "HEAD")

        # ── Commit 6: github-actions (bot author) ─────────────────────
        _git("config", "user.name", "github-actions[bot]")
        _git("config", "user.email", "github-actions[bot]@users.noreply.github.com")
        Path(cls._tmpdir, "version.txt").write_text("1.2.3\n")
        _git("add", ".")
        _git("commit", "-m", "chore: update version to 1.2.3")
        cls.sha_github_actions = _git("rev-parse", "HEAD")

        # ── Commit 7: bot + AI (bot author WITH AI co-authored-by) ────
        _git("config", "user.name", "dependabot[bot]")
        _git("config", "user.email", "dependabot[bot]@users.noreply.github.com")
        Path(cls._tmpdir, "ai_bot.py").write_text("# AI-assisted bot commit\n")
        _git("add", ".")
        _git(
            "commit",
            "-m",
            "build(deps): AI-assisted update\n\nCo-authored-by: Copilot <copilot@github.com>",
        )
        cls.sha_ai_and_bot = _git("rev-parse", "HEAD")

        # Restore author for any further git ops
        _git("config", "user.name", "Test User")
        _git("config", "user.email", "test@example.com")

        # Store first and last SHAs for range tests
        cls.sha_first = cls.sha_human
        cls.sha_last = cls.sha_ai_and_bot

    @classmethod
    def tearDownClass(cls) -> None:
        os.chdir(cls._old_cwd)
        shutil.rmtree(cls._tmpdir, ignore_errors=True)

    def setUp(self) -> None:
        """Ensure cwd is the temp repo before each test."""
        os.chdir(self._tmpdir)
        # Clean up any .aiir/ or .receipts/ from previous tests
        for d in [".aiir", ".receipts", ".audit", ".rcpts"]:
            p = Path(self._tmpdir, d)
            if p.exists():
                shutil.rmtree(p)

    # ── Helpers ─────────────────────────────────────────────────────────

    def _run_cli(self, *args: str) -> tuple[int, str, str]:
        """Run cli.main() and capture (rc, stdout, stderr)."""
        out, err = StringIO(), StringIO()
        with patch("sys.stdout", out), patch("sys.stderr", err):
            rc = cli.main(list(args))
        return rc, out.getvalue(), err.getvalue()

    # ── 1. Default ledger mode ──────────────────────────────────────────

    def test_01_default_creates_ledger(self):
        """'aiir' creates .aiir/receipts.jsonl and .aiir/index.json."""
        rc, stdout, stderr = self._run_cli()
        self.assertEqual(rc, 0, f"Expected rc=0, got {rc}. stderr: {stderr}")
        self.assertTrue(
            Path(".aiir/receipts.jsonl").exists(),
            "Ledger file should exist",
        )
        self.assertTrue(
            Path(".aiir/index.json").exists(),
            "Index file should exist",
        )

    # ── 2. --pretty ─────────────────────────────────────────────────────

    def test_02_pretty_shows_receipt_box(self):
        """'aiir --pretty' shows human-readable receipt on stderr."""
        rc, stdout, stderr = self._run_cli("--pretty")
        self.assertEqual(rc, 0)
        # Pretty output contains receipt structure keywords
        self.assertIn("Receipt:", stderr)
        self.assertIn("Commit:", stderr)
        self.assertIn("Subject:", stderr)
        self.assertIn("Author:", stderr)
        self.assertIn("AI:", stderr)
        self.assertIn("Hash:", stderr)

    # ── 3. --range --pretty ─────────────────────────────────────────────

    def test_03_range_receipts_correct_commits(self):
        """'aiir --range A..B --pretty' receipts only commits in range."""
        # Range from human to chatgpt (exclusive of human, inclusive of chatgpt)
        range_spec = f"{self.sha_human}..{self.sha_chatgpt}"
        rc, stdout, stderr = self._run_cli("--range", range_spec, "--pretty")
        self.assertEqual(rc, 0)
        # Should have 2 receipts: copilot + chatgpt (range excludes start)
        self.assertIn("2 receipt", stderr)

    # ── 4. --ai-only ────────────────────────────────────────────────────

    def test_04_ai_only_filters_human_and_bot(self):
        """'aiir --ai-only --json' excludes human and bot-only commits."""
        range_spec = f"{self.sha_human}..{self.sha_github_actions}"
        rc, stdout, stderr = self._run_cli(
            "--range",
            range_spec,
            "--ai-only",
            "--json",
        )
        self.assertEqual(rc, 0)
        receipts = json.loads(stdout)
        if not isinstance(receipts, list):
            receipts = [receipts]
        # Should have exactly 3: copilot + chatgpt + claude
        self.assertEqual(len(receipts), 3, "Should have 3 AI-only receipts")
        for r in receipts:
            self.assertTrue(
                r["ai_attestation"]["is_ai_authored"],
                "All ai-only receipts must be AI-authored",
            )

    # ── 5. --ai-only --output ───────────────────────────────────────────

    def test_05_ai_only_output_dir(self):
        """'aiir --ai-only --output .rcpts/' writes only AI receipt files."""
        range_spec = f"{self.sha_human}..{self.sha_claude}"
        rc, stdout, stderr = self._run_cli(
            "--range",
            range_spec,
            "--ai-only",
            "--output",
            ".rcpts",
        )
        self.assertEqual(rc, 0)
        receipt_files = list(Path(".rcpts").glob("receipt_*.json"))
        self.assertEqual(len(receipt_files), 3, "Should have 3 AI receipt files")
        # Each file should be valid JSON
        for f in receipt_files:
            data = json.loads(f.read_text(encoding="utf-8"))
            self.assertTrue(data["ai_attestation"]["is_ai_authored"])

    # ── 6. --json ───────────────────────────────────────────────────────

    def test_06_json_stdout(self):
        """'aiir --json' prints valid JSON to stdout."""
        rc, stdout, stderr = self._run_cli("--json")
        self.assertEqual(rc, 0)
        data = json.loads(stdout)
        self.assertIsInstance(data, dict, "Single commit should be JSON object")
        self.assertIn("receipt_id", data)
        self.assertIn("content_hash", data)

    # ── 7. --jsonl ──────────────────────────────────────────────────────

    def test_07_jsonl_stdout(self):
        """'aiir --range X..Y --jsonl' prints one JSON per line."""
        range_spec = f"{self.sha_human}..{self.sha_claude}"
        rc, stdout, stderr = self._run_cli("--range", range_spec, "--jsonl")
        self.assertEqual(rc, 0)
        lines = [l for l in stdout.strip().splitlines() if l.strip()]
        self.assertEqual(len(lines), 3, "Should have 3 JSONL lines")
        for line in lines:
            data = json.loads(line)
            self.assertIn("receipt_id", data)

    # ── 8. --ledger .audit/ ─────────────────────────────────────────────

    def test_08_custom_ledger_path(self):
        """'aiir --ledger .audit/' writes to custom ledger directory."""
        rc, stdout, stderr = self._run_cli("--ledger", ".audit")
        self.assertEqual(rc, 0)
        self.assertTrue(
            Path(".audit/receipts.jsonl").exists(),
            "Custom ledger file should exist",
        )
        self.assertTrue(
            Path(".audit/index.json").exists(),
            "Custom index file should exist",
        )

    # ── 9. --verify round-trip ──────────────────────────────────────────

    def test_09_verify_round_trip(self):
        """Generate → write → verify round-trip passes."""
        # Generate to file
        rc, stdout, stderr = self._run_cli("--output", ".receipts")
        self.assertEqual(rc, 0)

        receipt_files = list(Path(".receipts").glob("receipt_*.json"))
        self.assertTrue(len(receipt_files) > 0, "Should have at least one receipt")

        # Verify the receipt
        rc2, stdout2, stderr2 = self._run_cli("--verify", str(receipt_files[0]))
        self.assertEqual(rc2, 0, f"Verification should pass. stderr: {stderr2}")
        self.assertIn("All good", stderr2)

    # ── 10. Deduplication ───────────────────────────────────────────────

    def test_10_ledger_deduplication(self):
        """Running 'aiir' twice on same commit produces zero duplicates."""
        # First run
        rc1, _, _ = self._run_cli()
        self.assertEqual(rc1, 0)

        # Count lines
        ledger = Path(".aiir/receipts.jsonl")
        lines_after_first = len(ledger.read_text().strip().splitlines())

        # Second run — same HEAD
        rc2, _, stderr2 = self._run_cli()
        self.assertEqual(rc2, 0)
        self.assertIn("duplicate", stderr2.lower(), "Should mention skipped duplicates")

        lines_after_second = len(ledger.read_text().strip().splitlines())
        self.assertEqual(
            lines_after_first,
            lines_after_second,
            "Ledger should not grow on re-run",
        )

    # ── 11. index.json structure ────────────────────────────────────────

    def test_11_index_json_structure(self):
        """index.json has all documented fields with correct types."""
        # Generate receipts: first the root commit, then the rest via range
        rc0, _, _ = self._run_cli("--commit", self.sha_first)
        self.assertEqual(rc0, 0)
        range_spec = f"{self.sha_first}..{self.sha_last}"
        rc, _, _ = self._run_cli("--range", range_spec)
        self.assertEqual(rc, 0)

        index = json.loads(Path(".aiir/index.json").read_text())

        # Documented fields
        self.assertEqual(index["version"], 1)
        self.assertIsInstance(index["receipt_count"], int)
        self.assertGreater(index["receipt_count"], 0)
        self.assertIsInstance(index["ai_commit_count"], int)
        self.assertIsInstance(index["bot_commit_count"], int)
        self.assertIsInstance(index["ai_percentage"], float)
        self.assertIsInstance(index["unique_authors"], int)
        self.assertIsInstance(index.get("first_receipt"), str)
        self.assertIsInstance(index.get("latest_timestamp"), str)
        self.assertIsInstance(index["commits"], dict)

        # Each commit entry has required fields
        for sha, entry in index["commits"].items():
            self.assertIn("receipt_id", entry)
            self.assertIn("ai", entry)
            self.assertIn("bot", entry)
            self.assertIn("authorship_class", entry)
            self.assertIn("author", entry)

    # ── 12. Receipt format validation ───────────────────────────────────

    def test_12_receipt_format(self):
        """Receipt JSON has every documented field with correct types."""
        rc, stdout, _ = self._run_cli("--json")
        self.assertEqual(rc, 0)
        receipt = json.loads(stdout)

        # Top-level fields
        self.assertEqual(receipt["type"], "aiir.commit_receipt")
        self.assertEqual(receipt["schema"], "aiir/commit_receipt.v2")
        self.assertIsInstance(receipt["version"], str)
        self.assertTrue(receipt["receipt_id"].startswith("g1-"))
        self.assertTrue(receipt["content_hash"].startswith("sha256:"))
        self.assertIsInstance(receipt["timestamp"], str)
        self.assertIn("T", receipt["timestamp"])  # ISO 8601

        # commit block
        commit = receipt["commit"]
        self.assertIsInstance(commit["sha"], str)
        self.assertEqual(len(commit["sha"]), 40)
        self.assertIsInstance(commit["author"], dict)
        self.assertIn("name", commit["author"])
        self.assertIn("email", commit["author"])
        self.assertIsInstance(commit["subject"], str)
        self.assertTrue(commit["diff_hash"].startswith("sha256:"))
        self.assertIsInstance(commit["files_changed"], int)

        # ai_attestation block
        ai = receipt["ai_attestation"]
        self.assertIsInstance(ai["is_ai_authored"], bool)
        self.assertIsInstance(ai["signals_detected"], list)
        self.assertIsInstance(ai["signal_count"], int)
        self.assertIsInstance(ai["is_bot_authored"], bool)
        self.assertIsInstance(ai["bot_signals_detected"], list)
        self.assertIsInstance(ai["bot_signal_count"], int)
        self.assertIn(
            ai["authorship_class"],
            [
                "human",
                "ai_assisted",
                "bot",
                "ai+bot",
            ],
        )
        self.assertEqual(ai["detection_method"], "heuristic_v2")

        # extensions block
        self.assertIn("extensions", receipt)
        self.assertIsInstance(receipt["extensions"], dict)

    # ── 13. Content-addressability ──────────────────────────────────────

    def test_13_content_addressability(self):
        """receipt_id = g1-<hash> of canonical JSON core."""
        rc, stdout, _ = self._run_cli("--json")
        self.assertEqual(rc, 0)
        receipt = json.loads(stdout)

        # Reconstruct core (everything except receipt_id, content_hash,
        # timestamp, extensions — exactly what build_commit_receipt hashes)
        core = {
            k: v
            for k, v in receipt.items()
            if k not in ("receipt_id", "content_hash", "timestamp", "extensions")
        }
        core_json = _canonical_json(core)
        expected_hash = _sha256(core_json)
        expected_id = f"g1-{expected_hash[:32]}"
        expected_content_hash = f"sha256:{expected_hash}"

        self.assertEqual(receipt["receipt_id"], expected_id)
        self.assertEqual(receipt["content_hash"], expected_content_hash)

    # ── 14. AI detection: Copilot / ChatGPT / Claude ────────────────────

    def test_14_ai_detection_copilot(self):
        """Copilot Co-authored-by trailer is detected."""
        rc, stdout, _ = self._run_cli("--commit", self.sha_copilot, "--json")
        self.assertEqual(rc, 0)
        receipt = json.loads(stdout)
        ai = receipt["ai_attestation"]
        self.assertTrue(ai["is_ai_authored"])
        self.assertEqual(ai["authorship_class"], "ai_assisted")
        # Should mention copilot in signals
        signals_str = " ".join(ai["signals_detected"]).lower()
        self.assertIn("copilot", signals_str)

    def test_14_ai_detection_chatgpt(self):
        """ChatGPT Generated-by trailer is detected."""
        rc, stdout, _ = self._run_cli("--commit", self.sha_chatgpt, "--json")
        self.assertEqual(rc, 0)
        receipt = json.loads(stdout)
        ai = receipt["ai_attestation"]
        self.assertTrue(ai["is_ai_authored"])
        self.assertEqual(ai["authorship_class"], "ai_assisted")
        signals_str = " ".join(ai["signals_detected"]).lower()
        self.assertIn("chatgpt", signals_str)

    def test_14_ai_detection_claude(self):
        """Claude Generated-by trailer is detected."""
        rc, stdout, _ = self._run_cli("--commit", self.sha_claude, "--json")
        self.assertEqual(rc, 0)
        receipt = json.loads(stdout)
        ai = receipt["ai_attestation"]
        self.assertTrue(ai["is_ai_authored"])
        self.assertEqual(ai["authorship_class"], "ai_assisted")
        signals_str = " ".join(ai["signals_detected"]).lower()
        self.assertIn("claude", signals_str)

    # ── 15. Bot detection ───────────────────────────────────────────────

    def test_15_bot_detection_dependabot(self):
        """dependabot[bot] author is classified as bot."""
        rc, stdout, _ = self._run_cli("--commit", self.sha_dependabot, "--json")
        self.assertEqual(rc, 0)
        receipt = json.loads(stdout)
        ai = receipt["ai_attestation"]
        self.assertTrue(ai["is_bot_authored"])
        self.assertFalse(ai["is_ai_authored"], "Dependabot is bot, not AI")
        self.assertEqual(ai["authorship_class"], "bot")

    def test_15_bot_detection_github_actions(self):
        """github-actions[bot] author is classified as bot."""
        rc, stdout, _ = self._run_cli("--commit", self.sha_github_actions, "--json")
        self.assertEqual(rc, 0)
        receipt = json.loads(stdout)
        ai = receipt["ai_attestation"]
        self.assertTrue(ai["is_bot_authored"])
        self.assertFalse(ai["is_ai_authored"], "github-actions is bot, not AI")
        self.assertEqual(ai["authorship_class"], "bot")

    # ── 16. authorship_class values ─────────────────────────────────────

    def test_16_authorship_class_human(self):
        """Human commit gets authorship_class='human'."""
        rc, stdout, _ = self._run_cli("--commit", self.sha_human, "--json")
        self.assertEqual(rc, 0)
        receipt = json.loads(stdout)
        ai = receipt["ai_attestation"]
        self.assertFalse(ai["is_ai_authored"])
        self.assertFalse(ai["is_bot_authored"])
        self.assertEqual(ai["authorship_class"], "human")

    def test_16b_authorship_class_ai_and_bot(self):
        """Bot author + AI co-authored-by gets authorship_class='ai+bot'."""
        rc, stdout, _ = self._run_cli("--commit", self.sha_ai_and_bot, "--json")
        self.assertEqual(rc, 0)
        receipt = json.loads(stdout)
        ai = receipt["ai_attestation"]
        self.assertTrue(ai["is_ai_authored"], "Should detect AI co-authored-by")
        self.assertTrue(ai["is_bot_authored"], "Should detect bot author")
        self.assertEqual(ai["authorship_class"], "ai+bot")

    # ── 17. --redact-files ──────────────────────────────────────────────

    def test_17_redact_files(self):
        """--redact-files omits file paths, sets files_redacted=True."""
        rc, stdout, _ = self._run_cli("--redact-files", "--json")
        self.assertEqual(rc, 0)
        receipt = json.loads(stdout)
        commit = receipt["commit"]
        self.assertTrue(commit.get("files_redacted"), "files_redacted should be True")
        self.assertNotIn("files", commit, "files list should be omitted")

    def test_17_no_redact_includes_files(self):
        """Without --redact-files, file paths are included."""
        rc, stdout, _ = self._run_cli("--json")
        self.assertEqual(rc, 0)
        receipt = json.loads(stdout)
        commit = receipt["commit"]
        self.assertIn("files", commit, "files list should be present")
        self.assertIsInstance(commit["files"], list)

    # ── 18. --github-action ─────────────────────────────────────────────

    def test_18_github_action_outputs(self):
        """--github-action sets receipt_count and ai_commit_count outputs."""
        # Create a fake GITHUB_OUTPUT file
        gh_output = Path(self._tmpdir, "gh_output.txt")
        gh_output.write_text("")

        env_patch = {
            "GITHUB_OUTPUT": str(gh_output),
            "GITHUB_STEP_SUMMARY": str(Path(self._tmpdir, "gh_summary.md")),
        }
        Path(self._tmpdir, "gh_summary.md").write_text("")

        with patch.dict(os.environ, env_patch):
            rc, stdout, stderr = self._run_cli(
                "--range",
                f"{self.sha_human}..{self.sha_claude}",
                "--github-action",
            )
        self.assertEqual(rc, 0)

        output_text = gh_output.read_text()
        self.assertIn("receipt_count", output_text)
        self.assertIn("ai_commit_count", output_text)

    # ── 19. --version ───────────────────────────────────────────────────

    def test_19_version(self):
        """'aiir --version' prints current version."""
        out = StringIO()
        with self.assertRaises(SystemExit) as ctx:
            with patch("sys.stdout", out):
                cli.main(["--version"])
        self.assertEqual(ctx.exception.code, 0)
        self.assertIn(__version__, out.getvalue())

    # ── 20. --help ──────────────────────────────────────────────────────

    def test_20_help_includes_examples(self):
        """'aiir --help' includes documented usage examples."""
        out = StringIO()
        with self.assertRaises(SystemExit) as ctx:
            with patch("sys.stdout", out):
                cli.main(["--help"])
        self.assertEqual(ctx.exception.code, 0)
        help_text = out.getvalue()
        self.assertIn("examples:", help_text)
        self.assertIn("aiir --pretty", help_text)
        self.assertIn("--verify", help_text)

    # ── 21. --json single commit → JSON object ─────────────────────────

    def test_21_json_single_is_object(self):
        """Single-commit --json returns a JSON object (not array)."""
        rc, stdout, _ = self._run_cli("--commit", self.sha_human, "--json")
        self.assertEqual(rc, 0)
        data = json.loads(stdout)
        self.assertIsInstance(data, dict, "Single commit should be dict, not list")

    def test_21_json_range_is_array(self):
        """Multi-commit --json returns a JSON array."""
        range_spec = f"{self.sha_human}..{self.sha_claude}"
        rc, stdout, _ = self._run_cli("--range", range_spec, "--json")
        self.assertEqual(rc, 0)
        data = json.loads(stdout)
        self.assertIsInstance(data, list, "Range --json should be array")
        self.assertEqual(len(data), 3)

    # ── 22. --export ────────────────────────────────────────────────────

    def test_22_export_creates_bundle(self):
        """'aiir --export' creates a portable JSON bundle."""
        # First, generate a ledger
        rc, _, _ = self._run_cli()
        self.assertEqual(rc, 0)

        # Export it
        rc2, _, stderr2 = self._run_cli("--export", "export.json")
        self.assertEqual(rc2, 0, f"Export should succeed. stderr: {stderr2}")

        bundle = json.loads(Path("export.json").read_text())
        self.assertEqual(bundle["format"], "aiir.export.v1")
        self.assertIn("exported_at", bundle)
        self.assertIn("instance_id", bundle)
        self.assertIn("index", bundle)
        self.assertIn("receipts", bundle)
        self.assertIsInstance(bundle["receipts"], list)
        self.assertGreater(len(bundle["receipts"]), 0)

    # ── 23. --stats / --badge / --check ─────────────────────────────────

    def test_23_stats_after_ledger(self):
        """'aiir --stats' works after generating a ledger."""
        # Generate
        rc, _, _ = self._run_cli()
        self.assertEqual(rc, 0)

        # Stats
        rc2, _, stderr2 = self._run_cli("--stats")
        self.assertEqual(rc2, 0)
        # Stats should mention receipts or commits
        self.assertTrue(
            "receipt" in stderr2.lower() or "commit" in stderr2.lower(),
            f"Stats should mention receipts or commits. Got: {stderr2}",
        )

    def test_23_badge_after_ledger(self):
        """'aiir --badge' prints shield badge markdown."""
        # Generate
        rc, _, _ = self._run_cli()
        self.assertEqual(rc, 0)

        # Badge
        rc2, stdout2, _ = self._run_cli("--badge")
        self.assertEqual(rc2, 0)
        self.assertIn("img.shields.io", stdout2)

    def test_23_check_passes(self):
        """'aiir --check' passes with default policy."""
        # Generate
        rc, _, _ = self._run_cli()
        self.assertEqual(rc, 0)

        # Check
        rc2, _, stderr2 = self._run_cli("--check")
        self.assertEqual(rc2, 0)

    # ── 24. Summary and UX emoji ────────────────────────────────────────

    def test_24_summary_has_checkmark(self):
        """Post-generation summary shows ✅."""
        rc, _, stderr = self._run_cli("--pretty")
        self.assertEqual(rc, 0)
        self.assertIn("receipt", stderr.lower())

    def test_24_unsigned_tip(self):
        """Without --sign, shows signing tip (📝)."""
        rc, _, stderr = self._run_cli("--pretty")
        self.assertEqual(rc, 0)
        self.assertIn("--sign", stderr, "Should mention --sign tip")

    # ── 25. Verify tampered receipt fails ───────────────────────────────

    def test_25_verify_tampered_fails(self):
        """Verify a tampered receipt returns rc=1."""
        # Generate a receipt
        rc, stdout, _ = self._run_cli("--json")
        self.assertEqual(rc, 0)
        receipt = json.loads(stdout)

        # Tamper with it
        receipt["commit"]["subject"] = "TAMPERED"
        tampered_path = Path(self._tmpdir, "tampered.json")
        tampered_path.write_text(json.dumps(receipt, indent=2))

        # Verify should fail
        rc2, _, stderr2 = self._run_cli("--verify", str(tampered_path))
        self.assertEqual(rc2, 1, "Tampered receipt should fail verification")

    # ── 26. Provenance fields ───────────────────────────────────────────

    def test_26_provenance_fields(self):
        """Receipt includes provenance block with tool and generator."""
        rc, stdout, _ = self._run_cli("--json")
        self.assertEqual(rc, 0)
        receipt = json.loads(stdout)

        self.assertIn("provenance", receipt)
        prov = receipt["provenance"]
        self.assertIn("tool", prov)
        self.assertIn("generator", prov)
        self.assertIn("aiir", prov["tool"])
        self.assertEqual(prov["generator"], "aiir.cli")

    # ── 27. All 6 commits get correct classifications ───────────────────

    def test_27_full_range_all_classifications(self):
        """All 6 commits in the repo get correct classifications."""
        # Get root commit separately (sha~1 doesn't work on root)
        rc0, stdout0, _ = self._run_cli("--commit", self.sha_first, "--json")
        self.assertEqual(rc0, 0)
        # Get remaining 6 via range
        range_spec = f"{self.sha_first}..{self.sha_last}"
        rc, stdout, _ = self._run_cli("--range", range_spec, "--json")
        self.assertEqual(rc, 0)
        receipts = json.loads(stdout)
        self.assertIsInstance(receipts, list)
        receipts.insert(0, json.loads(stdout0))  # prepend root
        self.assertEqual(len(receipts), 7, "Should have 7 receipts")

        # Build a sha→receipt map
        by_sha = {r["commit"]["sha"]: r for r in receipts}

        # Human
        self.assertEqual(
            by_sha[self.sha_human]["ai_attestation"]["authorship_class"],
            "human",
        )
        # Copilot
        self.assertEqual(
            by_sha[self.sha_copilot]["ai_attestation"]["authorship_class"],
            "ai_assisted",
        )
        # ChatGPT
        self.assertEqual(
            by_sha[self.sha_chatgpt]["ai_attestation"]["authorship_class"],
            "ai_assisted",
        )
        # Claude
        self.assertEqual(
            by_sha[self.sha_claude]["ai_attestation"]["authorship_class"],
            "ai_assisted",
        )
        # Dependabot
        self.assertEqual(
            by_sha[self.sha_dependabot]["ai_attestation"]["authorship_class"],
            "bot",
        )
        # github-actions
        self.assertEqual(
            by_sha[self.sha_github_actions]["ai_attestation"]["authorship_class"],
            "bot",
        )
        # AI + bot (dependabot with Copilot co-authored-by)
        self.assertEqual(
            by_sha[self.sha_ai_and_bot]["ai_attestation"]["authorship_class"],
            "ai+bot",
        )

    # ── 28. Quiet mode suppresses tips ──────────────────────────────────

    def test_28_quiet_mode(self):
        """--quiet suppresses tips and non-essential output."""
        rc, _, stderr = self._run_cli("--quiet")
        self.assertEqual(rc, 0)
        self.assertNotIn("--sign", stderr, "Quiet mode should suppress signing tip")
        self.assertNotIn(
            "--redact-files", stderr, "Quiet mode should suppress privacy hint"
        )

    # ── 29. Verify multi-receipt file ───────────────────────────────────

    def test_29_verify_jsonl_array(self):
        """Verify works on a JSON array of receipts."""
        # Generate 3 receipts as JSON array
        range_spec = f"{self.sha_human}..{self.sha_claude}"
        rc, stdout, _ = self._run_cli("--range", range_spec, "--json")
        self.assertEqual(rc, 0)

        # Write as a JSON array file
        array_path = Path(self._tmpdir, "multi.json")
        array_path.write_text(stdout)

        # Verify
        rc2, _, stderr2 = self._run_cli("--verify", str(array_path))
        self.assertEqual(rc2, 0, f"Multi-receipt verify should pass. stderr: {stderr2}")
        self.assertIn("3 receipts verified", stderr2)

    # ── 30. Custom ledger read-path (Bug #1 regression) ────────────────

    def test_30_stats_reads_custom_ledger(self):
        """--stats --ledger .audit/ reads from .audit/, not default .aiir/."""
        # Write receipts to custom ledger dir
        rc, _, _ = self._run_cli("--ledger", ".audit")
        self.assertEqual(rc, 0)
        self.assertTrue(Path(".audit/index.json").exists())

        # .aiir/ must NOT exist — proves we're not falling back
        self.assertFalse(
            Path(".aiir").exists(),
            "Default .aiir/ should not be created when using custom ledger",
        )

        # --stats with custom ledger should succeed
        rc2, _, stderr2 = self._run_cli("--stats", "--ledger", ".audit")
        self.assertEqual(
            rc2, 0, f"--stats with custom ledger should work. stderr: {stderr2}"
        )
        self.assertTrue(
            "receipt" in stderr2.lower() or "commit" in stderr2.lower(),
            f"Stats should show data from custom ledger. Got: {stderr2}",
        )

    def test_30_badge_reads_custom_ledger(self):
        """--badge --ledger .audit/ reads from .audit/, not default .aiir/."""
        rc, _, _ = self._run_cli("--ledger", ".audit")
        self.assertEqual(rc, 0)

        rc2, stdout2, _ = self._run_cli("--badge", "--ledger", ".audit")
        self.assertEqual(rc2, 0, "Badge with custom ledger should succeed")
        self.assertIn("img.shields.io", stdout2)

    def test_30_check_reads_custom_ledger(self):
        """--check --ledger .audit/ reads from .audit/, not default .aiir/."""
        rc, _, _ = self._run_cli("--ledger", ".audit")
        self.assertEqual(rc, 0)

        rc2, _, stderr2 = self._run_cli("--check", "--ledger", ".audit")
        self.assertEqual(
            rc2, 0, f"Check with custom ledger should pass. stderr: {stderr2}"
        )

    def test_30_export_reads_custom_ledger(self):
        """--export --ledger .audit/ reads from .audit/, not default .aiir/."""
        rc, _, _ = self._run_cli("--ledger", ".audit")
        self.assertEqual(rc, 0)

        rc2, _, stderr2 = self._run_cli("--export", "bundle.json", "--ledger", ".audit")
        self.assertEqual(
            rc2, 0, f"Export with custom ledger should work. stderr: {stderr2}"
        )
        bundle = json.loads(Path("bundle.json").read_text())
        self.assertEqual(bundle["format"], "aiir.export.v1")
        self.assertGreater(len(bundle["receipts"]), 0)

    def test_30_stats_fails_without_custom_ledger_flag(self):
        """--stats without --ledger should fail when receipts are only in .audit/."""
        # Write to custom dir
        rc, _, _ = self._run_cli("--ledger", ".audit")
        self.assertEqual(rc, 0)

        # --stats without --ledger should fail (no .aiir/ exists)
        rc2, _, stderr2 = self._run_cli("--stats")
        self.assertEqual(
            rc2, 1, "Stats without --ledger should fail when no default ledger"
        )
        self.assertIn("No ledger found", stderr2)


if __name__ == "__main__":
    unittest.main()
