// SPDX-License-Identifier: Apache-2.0
// Copyright 2025-2026 Invariant Systems, Inc.
//
//! Cross-language deterministic CBOR decoder for AIIR canonical objects.
//!
//! This crate is the Rust dual of the Python `_verify_cbor.py` decoder.
//! It enforces identical strictness rules:
//!
//!   - Integers use shortest encoding (RFC 8949 §4.2.1).
//!   - No indefinite-length containers.
//!   - Map keys sorted by (encoded-length, lexicographic-bytes).
//!   - No non-finite floats (NaN, ±Inf).
//!
//! The primary purpose is to decode golden test vectors generated by the
//! Python encoder and confirm byte-identical round-trip, thereby proving
//! cross-language determinism of the canonical CBOR format.

use std::fmt;

// ── Error type ───────────────────────────────────────────────────────

/// Error returned when CBOR bytes cannot be decoded or violate determinism rules.
#[derive(Debug, Clone)]
pub struct CborDecodeError(pub String);

impl fmt::Display for CborDecodeError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "CborDecodeError: {}", self.0)
    }
}

impl std::error::Error for CborDecodeError {}

// ── Value type ───────────────────────────────────────────────────────

/// A decoded CBOR value.
#[derive(Debug, Clone)]
pub enum CborValue {
    Uint(u64),
    NegInt(i64), // stores -1 - n  (i.e. the actual value)
    Bytes(Vec<u8>),
    Text(String),
    Array(Vec<CborValue>),
    Map(Vec<(CborValue, CborValue)>), // preserves insertion order
    Bool(bool),
    Null,
    Float(f64),
}

impl PartialEq for CborValue {
    fn eq(&self, other: &Self) -> bool {
        match (self, other) {
            (CborValue::Uint(a), CborValue::Uint(b)) => a == b,
            (CborValue::NegInt(a), CborValue::NegInt(b)) => a == b,
            (CborValue::Bytes(a), CborValue::Bytes(b)) => a == b,
            (CborValue::Text(a), CborValue::Text(b)) => a == b,
            (CborValue::Array(a), CborValue::Array(b)) => a == b,
            (CborValue::Map(a), CborValue::Map(b)) => a == b,
            (CborValue::Bool(a), CborValue::Bool(b)) => a == b,
            (CborValue::Null, CborValue::Null) => true,
            (CborValue::Float(a), CborValue::Float(b)) => a.to_bits() == b.to_bits(),
            _ => false,
        }
    }
}

impl Eq for CborValue {}

// ── Encoder (canonical) ──────────────────────────────────────────────

fn encode_uint_head(major: u8, n: u64) -> Vec<u8> {
    let m = major << 5;
    if n < 24 {
        vec![m | (n as u8)]
    } else if n < 256 {
        vec![m | 24, n as u8]
    } else if n < 65536 {
        let mut v = vec![m | 25];
        v.extend_from_slice(&(n as u16).to_be_bytes());
        v
    } else if n < 4_294_967_296 {
        let mut v = vec![m | 26];
        v.extend_from_slice(&(n as u32).to_be_bytes());
        v
    } else {
        let mut v = vec![m | 27];
        v.extend_from_slice(&n.to_be_bytes());
        v
    }
}

/// Attempt to encode a float as f16 (half-precision).
/// Returns `Some(2-byte big-endian)` if lossless, else `None`.
fn try_f16(x: f64) -> Option<[u8; 2]> {
    // First check that f64→f32 is lossless
    let f32v = x as f32;
    if (f32v as f64).to_bits() != x.to_bits() {
        return None;
    }
    let bits32 = f32v.to_bits();
    let sign = ((bits32 >> 16) & 0x8000) as u16;
    let exp = ((bits32 >> 23) & 0xFF) as i32;
    let mant = bits32 & 0x7F_FFFF;
    let exp16 = exp - 127 + 15;

    if exp == 0xFF || exp16 >= 0x1F {
        return None;
    }

    let half: u16;
    if exp16 <= 0 {
        if exp16 < -10 {
            half = sign;
        } else {
            let mantissa = mant | 0x80_0000;
            let shift = 14 - exp16;
            half = sign | (((mantissa >> shift) as u16) & 0xFFFF);
        }
    } else {
        half = sign | (((exp16 as u16) & 0x1F) << 10) | (((mant >> 13) as u16) & 0x3FF);
    }

    // Verify round-trip
    let rt = f16_to_f64(half);
    if rt.to_bits() == x.to_bits() {
        Some(half.to_be_bytes())
    } else {
        None
    }
}

fn f16_to_f64(bits: u16) -> f64 {
    let sign: f64 = if (bits & 0x8000) != 0 { -1.0 } else { 1.0 };
    let exp = ((bits >> 10) & 0x1F) as i32;
    let frac = (bits & 0x03FF) as f64;
    if exp == 0 {
        sign * (frac / 1024.0) * f64::powi(2.0, -14)
    } else {
        sign * (1.0 + frac / 1024.0) * f64::powi(2.0, exp - 15)
    }
}

fn encode_float_canonical(x: f64) -> Result<Vec<u8>, CborDecodeError> {
    if x.is_nan() || x.is_infinite() {
        return Err(CborDecodeError(
            "non-finite float not allowed in canonical CBOR".into(),
        ));
    }
    if let Some(h) = try_f16(x) {
        let mut v = vec![0xF9];
        v.extend_from_slice(&h);
        return Ok(v);
    }
    // Try f32
    let f32v = x as f32;
    if (f32v as f64).to_bits() == x.to_bits() {
        let mut v = vec![0xFA];
        v.extend_from_slice(&f32v.to_be_bytes());
        return Ok(v);
    }
    // f64
    let mut v = vec![0xFB];
    v.extend_from_slice(&x.to_be_bytes());
    Ok(v)
}

/// Encode a `CborValue` into canonical CBOR bytes.
pub fn encode(val: &CborValue) -> Result<Vec<u8>, CborDecodeError> {
    match val {
        CborValue::Null => Ok(vec![0xF6]),
        CborValue::Bool(false) => Ok(vec![0xF4]),
        CborValue::Bool(true) => Ok(vec![0xF5]),
        CborValue::Uint(n) => Ok(encode_uint_head(0, *n)),
        CborValue::NegInt(n) => {
            // n is the actual negative value: -1 - raw => raw = -1 - n
            let raw = (-1i128 - (*n as i128)) as u64;
            Ok(encode_uint_head(1, raw))
        }
        CborValue::Float(x) => encode_float_canonical(*x),
        CborValue::Bytes(b) => {
            let mut out = encode_uint_head(2, b.len() as u64);
            out.extend_from_slice(b);
            Ok(out)
        }
        CborValue::Text(s) => {
            let b = s.as_bytes();
            let mut out = encode_uint_head(3, b.len() as u64);
            out.extend_from_slice(b);
            Ok(out)
        }
        CborValue::Array(items) => {
            let mut out = encode_uint_head(4, items.len() as u64);
            for item in items {
                out.extend(encode(item)?);
            }
            Ok(out)
        }
        CborValue::Map(entries) => {
            // Sort by (encoded-key-length, encoded-key-bytes)
            let mut encoded_entries: Vec<(Vec<u8>, Vec<u8>)> = Vec::new();
            for (k, v) in entries {
                let kb = encode(k)?;
                let vb = encode(v)?;
                encoded_entries.push((kb, vb));
            }
            encoded_entries.sort_by(|a, b| (a.0.len(), &a.0).cmp(&(b.0.len(), &b.0)));
            let mut out = encode_uint_head(5, entries.len() as u64);
            for (kb, vb) in &encoded_entries {
                out.extend_from_slice(kb);
                out.extend_from_slice(vb);
            }
            Ok(out)
        }
    }
}

// ── Decoder (strict, canonical) ──────────────────────────────────────

fn read_uint(data: &[u8], offset: usize) -> Result<(u64, usize), CborDecodeError> {
    if offset >= data.len() {
        return Err(CborDecodeError("unexpected end of input".into()));
    }
    let additional = data[offset] & 0x1F;
    let off = offset + 1;

    match additional {
        n if n < 24 => Ok((n as u64, off)),
        24 => {
            if off >= data.len() {
                return Err(CborDecodeError("unexpected end of input".into()));
            }
            let val = data[off] as u64;
            if val < 24 {
                return Err(CborDecodeError(format!(
                    "non-canonical uint encoding: {} in 1-byte form",
                    val
                )));
            }
            Ok((val, off + 1))
        }
        25 => {
            if off + 2 > data.len() {
                return Err(CborDecodeError("unexpected end of input".into()));
            }
            let val = u16::from_be_bytes([data[off], data[off + 1]]) as u64;
            if val < 256 {
                return Err(CborDecodeError(format!(
                    "non-canonical uint encoding: {} in 2-byte form",
                    val
                )));
            }
            Ok((val, off + 2))
        }
        26 => {
            if off + 4 > data.len() {
                return Err(CborDecodeError("unexpected end of input".into()));
            }
            let val = u32::from_be_bytes([
                data[off],
                data[off + 1],
                data[off + 2],
                data[off + 3],
            ]) as u64;
            if val < 65536 {
                return Err(CborDecodeError(format!(
                    "non-canonical uint encoding: {} in 4-byte form",
                    val
                )));
            }
            Ok((val, off + 4))
        }
        27 => {
            if off + 8 > data.len() {
                return Err(CborDecodeError("unexpected end of input".into()));
            }
            let val = u64::from_be_bytes([
                data[off],
                data[off + 1],
                data[off + 2],
                data[off + 3],
                data[off + 4],
                data[off + 5],
                data[off + 6],
                data[off + 7],
            ]);
            if val < 4_294_967_296 {
                return Err(CborDecodeError(format!(
                    "non-canonical uint encoding: {} in 8-byte form",
                    val
                )));
            }
            Ok((val, off + 8))
        }
        _ => Err(CborDecodeError(format!(
            "non-canonical or unsupported additional info: {}",
            additional
        ))),
    }
}

fn decode_f16(data: &[u8], offset: usize) -> Result<(f64, usize), CborDecodeError> {
    if offset + 2 > data.len() {
        return Err(CborDecodeError(
            "unexpected end of input for f16".into(),
        ));
    }
    let bits = u16::from_be_bytes([data[offset], data[offset + 1]]);
    let sign: f64 = if (bits & 0x8000) != 0 { -1.0 } else { 1.0 };
    let exp = ((bits >> 10) & 0x1F) as i32;
    let frac = (bits & 0x03FF) as f64;

    if exp == 0x1F {
        return Err(CborDecodeError(
            "non-finite float not allowed in canonical CBOR".into(),
        ));
    }

    let val = if exp == 0 {
        sign * (frac / 1024.0) * f64::powi(2.0, -14)
    } else {
        sign * (1.0 + frac / 1024.0) * f64::powi(2.0, exp - 15)
    };

    Ok((val, offset + 2))
}

fn decode_float(
    data: &[u8],
    offset: usize,
    additional: u8,
) -> Result<(f64, usize), CborDecodeError> {
    match additional {
        25 => decode_f16(data, offset),
        26 => {
            if offset + 4 > data.len() {
                return Err(CborDecodeError(
                    "unexpected end of input for f32".into(),
                ));
            }
            let val = f32::from_be_bytes([
                data[offset],
                data[offset + 1],
                data[offset + 2],
                data[offset + 3],
            ]) as f64;
            Ok((val, offset + 4))
        }
        27 => {
            if offset + 8 > data.len() {
                return Err(CborDecodeError(
                    "unexpected end of input for f64".into(),
                ));
            }
            let val = f64::from_be_bytes([
                data[offset],
                data[offset + 1],
                data[offset + 2],
                data[offset + 3],
                data[offset + 4],
                data[offset + 5],
                data[offset + 6],
                data[offset + 7],
            ]);
            Ok((val, offset + 8))
        }
        _ => Err(CborDecodeError(format!(
            "unsupported float additional info: {}",
            additional
        ))),
    }
}

/// Decode one CBOR data item from `data` at `offset`.
/// Returns `(value, new_offset)`.
///
/// Enforces canonical encoding: shortest integers, no indefinite-length,
/// map keys sorted by `(encoded_length, encoded_bytes)`.
pub fn decode(data: &[u8], offset: usize) -> Result<(CborValue, usize), CborDecodeError> {
    if offset >= data.len() {
        return Err(CborDecodeError("unexpected end of input".into()));
    }

    let initial = data[offset];
    let major = (initial >> 5) & 0x07;
    let additional = initial & 0x1F;

    match major {
        // Major 0: unsigned integer
        0 => {
            let (val, off) = read_uint(data, offset)?;
            Ok((CborValue::Uint(val), off))
        }
        // Major 1: negative integer
        1 => {
            let (val, off) = read_uint(data, offset)?;
            Ok((CborValue::NegInt(-1 - (val as i64)), off))
        }
        // Major 2: byte string
        2 => {
            let (length, off) = read_uint(data, offset)?;
            let len = length as usize;
            if off + len > data.len() {
                return Err(CborDecodeError(
                    "byte string extends past end of input".into(),
                ));
            }
            Ok((CborValue::Bytes(data[off..off + len].to_vec()), off + len))
        }
        // Major 3: text string (UTF-8)
        3 => {
            let (length, off) = read_uint(data, offset)?;
            let len = length as usize;
            if off + len > data.len() {
                return Err(CborDecodeError(
                    "text string extends past end of input".into(),
                ));
            }
            let text = std::str::from_utf8(&data[off..off + len])
                .map_err(|e| CborDecodeError(format!("invalid UTF-8 in text string: {}", e)))?;
            Ok((CborValue::Text(text.to_string()), off + len))
        }
        // Major 4: array
        4 => {
            let (count, mut off) = read_uint(data, offset)?;
            let mut items = Vec::with_capacity(count as usize);
            for _ in 0..count {
                let (item, new_off) = decode(data, off)?;
                items.push(item);
                off = new_off;
            }
            Ok((CborValue::Array(items), off))
        }
        // Major 5: map
        5 => {
            let (count, mut off) = read_uint(data, offset)?;
            let mut entries = Vec::with_capacity(count as usize);
            let mut prev_key_bytes: Option<Vec<u8>> = None;
            for _ in 0..count {
                let key_start = off;
                let (key, new_off) = decode(data, off)?;
                let key_bytes = data[key_start..new_off].to_vec();

                // Check canonical key ordering
                if let Some(ref prev) = prev_key_bytes {
                    if (key_bytes.len(), &key_bytes) <= (prev.len(), prev) {
                        return Err(CborDecodeError(
                            "map keys not in canonical order".into(),
                        ));
                    }
                }
                prev_key_bytes = Some(key_bytes);
                off = new_off;

                let (value, new_off) = decode(data, off)?;
                entries.push((key, value));
                off = new_off;
            }
            Ok((CborValue::Map(entries), off))
        }
        // Major 7: simple values and floats
        7 => match additional {
            20 => Ok((CborValue::Bool(false), offset + 1)),
            21 => Ok((CborValue::Bool(true), offset + 1)),
            22 => Ok((CborValue::Null, offset + 1)),
            25 | 26 | 27 => {
                let (val, off) = decode_float(data, offset + 1, additional)?;
                Ok((CborValue::Float(val), off))
            }
            _ => Err(CborDecodeError(format!(
                "unsupported simple value: {}",
                additional
            ))),
        },
        // Major 6 (tags) and others: not supported
        _ => Err(CborDecodeError(format!(
            "unsupported CBOR major type: {}",
            major
        ))),
    }
}

/// Decode exactly one CBOR item consuming all bytes.
/// Returns an error if there are trailing bytes.
pub fn decode_full(data: &[u8]) -> Result<CborValue, CborDecodeError> {
    let (value, offset) = decode(data, 0)?;
    if offset != data.len() {
        return Err(CborDecodeError(format!(
            "trailing bytes: {} bytes after CBOR item",
            data.len() - offset
        )));
    }
    Ok(value)
}

// ── Envelope verification ────────────────────────────────────────────

const CANONICAL_OBJECT_TYPE: &str = "aiir.canonical_object";
const CANONICAL_OBJECT_SCHEMA: &str = "aiir/canonical_object.v1";

/// Validate the Layer-0 envelope structure.
/// Returns a list of error strings (empty = valid).
pub fn verify_envelope(obj: &CborValue) -> Vec<String> {
    let mut errors = Vec::new();

    let map = match obj {
        CborValue::Map(entries) => entries,
        other => {
            return vec![format!(
                "envelope is {:?}, expected map",
                std::mem::discriminant(other)
            )];
        }
    };

    let get_text = |key: &str| -> Option<&str> {
        for (k, v) in map {
            if let CborValue::Text(k_str) = k {
                if k_str == key {
                    if let CborValue::Text(v_str) = v {
                        return Some(v_str.as_str());
                    }
                }
            }
        }
        None
    };

    let required = ["type", "schema", "kind", "object_schema", "core"];
    let present: Vec<&str> = map
        .iter()
        .filter_map(|(k, _)| {
            if let CborValue::Text(s) = k {
                Some(s.as_str())
            } else {
                None
            }
        })
        .collect();

    let missing: Vec<&&str> = required
        .iter()
        .filter(|r| !present.contains(*r))
        .collect();

    if !missing.is_empty() {
        errors.push(format!("missing envelope keys: {:?}", missing));
        return errors;
    }

    if let Some(t) = get_text("type") {
        if t != CANONICAL_OBJECT_TYPE {
            errors.push(format!(
                "envelope type mismatch: {:?} != {:?}",
                t, CANONICAL_OBJECT_TYPE
            ));
        }
    }
    if let Some(s) = get_text("schema") {
        if s != CANONICAL_OBJECT_SCHEMA {
            errors.push(format!(
                "envelope schema mismatch: {:?} != {:?}",
                s, CANONICAL_OBJECT_SCHEMA
            ));
        }
    }
    if let Some(k) = get_text("kind") {
        if k.is_empty() {
            errors.push("envelope kind must be a non-empty string".into());
        }
    }
    if let Some(os) = get_text("object_schema") {
        if os.is_empty() {
            errors.push("envelope object_schema must be a non-empty string".into());
        }
    }

    // Check core is a map
    let has_core_map = map.iter().any(|(k, v)| {
        matches!(k, CborValue::Text(s) if s == "core") && matches!(v, CborValue::Map(_))
    });
    if !has_core_map {
        errors.push("envelope core is not a map".into());
    }

    errors
}

/// Verify a CBOR sidecar: decode, validate envelope, check round-trip.
/// Returns `(valid, errors, sha256_hex)`.
pub fn verify_sidecar(cbor_bytes: &[u8]) -> (bool, Vec<String>, String) {
    use sha2::{Digest, Sha256};

    let mut errors = Vec::new();

    // 1. Decode
    let obj = match decode_full(cbor_bytes) {
        Ok(v) => v,
        Err(e) => {
            return (false, vec![format!("CBOR decode error: {}", e)], String::new());
        }
    };

    // 2. Envelope
    let env_errors = verify_envelope(&obj);
    if !env_errors.is_empty() {
        return (false, env_errors, String::new());
    }

    // 3. Round-trip
    let re_encoded = match encode(&obj) {
        Ok(v) => v,
        Err(e) => {
            return (false, vec![format!("re-encode failed: {}", e)], String::new());
        }
    };

    if re_encoded != cbor_bytes {
        errors.push(format!(
            "round-trip mismatch: original {} bytes, re-encoded {} bytes",
            cbor_bytes.len(),
            re_encoded.len()
        ));
    }

    let sha256 = hex::encode(Sha256::digest(cbor_bytes));
    let valid = errors.is_empty();
    (valid, errors, sha256)
}

#[cfg(test)]
mod tests;
