"""
AIIR internal core — constants, encoding helpers, git operations, hashing.

This module contains the foundational utilities shared across all AIIR
submodules. It is NOT part of the public API; import from ``aiir.cli`` instead.

Copyright 2025-2026 Invariant Systems, Inc.
SPDX-License-Identifier: Apache-2.0
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import re
import subprocess
import sys
import time
import unicodedata
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List, Optional, Tuple
from urllib.parse import urlparse, urlunparse

# Structured logging for observability/debuggability.
# Users enable with --verbose or AIIR_LOG_LEVEL=DEBUG.
logger = logging.getLogger("aiir")

# Windows does not have os.fchmod — guard all permission-setting calls.
_HAS_FCHMOD = hasattr(os, "fchmod")


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

RECEIPT_SCHEMA_VERSION = "aiir/commit_receipt.v1"

# Single source of truth — __version__ lives in __init__.py only.
from aiir import __version__ as CLI_VERSION

# Safety limit: max commits to receipt in a single range (DoS prevention)
MAX_RECEIPTS_PER_RANGE = 1000

# Safety limit: max file size for receipt verification (50 MB)
MAX_RECEIPT_FILE_SIZE = 50 * 1024 * 1024

# GitHub Actions step summary size limit (1 MB matches GitHub's own limit).
MAX_SUMMARY_SIZE = 1024 * 1024

# Default ledger directory and filenames.
LEDGER_DIR = ".aiir"
LEDGER_FILE = "receipts.jsonl"
INDEX_FILE = "index.json"
CONFIG_FILE = "config.json"

# Default subprocess timeout (seconds) to prevent indefinite hangs
GIT_TIMEOUT = 300

# Prevent auth hangs (GIT_TERMINAL_PROMPT) and credential helpers (GIT_ASKPASS)
# in CI environments where no human is present.
_GIT_SAFE_ENV: Dict[str, str] = {
    **os.environ,
    "GIT_TERMINAL_PROMPT": "0",
    "GIT_ASKPASS": "",
}


# ---------------------------------------------------------------------------
# Encoding-safe symbol helpers
# ---------------------------------------------------------------------------
# Emoji above U+2700 crash on Windows cmd.exe (cp437/cp1252), CI runners with
# LANG=C, and piped stderr (encoding=ascii).  Box-drawing chars (U+2500 range)
# survive cp437 but crash on cp1252 (PowerShell default) and ASCII/latin-1.
# We probe sys.stderr.encoding once and fall back to plain ASCII when needed.

_EMOJI: Dict[str, Tuple[str, str]] = {
    "ok":     ("\u2705", "[ok]"),       # ✅
    "error":  ("\u274c", "[error]"),     # ❌
    "hint":   ("\U0001f4a1", "[hint]"),  # 💡
    "ai":     ("\U0001f916", "[AI]"),    # 🤖
    "signed": ("\U0001f58a\ufe0f", "[signed]"),  # 🖊️
    "tip":    ("\U0001f4dd", "[tip]"),   # 📝
    "shrug":  ("\U0001f937", "[info]"),  # 🤷
    "check":  ("\u2714", "ok"),          # ✔
}

# Box-drawing glyphs used in format_receipt_pretty.  These survive on cp437
# (DOS/Windows Console Host) but crash on cp1252 (PowerShell default),
# latin-1, and ASCII.  Fall back to safe ASCII art (+, -, |).
_BOX: Dict[str, Tuple[str, str]] = {
    "tl":   ("\u250c", "+"),   # ┌  top-left corner
    "vl":   ("\u2502", "|"),   # │  vertical line
    "bl":   ("\u2514", "+"),   # └  bottom-left corner
    "hl":   ("\u2500", "-"),   # ─  horizontal line
}


def _can_encode(probe: str) -> bool:
    """Return True if stderr can encode *probe* without error."""
    try:
        enc = getattr(sys.stderr, "encoding", None) or "ascii"
        probe.encode(enc)
        return True
    except (UnicodeEncodeError, LookupError):  # pragma: no cover
        return False


# Resolved once at import time; overridable in tests via monkeypatching.
_USE_EMOJI: bool = _can_encode("\u2705\U0001f916")
_USE_BOXDRAW: bool = _can_encode("\u250c\u2500\u2502\u2514")


def _e(name: str) -> str:
    """Return emoji glyph if the terminal supports it, else ASCII fallback."""
    pair = _EMOJI.get(name)
    if pair is None:
        return ""
    return pair[0] if _USE_EMOJI else pair[1]


def _b(name: str) -> str:
    """Return box-drawing glyph if the terminal supports it, else ASCII."""
    pair = _BOX.get(name)
    if pair is None:
        return ""
    return pair[0] if _USE_BOXDRAW else pair[1]


# Unicode TR39 confusable map — characters that NFKC does NOT resolve.
# Source: Unicode Security Mechanisms for UTS #39, confusables.txt
# URL: https://www.unicode.org/Public/security/latest/confusables.txt
# Version: 17.0.0 (2025-07-22)
# Scope: 669 single-codepoint → ASCII letter/digit mappings across
#         69 scripts (Cyrillic, Greek, Armenian, Cherokee, Coptic,
#         Lisu, Warang Citi, Mathematical, and 61+ others).
# Generation: Programmatically extracted — see scripts/gen_confusables.py.
# Only entries where NFKC(source) ≠ target are included.
_CONFUSABLE_TO_ASCII = {
    "\u00D7": "x",  # MULTIPLICATION SIGN
    "\u00FE": "p",  # LATIN SMALL LETTER THORN
    "\u0131": "i",  # LATIN SMALL LETTER DOTLESS I
    "\u017F": "f",  # LATIN SMALL LETTER LONG S
    "\u0184": "b",  # LATIN CAPITAL LETTER TONE SIX
    "\u018D": "g",  # LATIN SMALL LETTER TURNED DELTA
    "\u0192": "f",  # LATIN SMALL LETTER F WITH HOOK
    "\u0196": "l",  # LATIN CAPITAL LETTER IOTA
    "\u01A6": "R",  # LATIN LETTER YR
    "\u01A7": "2",  # LATIN CAPITAL LETTER TONE TWO
    "\u01B7": "3",  # LATIN CAPITAL LETTER EZH
    "\u01BC": "5",  # LATIN CAPITAL LETTER TONE FIVE
    "\u01BD": "s",  # LATIN SMALL LETTER TONE FIVE
    "\u01BF": "p",  # LATIN LETTER WYNN
    "\u01C0": "l",  # LATIN LETTER DENTAL CLICK
    "\u021C": "3",  # LATIN CAPITAL LETTER YOGH
    "\u0222": "8",  # LATIN CAPITAL LETTER OU
    "\u0223": "8",  # LATIN SMALL LETTER OU
    "\u0251": "a",  # LATIN SMALL LETTER ALPHA
    "\u0261": "g",  # LATIN SMALL LETTER SCRIPT G
    "\u0263": "y",  # LATIN SMALL LETTER GAMMA
    "\u0269": "i",  # LATIN SMALL LETTER IOTA
    "\u026A": "i",  # LATIN LETTER SMALL CAPITAL I
    "\u026F": "w",  # LATIN SMALL LETTER TURNED M
    "\u028B": "u",  # LATIN SMALL LETTER V WITH HOOK
    "\u028F": "y",  # LATIN LETTER SMALL CAPITAL Y
    "\u02DB": "i",  # OGONEK
    "\u037A": "i",  # GREEK YPOGEGRAMMENI
    "\u037F": "J",  # GREEK CAPITAL LETTER YOT
    "\u0391": "A",  # GREEK CAPITAL LETTER ALPHA
    "\u0392": "B",  # GREEK CAPITAL LETTER BETA
    "\u0395": "E",  # GREEK CAPITAL LETTER EPSILON
    "\u0396": "Z",  # GREEK CAPITAL LETTER ZETA
    "\u0397": "H",  # GREEK CAPITAL LETTER ETA
    "\u0399": "l",  # GREEK CAPITAL LETTER IOTA
    "\u039A": "K",  # GREEK CAPITAL LETTER KAPPA
    "\u039C": "M",  # GREEK CAPITAL LETTER MU
    "\u039D": "N",  # GREEK CAPITAL LETTER NU
    "\u039F": "O",  # GREEK CAPITAL LETTER OMICRON
    "\u03A1": "P",  # GREEK CAPITAL LETTER RHO
    "\u03A4": "T",  # GREEK CAPITAL LETTER TAU
    "\u03A5": "Y",  # GREEK CAPITAL LETTER UPSILON
    "\u03A7": "X",  # GREEK CAPITAL LETTER CHI
    "\u03B1": "a",  # GREEK SMALL LETTER ALPHA
    "\u03B3": "y",  # GREEK SMALL LETTER GAMMA
    "\u03B9": "i",  # GREEK SMALL LETTER IOTA
    "\u03BD": "v",  # GREEK SMALL LETTER NU
    "\u03BF": "o",  # GREEK SMALL LETTER OMICRON
    "\u03C1": "p",  # GREEK SMALL LETTER RHO
    "\u03C3": "o",  # GREEK SMALL LETTER SIGMA
    "\u03C5": "u",  # GREEK SMALL LETTER UPSILON
    "\u03D2": "Y",  # GREEK UPSILON WITH HOOK SYMBOL
    "\u03DC": "F",  # GREEK LETTER DIGAMMA
    "\u03E8": "2",  # COPTIC CAPITAL LETTER HORI
    "\u03EC": "6",  # COPTIC CAPITAL LETTER SHIMA
    "\u03ED": "o",  # COPTIC SMALL LETTER SHIMA
    "\u03F1": "p",  # GREEK RHO SYMBOL
    "\u03F2": "c",  # GREEK LUNATE SIGMA SYMBOL
    "\u03F3": "j",  # GREEK LETTER YOT
    "\u03F8": "p",  # GREEK SMALL LETTER SHO
    "\u03F9": "C",  # GREEK CAPITAL LUNATE SIGMA SYMBOL
    "\u03FA": "M",  # GREEK CAPITAL LETTER SAN
    "\u0405": "S",  # CYRILLIC CAPITAL LETTER DZE
    "\u0406": "l",  # CYRILLIC CAPITAL LETTER BYELORUSSIAN-UKRAINIAN I
    "\u0408": "J",  # CYRILLIC CAPITAL LETTER JE
    "\u0410": "A",  # CYRILLIC CAPITAL LETTER A
    "\u0412": "B",  # CYRILLIC CAPITAL LETTER VE
    "\u0415": "E",  # CYRILLIC CAPITAL LETTER IE
    "\u0417": "3",  # CYRILLIC CAPITAL LETTER ZE
    "\u041A": "K",  # CYRILLIC CAPITAL LETTER KA
    "\u041C": "M",  # CYRILLIC CAPITAL LETTER EM
    "\u041D": "H",  # CYRILLIC CAPITAL LETTER EN
    "\u041E": "O",  # CYRILLIC CAPITAL LETTER O
    "\u0420": "P",  # CYRILLIC CAPITAL LETTER ER
    "\u0421": "C",  # CYRILLIC CAPITAL LETTER ES
    "\u0422": "T",  # CYRILLIC CAPITAL LETTER TE
    "\u0423": "Y",  # CYRILLIC CAPITAL LETTER U
    "\u0425": "X",  # CYRILLIC CAPITAL LETTER HA
    "\u042C": "b",  # CYRILLIC CAPITAL LETTER SOFT SIGN
    "\u0430": "a",  # CYRILLIC SMALL LETTER A
    "\u0431": "6",  # CYRILLIC SMALL LETTER BE
    "\u0433": "r",  # CYRILLIC SMALL LETTER GHE
    "\u0435": "e",  # CYRILLIC SMALL LETTER IE
    "\u043E": "o",  # CYRILLIC SMALL LETTER O
    "\u0440": "p",  # CYRILLIC SMALL LETTER ER
    "\u0441": "c",  # CYRILLIC SMALL LETTER ES
    "\u0443": "y",  # CYRILLIC SMALL LETTER U
    "\u0445": "x",  # CYRILLIC SMALL LETTER HA
    "\u0448": "w",  # CYRILLIC SMALL LETTER SHA
    "\u0455": "s",  # CYRILLIC SMALL LETTER DZE
    "\u0456": "i",  # CYRILLIC SMALL LETTER BYELORUSSIAN-UKRAINIAN I
    "\u0458": "j",  # CYRILLIC SMALL LETTER JE
    "\u0461": "w",  # CYRILLIC SMALL LETTER OMEGA
    "\u0474": "V",  # CYRILLIC CAPITAL LETTER IZHITSA
    "\u0475": "v",  # CYRILLIC SMALL LETTER IZHITSA
    "\u04AE": "Y",  # CYRILLIC CAPITAL LETTER STRAIGHT U
    "\u04AF": "y",  # CYRILLIC SMALL LETTER STRAIGHT U
    "\u04BB": "h",  # CYRILLIC SMALL LETTER SHHA
    "\u04BD": "e",  # CYRILLIC SMALL LETTER ABKHASIAN CHE
    "\u04C0": "l",  # CYRILLIC LETTER PALOCHKA
    "\u04CF": "l",  # CYRILLIC SMALL LETTER PALOCHKA
    "\u04E0": "3",  # CYRILLIC CAPITAL LETTER ABKHASIAN DZE
    "\u0501": "d",  # CYRILLIC SMALL LETTER KOMI DE
    "\u050C": "G",  # CYRILLIC CAPITAL LETTER KOMI SJE
    "\u051B": "q",  # CYRILLIC SMALL LETTER QA
    "\u051C": "W",  # CYRILLIC CAPITAL LETTER WE
    "\u051D": "w",  # CYRILLIC SMALL LETTER WE
    "\u054D": "U",  # ARMENIAN CAPITAL LETTER SEH
    "\u054F": "S",  # ARMENIAN CAPITAL LETTER TIWN
    "\u0555": "O",  # ARMENIAN CAPITAL LETTER OH
    "\u0561": "w",  # ARMENIAN SMALL LETTER AYB
    "\u0563": "q",  # ARMENIAN SMALL LETTER GIM
    "\u0566": "q",  # ARMENIAN SMALL LETTER ZA
    "\u0570": "h",  # ARMENIAN SMALL LETTER HO
    "\u0578": "n",  # ARMENIAN SMALL LETTER VO
    "\u057C": "n",  # ARMENIAN SMALL LETTER RA
    "\u057D": "u",  # ARMENIAN SMALL LETTER SEH
    "\u0581": "g",  # ARMENIAN SMALL LETTER CO
    "\u0582": "i",  # ARMENIAN SMALL LETTER YIWN
    "\u0584": "f",  # ARMENIAN SMALL LETTER KEH
    "\u0585": "o",  # ARMENIAN SMALL LETTER OH
    "\u05C0": "l",  # HEBREW PUNCTUATION PASEQ
    "\u05D5": "l",  # HEBREW LETTER VAV
    "\u05D8": "v",  # HEBREW LETTER TET
    "\u05DF": "l",  # HEBREW LETTER FINAL NUN
    "\u05E1": "o",  # HEBREW LETTER SAMEKH
    "\u0627": "l",  # ARABIC LETTER ALEF
    "\u0647": "o",  # ARABIC LETTER HEH
    "\u0661": "l",  # ARABIC-INDIC DIGIT ONE
    "\u0665": "o",  # ARABIC-INDIC DIGIT FIVE
    "\u0667": "V",  # ARABIC-INDIC DIGIT SEVEN
    "\u06BE": "o",  # ARABIC LETTER HEH DOACHASHMEE
    "\u06C1": "o",  # ARABIC LETTER HEH GOAL
    "\u06D5": "o",  # ARABIC LETTER AE
    "\u06F1": "l",  # EXTENDED ARABIC-INDIC DIGIT ONE
    "\u06F5": "o",  # EXTENDED ARABIC-INDIC DIGIT FIVE
    "\u06F7": "V",  # EXTENDED ARABIC-INDIC DIGIT SEVEN
    "\u07C0": "O",  # NKO DIGIT ZERO
    "\u07CA": "l",  # NKO LETTER A
    "\u0966": "o",  # DEVANAGARI DIGIT ZERO
    "\u0969": "3",  # DEVANAGARI DIGIT THREE
    "\u09E6": "o",  # BENGALI DIGIT ZERO
    "\u09EA": "8",  # BENGALI DIGIT FOUR
    "\u09ED": "9",  # BENGALI DIGIT SEVEN
    "\u0A66": "o",  # GURMUKHI DIGIT ZERO
    "\u0A67": "9",  # GURMUKHI DIGIT ONE
    "\u0A6A": "8",  # GURMUKHI DIGIT FOUR
    "\u0AE6": "o",  # GUJARATI DIGIT ZERO
    "\u0AE9": "3",  # GUJARATI DIGIT THREE
    "\u0B03": "8",  # ORIYA SIGN VISARGA
    "\u0B20": "O",  # ORIYA LETTER TTHA
    "\u0B66": "o",  # ORIYA DIGIT ZERO
    "\u0B68": "9",  # ORIYA DIGIT TWO
    "\u0BE6": "o",  # TAMIL DIGIT ZERO
    "\u0C02": "o",  # TELUGU SIGN ANUSVARA
    "\u0C66": "o",  # TELUGU DIGIT ZERO
    "\u0C82": "o",  # KANNADA SIGN ANUSVARA
    "\u0CE6": "O",  # KANNADA DIGIT ZERO
    "\u0D02": "o",  # MALAYALAM SIGN ANUSVARA
    "\u0D1F": "s",  # MALAYALAM LETTER TTA
    "\u0D20": "o",  # MALAYALAM LETTER TTHA
    "\u0D66": "o",  # MALAYALAM DIGIT ZERO
    "\u0D6D": "9",  # MALAYALAM DIGIT SEVEN
    "\u0D82": "o",  # SINHALA SIGN ANUSVARAYA
    "\u0E50": "o",  # THAI DIGIT ZERO
    "\u0ED0": "o",  # LAO DIGIT ZERO
    "\u1004": "c",  # MYANMAR LETTER NGA
    "\u101D": "o",  # MYANMAR LETTER WA
    "\u1040": "o",  # MYANMAR DIGIT ZERO
    "\u105A": "c",  # MYANMAR LETTER MON NGA
    "\u10E7": "y",  # GEORGIAN LETTER QAR
    "\u10FF": "o",  # GEORGIAN LETTER LABIAL SIGN
    "\u1200": "U",  # ETHIOPIC SYLLABLE HA
    "\u12D0": "O",  # ETHIOPIC SYLLABLE PHARYNGEAL A
    "\u13A0": "D",  # CHEROKEE LETTER A
    "\u13A1": "R",  # CHEROKEE LETTER E
    "\u13A2": "T",  # CHEROKEE LETTER I
    "\u13A5": "i",  # CHEROKEE LETTER V
    "\u13A9": "Y",  # CHEROKEE LETTER GI
    "\u13AA": "A",  # CHEROKEE LETTER GO
    "\u13AB": "J",  # CHEROKEE LETTER GU
    "\u13AC": "E",  # CHEROKEE LETTER GV
    "\u13B3": "W",  # CHEROKEE LETTER LA
    "\u13B7": "M",  # CHEROKEE LETTER LU
    "\u13BB": "H",  # CHEROKEE LETTER MI
    "\u13BD": "Y",  # CHEROKEE LETTER MU
    "\u13C0": "G",  # CHEROKEE LETTER NAH
    "\u13C2": "h",  # CHEROKEE LETTER NI
    "\u13C3": "Z",  # CHEROKEE LETTER NO
    "\u13CE": "4",  # CHEROKEE LETTER SE
    "\u13CF": "b",  # CHEROKEE LETTER SI
    "\u13D2": "R",  # CHEROKEE LETTER SV
    "\u13D4": "W",  # CHEROKEE LETTER TA
    "\u13D5": "S",  # CHEROKEE LETTER DE
    "\u13D9": "V",  # CHEROKEE LETTER DO
    "\u13DA": "S",  # CHEROKEE LETTER DU
    "\u13DE": "L",  # CHEROKEE LETTER TLE
    "\u13DF": "C",  # CHEROKEE LETTER TLI
    "\u13E2": "P",  # CHEROKEE LETTER TLV
    "\u13E6": "K",  # CHEROKEE LETTER TSO
    "\u13E7": "d",  # CHEROKEE LETTER TSU
    "\u13EE": "6",  # CHEROKEE LETTER WV
    "\u13F3": "G",  # CHEROKEE LETTER YU
    "\u13F4": "B",  # CHEROKEE LETTER YV
    "\u142F": "V",  # CANADIAN SYLLABICS PE
    "\u144C": "U",  # CANADIAN SYLLABICS TE
    "\u146D": "P",  # CANADIAN SYLLABICS KI
    "\u146F": "d",  # CANADIAN SYLLABICS KO
    "\u1472": "b",  # CANADIAN SYLLABICS KA
    "\u148D": "J",  # CANADIAN SYLLABICS CO
    "\u14AA": "L",  # CANADIAN SYLLABICS MA
    "\u14BF": "2",  # CANADIAN SYLLABICS SAYISI M
    "\u1541": "x",  # CANADIAN SYLLABICS SAYISI YI
    "\u157C": "H",  # CANADIAN SYLLABICS NUNAVUT H
    "\u157D": "x",  # CANADIAN SYLLABICS HK
    "\u1587": "R",  # CANADIAN SYLLABICS TLHI
    "\u15AF": "b",  # CANADIAN SYLLABICS AIVILIK B
    "\u15B4": "F",  # CANADIAN SYLLABICS BLACKFOOT WE
    "\u15C5": "A",  # CANADIAN SYLLABICS CARRIER GHO
    "\u15DE": "D",  # CANADIAN SYLLABICS CARRIER THE
    "\u15EA": "D",  # CANADIAN SYLLABICS CARRIER PE
    "\u15F0": "M",  # CANADIAN SYLLABICS CARRIER GO
    "\u15F7": "B",  # CANADIAN SYLLABICS CARRIER KHE
    "\u166D": "X",  # CANADIAN SYLLABICS CHI SIGN
    "\u166E": "x",  # CANADIAN SYLLABICS FULL STOP
    "\u16B7": "X",  # RUNIC LETTER GEBO GYFU G
    "\u16C1": "l",  # RUNIC LETTER ISAZ IS ISS I
    "\u16D5": "K",  # RUNIC LETTER OPEN-P
    "\u16D6": "M",  # RUNIC LETTER EHWAZ EH E
    "\u17E0": "o",  # KHMER DIGIT ZERO
    "\u1D04": "c",  # LATIN LETTER SMALL CAPITAL C
    "\u1D0F": "o",  # LATIN LETTER SMALL CAPITAL O
    "\u1D11": "o",  # LATIN SMALL LETTER SIDEWAYS O
    "\u1D1C": "u",  # LATIN LETTER SMALL CAPITAL U
    "\u1D20": "v",  # LATIN LETTER SMALL CAPITAL V
    "\u1D21": "w",  # LATIN LETTER SMALL CAPITAL W
    "\u1D22": "z",  # LATIN LETTER SMALL CAPITAL Z
    "\u1D26": "r",  # GREEK LETTER SMALL CAPITAL GAMMA
    "\u1D83": "g",  # LATIN SMALL LETTER G WITH PALATAL HOOK
    "\u1D8C": "y",  # LATIN SMALL LETTER V WITH PALATAL HOOK
    "\u1E9D": "f",  # LATIN SMALL LETTER LONG S WITH HIGH STROKE
    "\u1EFF": "y",  # LATIN SMALL LETTER Y WITH LOOP
    "\u1FBE": "i",  # GREEK PROSGEGRAMMENI
    "\u2110": "l",  # SCRIPT CAPITAL I
    "\u2111": "l",  # BLACK-LETTER CAPITAL I
    "\u212E": "e",  # ESTIMATED SYMBOL
    "\u213D": "y",  # DOUBLE-STRUCK SMALL GAMMA
    "\u2160": "l",  # ROMAN NUMERAL ONE
    "\u2223": "l",  # DIVIDES
    "\u2228": "v",  # LOGICAL OR
    "\u222A": "U",  # UNION
    "\u22A4": "T",  # DOWN TACK
    "\u22C1": "v",  # N-ARY LOGICAL OR
    "\u22C3": "U",  # N-ARY UNION
    "\u22FF": "E",  # Z NOTATION BAG MEMBERSHIP
    "\u2373": "i",  # APL FUNCTIONAL SYMBOL IOTA
    "\u2374": "p",  # APL FUNCTIONAL SYMBOL RHO
    "\u237A": "a",  # APL FUNCTIONAL SYMBOL ALPHA
    "\u23FD": "l",  # POWER ON SYMBOL
    "\u2573": "X",  # BOX DRAWINGS LIGHT DIAGONAL CROSS
    "\u27D9": "T",  # LARGE DOWN TACK
    "\u292B": "x",  # RISING DIAGONAL CROSSING FALLING DIAGONAL
    "\u292C": "x",  # FALLING DIAGONAL CROSSING RISING DIAGONAL
    "\u2A2F": "x",  # VECTOR OR CROSS PRODUCT
    "\u2C82": "B",  # COPTIC CAPITAL LETTER VIDA
    "\u2C85": "r",  # COPTIC SMALL LETTER GAMMA
    "\u2C8E": "H",  # COPTIC CAPITAL LETTER HATE
    "\u2C92": "l",  # COPTIC CAPITAL LETTER IAUDA
    "\u2C93": "i",  # COPTIC SMALL LETTER IAUDA
    "\u2C94": "K",  # COPTIC CAPITAL LETTER KAPA
    "\u2C98": "M",  # COPTIC CAPITAL LETTER MI
    "\u2C9A": "N",  # COPTIC CAPITAL LETTER NI
    "\u2C9C": "3",  # COPTIC CAPITAL LETTER KSI
    "\u2C9E": "O",  # COPTIC CAPITAL LETTER O
    "\u2C9F": "o",  # COPTIC SMALL LETTER O
    "\u2CA2": "P",  # COPTIC CAPITAL LETTER RO
    "\u2CA3": "p",  # COPTIC SMALL LETTER RO
    "\u2CA4": "C",  # COPTIC CAPITAL LETTER SIMA
    "\u2CA5": "c",  # COPTIC SMALL LETTER SIMA
    "\u2CA6": "T",  # COPTIC CAPITAL LETTER TAU
    "\u2CA8": "Y",  # COPTIC CAPITAL LETTER UA
    "\u2CA9": "y",  # COPTIC SMALL LETTER UA
    "\u2CAC": "X",  # COPTIC CAPITAL LETTER KHI
    "\u2CBD": "w",  # COPTIC SMALL LETTER CRYPTOGRAMMIC NI
    "\u2CC4": "3",  # COPTIC CAPITAL LETTER OLD COPTIC SHEI
    "\u2CCA": "9",  # COPTIC CAPITAL LETTER DIALECT-P HORI
    "\u2CCB": "9",  # COPTIC SMALL LETTER DIALECT-P HORI
    "\u2CCC": "3",  # COPTIC CAPITAL LETTER OLD COPTIC HORI
    "\u2CCE": "P",  # COPTIC CAPITAL LETTER OLD COPTIC HA
    "\u2CCF": "p",  # COPTIC SMALL LETTER OLD COPTIC HA
    "\u2CD0": "L",  # COPTIC CAPITAL LETTER L-SHAPED HA
    "\u2CD2": "6",  # COPTIC CAPITAL LETTER OLD COPTIC HEI
    "\u2CD3": "6",  # COPTIC SMALL LETTER OLD COPTIC HEI
    "\u2CDC": "6",  # COPTIC CAPITAL LETTER OLD NUBIAN SHIMA
    "\u2D38": "V",  # TIFINAGH LETTER YADH
    "\u2D39": "E",  # TIFINAGH LETTER YADD
    "\u2D4F": "l",  # TIFINAGH LETTER YAN
    "\u2D54": "O",  # TIFINAGH LETTER YAR
    "\u2D55": "Q",  # TIFINAGH LETTER YARR
    "\u2D5D": "X",  # TIFINAGH LETTER YATH
    "\u3007": "O",  # IDEOGRAPHIC NUMBER ZERO
    "\uA4D0": "B",  # LISU LETTER BA
    "\uA4D1": "P",  # LISU LETTER PA
    "\uA4D2": "d",  # LISU LETTER PHA
    "\uA4D3": "D",  # LISU LETTER DA
    "\uA4D4": "T",  # LISU LETTER TA
    "\uA4D6": "G",  # LISU LETTER GA
    "\uA4D7": "K",  # LISU LETTER KA
    "\uA4D9": "J",  # LISU LETTER JA
    "\uA4DA": "C",  # LISU LETTER CA
    "\uA4DC": "Z",  # LISU LETTER DZA
    "\uA4DD": "F",  # LISU LETTER TSA
    "\uA4DF": "M",  # LISU LETTER MA
    "\uA4E0": "N",  # LISU LETTER NA
    "\uA4E1": "L",  # LISU LETTER LA
    "\uA4E2": "S",  # LISU LETTER SA
    "\uA4E3": "R",  # LISU LETTER ZHA
    "\uA4E6": "V",  # LISU LETTER HA
    "\uA4E7": "H",  # LISU LETTER XA
    "\uA4EA": "W",  # LISU LETTER WA
    "\uA4EB": "X",  # LISU LETTER SHA
    "\uA4EC": "Y",  # LISU LETTER YA
    "\uA4EE": "A",  # LISU LETTER A
    "\uA4F0": "E",  # LISU LETTER E
    "\uA4F2": "l",  # LISU LETTER I
    "\uA4F3": "O",  # LISU LETTER O
    "\uA4F4": "U",  # LISU LETTER U
    "\uA644": "2",  # CYRILLIC CAPITAL LETTER REVERSED DZE
    "\uA647": "i",  # CYRILLIC SMALL LETTER IOTA
    "\uA6DF": "V",  # BAMUM LETTER KO
    "\uA6EF": "2",  # BAMUM LETTER KOGHOM
    "\uA731": "s",  # LATIN LETTER SMALL CAPITAL S
    "\uA75A": "2",  # LATIN CAPITAL LETTER R ROTUNDA
    "\uA76A": "3",  # LATIN CAPITAL LETTER ET
    "\uA76E": "9",  # LATIN CAPITAL LETTER CON
    "\uA798": "F",  # LATIN CAPITAL LETTER F WITH STROKE
    "\uA799": "f",  # LATIN SMALL LETTER F WITH STROKE
    "\uA79F": "u",  # LATIN SMALL LETTER VOLAPUK UE
    "\uA7AB": "3",  # LATIN CAPITAL LETTER REVERSED OPEN E
    "\uA7B2": "J",  # LATIN CAPITAL LETTER J WITH CROSSED-TAIL
    "\uA7B3": "X",  # LATIN CAPITAL LETTER CHI
    "\uA7B4": "B",  # LATIN CAPITAL LETTER BETA
    "\uAB32": "e",  # LATIN SMALL LETTER BLACKLETTER E
    "\uAB35": "f",  # LATIN SMALL LETTER LENIS F
    "\uAB3D": "o",  # LATIN SMALL LETTER BLACKLETTER O
    "\uAB47": "r",  # LATIN SMALL LETTER R WITHOUT HANDLE
    "\uAB48": "r",  # LATIN SMALL LETTER DOUBLE R
    "\uAB4E": "u",  # LATIN SMALL LETTER U WITH SHORT RIGHT LEG
    "\uAB52": "u",  # LATIN SMALL LETTER U WITH LEFT HOOK
    "\uAB5A": "y",  # LATIN SMALL LETTER Y WITH SHORT RIGHT LEG
    "\uAB75": "i",  # CHEROKEE SMALL LETTER V
    "\uAB81": "r",  # CHEROKEE SMALL LETTER HU
    "\uAB83": "w",  # CHEROKEE SMALL LETTER LA
    "\uAB93": "z",  # CHEROKEE SMALL LETTER NO
    "\uABA9": "v",  # CHEROKEE SMALL LETTER DO
    "\uABAA": "s",  # CHEROKEE SMALL LETTER DU
    "\uABAF": "c",  # CHEROKEE SMALL LETTER TLI
    "\uFBA6": "o",  # ARABIC LETTER HEH GOAL ISOLATED FORM
    "\uFBA7": "o",  # ARABIC LETTER HEH GOAL FINAL FORM
    "\uFBA8": "o",  # ARABIC LETTER HEH GOAL INITIAL FORM
    "\uFBA9": "o",  # ARABIC LETTER HEH GOAL MEDIAL FORM
    "\uFBAA": "o",  # ARABIC LETTER HEH DOACHASHMEE ISOLATED FORM
    "\uFBAB": "o",  # ARABIC LETTER HEH DOACHASHMEE FINAL FORM
    "\uFBAC": "o",  # ARABIC LETTER HEH DOACHASHMEE INITIAL FORM
    "\uFBAD": "o",  # ARABIC LETTER HEH DOACHASHMEE MEDIAL FORM
    "\uFE8D": "l",  # ARABIC LETTER ALEF ISOLATED FORM
    "\uFE8E": "l",  # ARABIC LETTER ALEF FINAL FORM
    "\uFEE9": "o",  # ARABIC LETTER HEH ISOLATED FORM
    "\uFEEA": "o",  # ARABIC LETTER HEH FINAL FORM
    "\uFEEB": "o",  # ARABIC LETTER HEH INITIAL FORM
    "\uFEEC": "o",  # ARABIC LETTER HEH MEDIAL FORM
    "\uFF29": "l",  # FULLWIDTH LATIN CAPITAL LETTER I
    "\uFFE8": "l",  # HALFWIDTH FORMS LIGHT VERTICAL
    "\U00010282": "B",  # LYCIAN LETTER B
    "\U00010286": "E",  # LYCIAN LETTER I
    "\U00010287": "F",  # LYCIAN LETTER W
    "\U0001028A": "l",  # LYCIAN LETTER J
    "\U00010290": "X",  # LYCIAN LETTER MM
    "\U00010292": "O",  # LYCIAN LETTER U
    "\U00010295": "P",  # LYCIAN LETTER R
    "\U00010296": "S",  # LYCIAN LETTER S
    "\U00010297": "T",  # LYCIAN LETTER T
    "\U000102A0": "A",  # CARIAN LETTER A
    "\U000102A1": "B",  # CARIAN LETTER P2
    "\U000102A2": "C",  # CARIAN LETTER D
    "\U000102A5": "F",  # CARIAN LETTER R
    "\U000102AB": "O",  # CARIAN LETTER O
    "\U000102B0": "M",  # CARIAN LETTER S
    "\U000102B1": "T",  # CARIAN LETTER C-18
    "\U000102B2": "Y",  # CARIAN LETTER U
    "\U000102B4": "X",  # CARIAN LETTER X
    "\U000102CF": "H",  # CARIAN LETTER E2
    "\U000102F5": "Z",  # COPTIC EPACT NUMBER THREE HUNDRED
    "\U00010301": "B",  # OLD ITALIC LETTER BE
    "\U00010302": "C",  # OLD ITALIC LETTER KE
    "\U00010309": "l",  # OLD ITALIC LETTER I
    "\U00010311": "M",  # OLD ITALIC LETTER SHE
    "\U00010315": "T",  # OLD ITALIC LETTER TE
    "\U00010317": "X",  # OLD ITALIC LETTER EKS
    "\U0001031A": "8",  # OLD ITALIC LETTER EF
    "\U00010320": "l",  # OLD ITALIC NUMERAL ONE
    "\U00010322": "X",  # OLD ITALIC NUMERAL TEN
    "\U00010404": "O",  # DESERET CAPITAL LETTER LONG O
    "\U00010415": "C",  # DESERET CAPITAL LETTER CHEE
    "\U0001041B": "L",  # DESERET CAPITAL LETTER ETH
    "\U00010420": "S",  # DESERET CAPITAL LETTER ZHEE
    "\U0001042C": "o",  # DESERET SMALL LETTER LONG O
    "\U0001043D": "c",  # DESERET SMALL LETTER CHEE
    "\U00010448": "s",  # DESERET SMALL LETTER ZHEE
    "\U000104B4": "R",  # OSAGE CAPITAL LETTER BRA
    "\U000104C2": "O",  # OSAGE CAPITAL LETTER O
    "\U000104CE": "U",  # OSAGE CAPITAL LETTER U
    "\U000104D2": "7",  # OSAGE CAPITAL LETTER ZA
    "\U000104EA": "o",  # OSAGE SMALL LETTER O
    "\U000104F6": "u",  # OSAGE SMALL LETTER U
    "\U00010513": "N",  # ELBASAN LETTER NE
    "\U00010516": "O",  # ELBASAN LETTER O
    "\U00010518": "K",  # ELBASAN LETTER QE
    "\U0001051C": "C",  # ELBASAN LETTER SHE
    "\U0001051D": "V",  # ELBASAN LETTER TE
    "\U00010525": "F",  # ELBASAN LETTER GHE
    "\U00010526": "L",  # ELBASAN LETTER GHAMMA
    "\U00010527": "X",  # ELBASAN LETTER KHE
    "\U000114D0": "o",  # TIRHUTA DIGIT ZERO
    "\U00011706": "v",  # AHOM LETTER PA
    "\U0001170A": "w",  # AHOM LETTER JA
    "\U0001170E": "w",  # AHOM LETTER LA
    "\U0001170F": "w",  # AHOM LETTER SA
    "\U000118A0": "V",  # WARANG CITI CAPITAL LETTER NGAA
    "\U000118A2": "F",  # WARANG CITI CAPITAL LETTER WI
    "\U000118A3": "L",  # WARANG CITI CAPITAL LETTER YU
    "\U000118A4": "Y",  # WARANG CITI CAPITAL LETTER YA
    "\U000118A6": "E",  # WARANG CITI CAPITAL LETTER II
    "\U000118A9": "Z",  # WARANG CITI CAPITAL LETTER O
    "\U000118AC": "9",  # WARANG CITI CAPITAL LETTER KO
    "\U000118AE": "E",  # WARANG CITI CAPITAL LETTER YUJ
    "\U000118AF": "4",  # WARANG CITI CAPITAL LETTER UC
    "\U000118B2": "L",  # WARANG CITI CAPITAL LETTER TTE
    "\U000118B5": "O",  # WARANG CITI CAPITAL LETTER AT
    "\U000118B8": "U",  # WARANG CITI CAPITAL LETTER PU
    "\U000118BB": "5",  # WARANG CITI CAPITAL LETTER HORR
    "\U000118BC": "T",  # WARANG CITI CAPITAL LETTER HAR
    "\U000118C0": "v",  # WARANG CITI SMALL LETTER NGAA
    "\U000118C1": "s",  # WARANG CITI SMALL LETTER A
    "\U000118C2": "F",  # WARANG CITI SMALL LETTER WI
    "\U000118C3": "i",  # WARANG CITI SMALL LETTER YU
    "\U000118C4": "z",  # WARANG CITI SMALL LETTER YA
    "\U000118C6": "7",  # WARANG CITI SMALL LETTER II
    "\U000118C8": "o",  # WARANG CITI SMALL LETTER E
    "\U000118CA": "3",  # WARANG CITI SMALL LETTER ANG
    "\U000118CC": "9",  # WARANG CITI SMALL LETTER KO
    "\U000118D5": "6",  # WARANG CITI SMALL LETTER AT
    "\U000118D6": "9",  # WARANG CITI SMALL LETTER AM
    "\U000118D7": "o",  # WARANG CITI SMALL LETTER BU
    "\U000118D8": "u",  # WARANG CITI SMALL LETTER PU
    "\U000118DC": "y",  # WARANG CITI SMALL LETTER HAR
    "\U000118E0": "O",  # WARANG CITI DIGIT ZERO
    "\U000118E5": "Z",  # WARANG CITI DIGIT FIVE
    "\U000118E6": "W",  # WARANG CITI DIGIT SIX
    "\U000118E9": "C",  # WARANG CITI DIGIT NINE
    "\U000118EC": "X",  # WARANG CITI NUMBER THIRTY
    "\U000118EF": "W",  # WARANG CITI NUMBER SIXTY
    "\U000118F2": "C",  # WARANG CITI NUMBER NINETY
    "\U00011DDA": "l",  # UNKNOWN
    "\U00011DE0": "O",  # UNKNOWN
    "\U00011DE1": "l",  # UNKNOWN
    "\U00016EAA": "l",  # UNKNOWN
    "\U00016EB6": "b",  # UNKNOWN
    "\U00016F08": "V",  # MIAO LETTER VA
    "\U00016F0A": "T",  # MIAO LETTER TA
    "\U00016F16": "L",  # MIAO LETTER LA
    "\U00016F28": "l",  # MIAO LETTER GHA
    "\U00016F35": "R",  # MIAO LETTER ZHA
    "\U00016F3A": "S",  # MIAO LETTER SA
    "\U00016F3B": "3",  # MIAO LETTER ZA
    "\U00016F40": "A",  # MIAO LETTER ZZYA
    "\U00016F42": "U",  # MIAO LETTER WA
    "\U00016F43": "Y",  # MIAO LETTER AH
    "\U0001CCD6": "A",  # UNKNOWN
    "\U0001CCD7": "B",  # UNKNOWN
    "\U0001CCD8": "C",  # UNKNOWN
    "\U0001CCD9": "D",  # UNKNOWN
    "\U0001CCDA": "E",  # UNKNOWN
    "\U0001CCDB": "F",  # UNKNOWN
    "\U0001CCDC": "G",  # UNKNOWN
    "\U0001CCDD": "H",  # UNKNOWN
    "\U0001CCDE": "l",  # UNKNOWN
    "\U0001CCDF": "J",  # UNKNOWN
    "\U0001CCE0": "K",  # UNKNOWN
    "\U0001CCE1": "L",  # UNKNOWN
    "\U0001CCE2": "M",  # UNKNOWN
    "\U0001CCE3": "N",  # UNKNOWN
    "\U0001CCE4": "O",  # UNKNOWN
    "\U0001CCE5": "P",  # UNKNOWN
    "\U0001CCE6": "Q",  # UNKNOWN
    "\U0001CCE7": "R",  # UNKNOWN
    "\U0001CCE8": "S",  # UNKNOWN
    "\U0001CCE9": "T",  # UNKNOWN
    "\U0001CCEA": "U",  # UNKNOWN
    "\U0001CCEB": "V",  # UNKNOWN
    "\U0001CCEC": "W",  # UNKNOWN
    "\U0001CCED": "X",  # UNKNOWN
    "\U0001CCEE": "Y",  # UNKNOWN
    "\U0001CCEF": "Z",  # UNKNOWN
    "\U0001CCF0": "O",  # UNKNOWN
    "\U0001CCF1": "l",  # UNKNOWN
    "\U0001CCF2": "2",  # UNKNOWN
    "\U0001CCF3": "3",  # UNKNOWN
    "\U0001CCF4": "4",  # UNKNOWN
    "\U0001CCF5": "5",  # UNKNOWN
    "\U0001CCF6": "6",  # UNKNOWN
    "\U0001CCF7": "7",  # UNKNOWN
    "\U0001CCF8": "8",  # UNKNOWN
    "\U0001CCF9": "9",  # UNKNOWN
    "\U0001D206": "3",  # GREEK VOCAL NOTATION SYMBOL-7
    "\U0001D20D": "V",  # GREEK VOCAL NOTATION SYMBOL-14
    "\U0001D212": "7",  # GREEK VOCAL NOTATION SYMBOL-19
    "\U0001D213": "F",  # GREEK VOCAL NOTATION SYMBOL-20
    "\U0001D216": "R",  # GREEK VOCAL NOTATION SYMBOL-23
    "\U0001D22A": "L",  # GREEK INSTRUMENTAL NOTATION SYMBOL-23
    "\U0001D408": "l",  # MATHEMATICAL BOLD CAPITAL I
    "\U0001D43C": "l",  # MATHEMATICAL ITALIC CAPITAL I
    "\U0001D470": "l",  # MATHEMATICAL BOLD ITALIC CAPITAL I
    "\U0001D4D8": "l",  # MATHEMATICAL BOLD SCRIPT CAPITAL I
    "\U0001D540": "l",  # MATHEMATICAL DOUBLE-STRUCK CAPITAL I
    "\U0001D574": "l",  # MATHEMATICAL BOLD FRAKTUR CAPITAL I
    "\U0001D5A8": "l",  # MATHEMATICAL SANS-SERIF CAPITAL I
    "\U0001D5DC": "l",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL I
    "\U0001D610": "l",  # MATHEMATICAL SANS-SERIF ITALIC CAPITAL I
    "\U0001D644": "l",  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL I
    "\U0001D678": "l",  # MATHEMATICAL MONOSPACE CAPITAL I
    "\U0001D6A4": "i",  # MATHEMATICAL ITALIC SMALL DOTLESS I
    "\U0001D6A8": "A",  # MATHEMATICAL BOLD CAPITAL ALPHA
    "\U0001D6A9": "B",  # MATHEMATICAL BOLD CAPITAL BETA
    "\U0001D6AC": "E",  # MATHEMATICAL BOLD CAPITAL EPSILON
    "\U0001D6AD": "Z",  # MATHEMATICAL BOLD CAPITAL ZETA
    "\U0001D6AE": "H",  # MATHEMATICAL BOLD CAPITAL ETA
    "\U0001D6B0": "l",  # MATHEMATICAL BOLD CAPITAL IOTA
    "\U0001D6B1": "K",  # MATHEMATICAL BOLD CAPITAL KAPPA
    "\U0001D6B3": "M",  # MATHEMATICAL BOLD CAPITAL MU
    "\U0001D6B4": "N",  # MATHEMATICAL BOLD CAPITAL NU
    "\U0001D6B6": "O",  # MATHEMATICAL BOLD CAPITAL OMICRON
    "\U0001D6B8": "P",  # MATHEMATICAL BOLD CAPITAL RHO
    "\U0001D6BB": "T",  # MATHEMATICAL BOLD CAPITAL TAU
    "\U0001D6BC": "Y",  # MATHEMATICAL BOLD CAPITAL UPSILON
    "\U0001D6BE": "X",  # MATHEMATICAL BOLD CAPITAL CHI
    "\U0001D6C2": "a",  # MATHEMATICAL BOLD SMALL ALPHA
    "\U0001D6C4": "y",  # MATHEMATICAL BOLD SMALL GAMMA
    "\U0001D6CA": "i",  # MATHEMATICAL BOLD SMALL IOTA
    "\U0001D6CE": "v",  # MATHEMATICAL BOLD SMALL NU
    "\U0001D6D0": "o",  # MATHEMATICAL BOLD SMALL OMICRON
    "\U0001D6D2": "p",  # MATHEMATICAL BOLD SMALL RHO
    "\U0001D6D4": "o",  # MATHEMATICAL BOLD SMALL SIGMA
    "\U0001D6D6": "u",  # MATHEMATICAL BOLD SMALL UPSILON
    "\U0001D6E0": "p",  # MATHEMATICAL BOLD RHO SYMBOL
    "\U0001D6E2": "A",  # MATHEMATICAL ITALIC CAPITAL ALPHA
    "\U0001D6E3": "B",  # MATHEMATICAL ITALIC CAPITAL BETA
    "\U0001D6E6": "E",  # MATHEMATICAL ITALIC CAPITAL EPSILON
    "\U0001D6E7": "Z",  # MATHEMATICAL ITALIC CAPITAL ZETA
    "\U0001D6E8": "H",  # MATHEMATICAL ITALIC CAPITAL ETA
    "\U0001D6EA": "l",  # MATHEMATICAL ITALIC CAPITAL IOTA
    "\U0001D6EB": "K",  # MATHEMATICAL ITALIC CAPITAL KAPPA
    "\U0001D6ED": "M",  # MATHEMATICAL ITALIC CAPITAL MU
    "\U0001D6EE": "N",  # MATHEMATICAL ITALIC CAPITAL NU
    "\U0001D6F0": "O",  # MATHEMATICAL ITALIC CAPITAL OMICRON
    "\U0001D6F2": "P",  # MATHEMATICAL ITALIC CAPITAL RHO
    "\U0001D6F5": "T",  # MATHEMATICAL ITALIC CAPITAL TAU
    "\U0001D6F6": "Y",  # MATHEMATICAL ITALIC CAPITAL UPSILON
    "\U0001D6F8": "X",  # MATHEMATICAL ITALIC CAPITAL CHI
    "\U0001D6FC": "a",  # MATHEMATICAL ITALIC SMALL ALPHA
    "\U0001D6FE": "y",  # MATHEMATICAL ITALIC SMALL GAMMA
    "\U0001D704": "i",  # MATHEMATICAL ITALIC SMALL IOTA
    "\U0001D708": "v",  # MATHEMATICAL ITALIC SMALL NU
    "\U0001D70A": "o",  # MATHEMATICAL ITALIC SMALL OMICRON
    "\U0001D70C": "p",  # MATHEMATICAL ITALIC SMALL RHO
    "\U0001D70E": "o",  # MATHEMATICAL ITALIC SMALL SIGMA
    "\U0001D710": "u",  # MATHEMATICAL ITALIC SMALL UPSILON
    "\U0001D71A": "p",  # MATHEMATICAL ITALIC RHO SYMBOL
    "\U0001D71C": "A",  # MATHEMATICAL BOLD ITALIC CAPITAL ALPHA
    "\U0001D71D": "B",  # MATHEMATICAL BOLD ITALIC CAPITAL BETA
    "\U0001D720": "E",  # MATHEMATICAL BOLD ITALIC CAPITAL EPSILON
    "\U0001D721": "Z",  # MATHEMATICAL BOLD ITALIC CAPITAL ZETA
    "\U0001D722": "H",  # MATHEMATICAL BOLD ITALIC CAPITAL ETA
    "\U0001D724": "l",  # MATHEMATICAL BOLD ITALIC CAPITAL IOTA
    "\U0001D725": "K",  # MATHEMATICAL BOLD ITALIC CAPITAL KAPPA
    "\U0001D727": "M",  # MATHEMATICAL BOLD ITALIC CAPITAL MU
    "\U0001D728": "N",  # MATHEMATICAL BOLD ITALIC CAPITAL NU
    "\U0001D72A": "O",  # MATHEMATICAL BOLD ITALIC CAPITAL OMICRON
    "\U0001D72C": "P",  # MATHEMATICAL BOLD ITALIC CAPITAL RHO
    "\U0001D72F": "T",  # MATHEMATICAL BOLD ITALIC CAPITAL TAU
    "\U0001D730": "Y",  # MATHEMATICAL BOLD ITALIC CAPITAL UPSILON
    "\U0001D732": "X",  # MATHEMATICAL BOLD ITALIC CAPITAL CHI
    "\U0001D736": "a",  # MATHEMATICAL BOLD ITALIC SMALL ALPHA
    "\U0001D738": "y",  # MATHEMATICAL BOLD ITALIC SMALL GAMMA
    "\U0001D73E": "i",  # MATHEMATICAL BOLD ITALIC SMALL IOTA
    "\U0001D742": "v",  # MATHEMATICAL BOLD ITALIC SMALL NU
    "\U0001D744": "o",  # MATHEMATICAL BOLD ITALIC SMALL OMICRON
    "\U0001D746": "p",  # MATHEMATICAL BOLD ITALIC SMALL RHO
    "\U0001D748": "o",  # MATHEMATICAL BOLD ITALIC SMALL SIGMA
    "\U0001D74A": "u",  # MATHEMATICAL BOLD ITALIC SMALL UPSILON
    "\U0001D754": "p",  # MATHEMATICAL BOLD ITALIC RHO SYMBOL
    "\U0001D756": "A",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL ALPHA
    "\U0001D757": "B",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL BETA
    "\U0001D75A": "E",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL EPSILON
    "\U0001D75B": "Z",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL ZETA
    "\U0001D75C": "H",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL ETA
    "\U0001D75E": "l",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL IOTA
    "\U0001D75F": "K",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL KAPPA
    "\U0001D761": "M",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL MU
    "\U0001D762": "N",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL NU
    "\U0001D764": "O",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL OMICRON
    "\U0001D766": "P",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL RHO
    "\U0001D769": "T",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL TAU
    "\U0001D76A": "Y",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL UPSILON
    "\U0001D76C": "X",  # MATHEMATICAL SANS-SERIF BOLD CAPITAL CHI
    "\U0001D770": "a",  # MATHEMATICAL SANS-SERIF BOLD SMALL ALPHA
    "\U0001D772": "y",  # MATHEMATICAL SANS-SERIF BOLD SMALL GAMMA
    "\U0001D778": "i",  # MATHEMATICAL SANS-SERIF BOLD SMALL IOTA
    "\U0001D77C": "v",  # MATHEMATICAL SANS-SERIF BOLD SMALL NU
    "\U0001D77E": "o",  # MATHEMATICAL SANS-SERIF BOLD SMALL OMICRON
    "\U0001D780": "p",  # MATHEMATICAL SANS-SERIF BOLD SMALL RHO
    "\U0001D782": "o",  # MATHEMATICAL SANS-SERIF BOLD SMALL SIGMA
    "\U0001D784": "u",  # MATHEMATICAL SANS-SERIF BOLD SMALL UPSILON
    "\U0001D78E": "p",  # MATHEMATICAL SANS-SERIF BOLD RHO SYMBOL
    "\U0001D790": "A",  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL ALPHA
    "\U0001D791": "B",  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL BETA
    "\U0001D794": "E",  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL EPSILON
    "\U0001D795": "Z",  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL ZETA
    "\U0001D796": "H",  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL ETA
    "\U0001D798": "l",  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL IOTA
    "\U0001D799": "K",  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL KAPPA
    "\U0001D79B": "M",  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL MU
    "\U0001D79C": "N",  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL NU
    "\U0001D79E": "O",  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL OMICRON
    "\U0001D7A0": "P",  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL RHO
    "\U0001D7A3": "T",  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL TAU
    "\U0001D7A4": "Y",  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL UPSILON
    "\U0001D7A6": "X",  # MATHEMATICAL SANS-SERIF BOLD ITALIC CAPITAL CHI
    "\U0001D7AA": "a",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL ALPHA
    "\U0001D7AC": "y",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL GAMMA
    "\U0001D7B2": "i",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL IOTA
    "\U0001D7B6": "v",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL NU
    "\U0001D7B8": "o",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL OMICRON
    "\U0001D7BA": "p",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL RHO
    "\U0001D7BC": "o",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL SIGMA
    "\U0001D7BE": "u",  # MATHEMATICAL SANS-SERIF BOLD ITALIC SMALL UPSILON
    "\U0001D7C8": "p",  # MATHEMATICAL SANS-SERIF BOLD ITALIC RHO SYMBOL
    "\U0001D7CA": "F",  # MATHEMATICAL BOLD CAPITAL DIGAMMA
    "\U0001D7CE": "O",  # MATHEMATICAL BOLD DIGIT ZERO
    "\U0001D7CF": "l",  # MATHEMATICAL BOLD DIGIT ONE
    "\U0001D7D8": "O",  # MATHEMATICAL DOUBLE-STRUCK DIGIT ZERO
    "\U0001D7D9": "l",  # MATHEMATICAL DOUBLE-STRUCK DIGIT ONE
    "\U0001D7E2": "O",  # MATHEMATICAL SANS-SERIF DIGIT ZERO
    "\U0001D7E3": "l",  # MATHEMATICAL SANS-SERIF DIGIT ONE
    "\U0001D7EC": "O",  # MATHEMATICAL SANS-SERIF BOLD DIGIT ZERO
    "\U0001D7ED": "l",  # MATHEMATICAL SANS-SERIF BOLD DIGIT ONE
    "\U0001D7F6": "O",  # MATHEMATICAL MONOSPACE DIGIT ZERO
    "\U0001D7F7": "l",  # MATHEMATICAL MONOSPACE DIGIT ONE
    "\U0001E8C7": "l",  # MENDE KIKAKUI DIGIT ONE
    "\U0001E8CB": "8",  # MENDE KIKAKUI DIGIT FIVE
    "\U0001EE00": "l",  # ARABIC MATHEMATICAL ALEF
    "\U0001EE24": "o",  # ARABIC MATHEMATICAL INITIAL HEH
    "\U0001EE64": "o",  # ARABIC MATHEMATICAL STRETCHED HEH
    "\U0001EE80": "l",  # ARABIC MATHEMATICAL LOOPED ALEF
    "\U0001EE84": "o",  # ARABIC MATHEMATICAL LOOPED HEH
    "\U0001F74C": "C",  # ALCHEMICAL SYMBOL FOR CALX
    "\U0001F768": "T",  # ALCHEMICAL SYMBOL FOR CRUCIBLE-4
    "\U0001FBF0": "O",  # SEGMENTED DIGIT ZERO
    "\U0001FBF1": "l",  # SEGMENTED DIGIT ONE
}

# Unicode dash/hyphen variants that NFKC does NOT normalize to ASCII '-'.
# These are the delimiter in "co-authored-by" — missing them is a detection bypass.
_DASH_TO_ASCII = {
    "\u2010": "-",  # Hyphen (‐)
    "\u2011": "-",  # Non-breaking hyphen (‑)
    "\u2013": "-",  # En dash (–)
    "\u2014": "-",  # Em dash (—)
    "\u2015": "-",  # Horizontal bar (―)
    "\u2212": "-",  # Minus sign (−)
    "\u00AD": "-",  # Soft hyphen
    "\uFE58": "-",  # Small em dash (﹘)
    "\uFE63": "-",  # Small hyphen-minus (﹣) — NFKC covers this but be explicit
    "\uFF0D": "-",  # Fullwidth hyphen-minus (－) — NFKC covers this but be explicit
}


def _validate_ref(ref: str) -> str:
    """Reject refs that look like git options, path traversal, or shell metacharacters."""
    if ref.lstrip().startswith("-"):
        raise ValueError(f"Invalid git ref (looks like an option): {ref!r}")
    if "\x00" in ref:
        raise ValueError(f"Invalid git ref (contains NUL byte): {ref!r}")
    if "\n" in ref or "\r" in ref:
        raise ValueError(f"Invalid git ref (contains newline/CR): {ref!r}")
    if len(ref) > 1024:
        raise ValueError(f"Git ref too long ({len(ref)} chars, max 1024)")
    # Reject path traversal sequences — git rejects these too, but
    # defense-in-depth means catching them before they reach the subprocess.
    # IMPORTANT: '..' and '...' are valid git range operators (main..HEAD,
    # main...HEAD), so only reject path-traversal patterns like '../' or '/../'.
    if "/../" in ref or ref.startswith("../"):
        raise ValueError(f"Invalid git ref (contains path traversal): {ref!r}")
    # Reject shell metacharacters that have no place in a git ref.
    _SHELL_METACHARS = set(";&|$`!><{}()")
    found = _SHELL_METACHARS.intersection(ref)
    if found:
        raise ValueError(
            f"Invalid git ref (contains shell metacharacters {found!r}): {ref!r}"
        )
    return ref


def _sanitize_md(text: str) -> str:
    """Sanitize text for safe inclusion in GitHub Markdown step summaries.

    Escapes: \\ & < > | ` [ ! * _ ~ :// and dangerous Unicode (bidi, Cc, etc.).
    """
    # Strip dangerous Unicode control characters (RTL override, etc.)
    # Use targeted deny-list instead of blanket Cf strip, since we
    # intentionally use ZWSP (U+200B) below for autolink breaking.
    _DANGEROUS_CATEGORIES = {"Cc"}  # C0/C1 control codes
    _DANGEROUS_CODEPOINTS = {
        "\u200E", "\u200F",          # LRM, RLM
        "\u200C", "\u200D",          # ZWNJ, ZWJ (homoglyph risk)
        "\u202A", "\u202B", "\u202C", "\u202D", "\u202E",  # Bidi overrides
        "\u2066", "\u2067", "\u2068", "\u2069",              # Bidi isolates
        "\u00AD",                      # Soft hyphen
        "\uFEFF",                      # BOM / ZWNBSP
    }
    text = "".join(
        c for c in text
        if unicodedata.category(c) not in _DANGEROUS_CATEGORIES
        and c not in _DANGEROUS_CODEPOINTS
    )
    # Escape & → &amp; FIRST so that pre-encoded HTML entities
    # (e.g., &lt;script&gt;) become &amp;lt; and are displayed literally, not
    # decoded back to <script> by GFM renderers.
    text = text.replace("&", "&amp;")
    # Escape backslashes BEFORE all \-based escapes.  Without
    # this, a commit subject containing \| survives as \\| in the output,
    # and GFM interprets \\\\ as a literal backslash followed by | as a
    # pipe delimiter — breaking the summary table structure.  Similarly,
    # \* \_ \~ would bypass the emphasis escaping below.
    text = text.replace("\\", "\\\\")
    text = text.replace("|", "\\|")
    text = text.replace("`", "\\`")
    text = text.replace("[", "\\[")
    text = text.replace("!", "\\!")
    text = text.replace("<", "&lt;")
    text = text.replace(">", "&gt;")
    # Escape GFM emphasis/strikethrough markers to prevent
    # formatting injection in table cells (*bold*, _italic_, ~~strike~~).
    text = text.replace("*", "\\*")
    text = text.replace("_", "\\_")
    text = text.replace("~", "\\~")
    # Break GFM autolink detection to prevent phishing links in summaries
    text = text.replace("://", "\u200B://")
    return text


# ---------------------------------------------------------------------------
# Data classes
# ---------------------------------------------------------------------------


@dataclass
class CommitInfo:
    """Parsed git commit metadata."""

    sha: str
    author_name: str
    author_email: str
    author_date: str
    committer_name: str
    committer_email: str
    committer_date: str
    subject: str
    body: str
    diff_stat: str
    diff_hash: str  # SHA-256 of the full diff
    files_changed: List[str] = field(default_factory=list)
    ai_signals_detected: List[str] = field(default_factory=list)
    is_ai_authored: bool = False
    bot_signals_detected: List[str] = field(default_factory=list)
    is_bot_authored: bool = False
    # Structured authorship classification — first-class taxonomy.
    # Values: "human", "ai-assisted", "bot-generated", "ai+bot", "unknown".
    # Derived from is_ai_authored / is_bot_authored at detection time.
    authorship_class: str = "human"


# ---------------------------------------------------------------------------
# Terminal escape stripping
# ---------------------------------------------------------------------------


def _strip_terminal_escapes(text: str) -> str:
    """Strip ANSI escape sequences and ASCII control chars from text (R5-10).

    Prevents terminal injection via crafted commit subjects or author names
    (e.g., overwriting lines with ESC[A, changing colors, setting title).
    """
    # Strip ANSI CSI sequences (ESC[...X) and OSC sequences (ESC]...BEL/ST)
    # CSI final byte is 0x40-0x7E per ECMA-48, not just [A-Za-z].
    # Includes @, ~, {, |, } etc. (e.g., ESC[2~ = Insert key).
    text = re.sub(r'\x1b\[[0-9;]*[@-~]', '', text)
    # OSC terminator is optional — unterminated sequences (no BEL or ST)
    # must also be stripped to prevent payload leakage (same as PM/APC/SOS/DCS).
    text = re.sub(r'\x1b\][^\x07\x1b]*(?:\x07|\x1b\\)?', '', text)
    # Strip PM (ESC ^...ST) and APC (ESC _...ST) sequences.
    # Also strip SOS (ESC X...ST) and DCS (ESC P...ST) sequences.
    # ECMA-48 §5.6 defines six C1 control strings; we now cover all of them.
    # ST terminator is now optional — unterminated control strings
    # (payload with no ESC \) are also stripped to prevent payload leakage.
    text = re.sub(r'\x1b[\^_XP][^\x1b]*(?:\x1b\\)?', '', text)
    # Strip remaining control characters:
    # - C0 range (0x00-0x1F except tab)
    # - DEL (0x7F) — erases characters in some terminals
    # 8-bit C1 controls (0x80-0x9F) — single-byte equivalents of
    # ESC-based C1 sequences (e.g., U+009B = CSI, U+0090 = DCS). Some terminals
    # interpret these as control sequences even in UTF-8 mode.
    text = ''.join(
        c for c in text
        if (ord(c) >= 0x20 or c == '\t')
        and ord(c) != 0x7F
        and not (0x80 <= ord(c) <= 0x9F)
    )
    return text


# ---------------------------------------------------------------------------
# Git helpers (subprocess, no dependencies)
# ---------------------------------------------------------------------------


def _run_git(args: List[str], cwd: Optional[str] = None) -> str:
    """Run a git command and return stdout."""
    logger.debug("git %s (cwd=%s)", " ".join(args[:3]), cwd or os.getcwd())
    result = subprocess.run(
        ["git", "--no-optional-locks"] + args,
        cwd=cwd or os.getcwd(),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        encoding="utf-8",  # Explicit UTF-8 — git outputs UTF-8 but Windows defaults to cp1252
        errors="replace",   # Replace undecodable bytes rather than crash
        check=False,
        timeout=GIT_TIMEOUT,  # Prevent indefinite hangs
        env=_GIT_SAFE_ENV,  # Prevent auth hangs
    )
    if result.returncode != 0:
        # Truncate stderr and redact command args to prevent leaking
        # internal format strings, paths, or auth details
        stderr_safe = result.stderr.strip().split('\n')[0][:200]
        # Redact anything that looks like a filesystem path to
        # prevent leaking internal directory structure in error messages.
        stderr_safe = re.sub(r'/[\w./-]{5,}', '<path>', stderr_safe)
        # Strip terminal escape sequences — a crafted ref name
        # (e.g., containing ESC[2J) would be echoed in git's stderr and
        # survive the truncation + path-redaction above.
        stderr_safe = _strip_terminal_escapes(stderr_safe)
        subcmd = args[0] if args else "command"
        raise RuntimeError(f"git {subcmd} failed: {stderr_safe}")
    return result.stdout


# ---------------------------------------------------------------------------
# Hashing and serialization
# ---------------------------------------------------------------------------


def _sha256(data: str) -> str:
    """SHA-256 hex digest of a UTF-8 string."""
    return hashlib.sha256(data.encode("utf-8")).hexdigest()


def _canonical_json(obj: Any) -> str:
    """Deterministic JSON serialization (sorted keys, no whitespace).

    Uses an explicit depth limit instead of relying on Python's recursion limit.
    Prevents stack overflow from deeply nested JSON structures.
    """
    _check_json_depth(obj, max_depth=64)
    return json.dumps(
        obj, sort_keys=True, separators=(",", ":"),
        ensure_ascii=True, allow_nan=False,
    )


# Explicit depth checker for JSON structures.
_MAX_JSON_DEPTH = 64


def _check_json_depth(obj: Any, max_depth: int = _MAX_JSON_DEPTH) -> None:
    """Raise ValueError if a JSON structure exceeds max_depth nesting.

    Uses iterative stack-based traversal instead of recursion.
    The recursive version added to Python's call stack alongside any caller
    frames (e.g., MCP server → handler → verify → canonical_json → check),
    making the 64-level limit fragile under deep call chains.
    Removed dead `_current` parameter from old recursive API.
    """
    stack = [(obj, 0)]
    while stack:
        node, depth = stack.pop()
        if depth > max_depth:
            raise ValueError(f"JSON structure exceeds maximum depth of {max_depth}")
        if isinstance(node, dict):
            for v in node.values():
                stack.append((v, depth + 1))
        elif isinstance(node, (list, tuple)):
            for item in node:
                stack.append((item, depth + 1))


def _hash_diff_streaming(parent: str, sha: str, cwd: Optional[str] = None) -> str:
    """Stream-hash a git diff to avoid loading it all into memory.

    R3-02: stderr goes to DEVNULL to prevent bidirectional pipe deadlock.
    (If stdout and stderr are both PIPE and stderr fills the 64KB buffer,
    git blocks on stderr write while Python blocks on stdout read.)
    """
    # --no-ext-diff and --no-textconv prevent malicious .gitattributes
    # from invoking custom diff drivers/textconv filters that could inject
    # arbitrary data into the diff hash.
    proc = subprocess.Popen(
        ["git", "--no-optional-locks", "diff", "--no-ext-diff", "--no-textconv", parent, sha],
        cwd=cwd or os.getcwd(),
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        env=_GIT_SAFE_ENV,  # Consistent with _run_git
    )
    h = hashlib.sha256()
    # Track elapsed time to enforce timeout
    deadline = time.monotonic() + GIT_TIMEOUT
    try:
        while True:
            if time.monotonic() > deadline:
                proc.kill()
                proc.wait()  # Reap child to prevent zombie process
                raise RuntimeError(
                    f"git diff {parent} {sha} timed out after {GIT_TIMEOUT}s"
                )
            chunk = proc.stdout.read(65536)
            if not chunk:
                break
            h.update(chunk)
    except RuntimeError:
        raise  # Re-raise timeout error (already cleaned up above)
    except Exception:
        # Unexpected I/O error — kill and reap the subprocess
        proc.kill()
        proc.wait()
        raise
    finally:
        proc.stdout.close()
    # Final wait with timeout — kill if git hangs during cleanup.
    _killed_for_cleanup = False
    try:
        proc.wait(timeout=30)
    except subprocess.TimeoutExpired:  # pragma: no cover
        proc.kill()
        proc.wait()
        _killed_for_cleanup = True
    if proc.returncode != 0 and not _killed_for_cleanup:
        raise RuntimeError(f"git diff {parent} {sha} failed (exit code {proc.returncode})")
    return "sha256:" + h.hexdigest()


def _strip_url_credentials(url: str) -> str:
    """Remove embedded credentials and query params from a git remote URL."""
    try:
        parsed = urlparse(url)
        needs_clean = False
        clean_netloc = parsed.netloc
        if parsed.username or parsed.password:
            # Reconstruct without credentials
            clean_netloc = parsed.hostname or ""
            if parsed.port:
                clean_netloc += f":{parsed.port}"
            needs_clean = True
        # Strip query params and fragments that may contain tokens
        if parsed.query or parsed.fragment:
            needs_clean = True
        if needs_clean:
            return urlunparse(parsed._replace(
                netloc=clean_netloc, query="", fragment="",
            ))
    except Exception:  # pragma: no cover
        # If URL parsing/reconstruction fails, return a safe
        # placeholder instead of the original (which may contain credentials).
        # The old code did `pass` + `return url`, leaking embedded PATs.
        return "[credential-redacted-url]"
    return url


def _now_rfc3339() -> str:
    """Current time in RFC 3339 format."""
    return (
        datetime.now(timezone.utc)
        .replace(microsecond=0)
        .isoformat()
        .replace("+00:00", "Z")
    )


def get_repo_root(cwd: Optional[str] = None) -> str:
    """Get the git repository root."""
    return _run_git(["rev-parse", "--show-toplevel"], cwd=cwd).strip()


def _normalize_for_detection(text: str) -> str:
    """Normalize text for AI signal detection.

    Strips invisible/formatting characters, resolves Unicode homoglyphs,
    and removes combining marks to produce a canonical ASCII-ish string
    suitable for substring matching against known AI signals.

    Order: strip Cf → NFKC → confusable map → strip Mn/Me.
    """
    # Strip Cf (format chars: ZWJ, ZWNJ, ZWSP, variation selectors)
    # before NFKC to prevent zero-width insertion from affecting normalization.
    # EXCEPTION: U+00AD (soft hyphen) is Cf but should be converted to '-'
    # by _DASH_TO_ASCII, not stripped.  Stripping it removes the hyphen
    # entirely ("co\u00ADauthored" → "coauthored" instead of "co-authored").
    text = "".join(
        c for c in text
        if unicodedata.category(c) != "Cf" or c == "\u00AD"
    )
    # NFKC collapses compatibility variants (e.g., fullwidth Ｃ→C)
    text = unicodedata.normalize("NFKC", text)
    # Normalize Unicode dash/hyphen variants to ASCII '-'
    text = "".join(_DASH_TO_ASCII.get(c, c) for c in text)
    # Resolve cross-script homoglyphs that NFKC doesn't cover
    text = "".join(_CONFUSABLE_TO_ASCII.get(c, c) for c in text)
    # NFD decomposition before Mn stripping — NFKC sometimes composes
    # base+combining into a single precomposed codepoint (e.g., o+\u0303 → õ)
    # which has category Ll, not Mn, and would survive Mn stripping.
    # NFD decomposes it back so the combining mark can be stripped.
    text = unicodedata.normalize("NFD", text)
    # Strip combining marks (Mn) and enclosing marks (Me) — variation
    # selectors and diacriticals that survive NFKC
    text = "".join(
        c for c in text if unicodedata.category(c) not in ("Mn", "Me")
    )
    return text
